### ISSUE TITLE
Add screenshots or highlights tab

### ISSUE THREAD

**Issue by kinggoesgaming** [SpongePowered/Ore#105]
Although we can add pictures and stuff in the post... it would be nice if there is a dedicated tab for media and showcases related to a plugin. This way we can for example add youtube videos without breaking backwards compatibility with GH Flavored Markdown.

**Comment by windy1** [comment]
You can just create a new page for your media, that's kind of the whole point of allowing multiple pages. Embedded videos might be something we can do in the future. Also Ore doesn't use "GitHub Flavored Markdown" it uses custom styling to look similar to GH but there is no extra library involved or anything.
