### ISSUE TITLE
Improve project pagination

### ISSUE THREAD

**Issue by Aaron1011** [SpongePowered/Ore#107]
Currently, project pagination uses a 'More' button, which loads the next 'page' of projects with AJAX. These are then added to the bottom of the page.

While this method of pagination works well, it has a number of shortcomings:
- Navigating to a specific page/section is impossible. This is especially problematic when navigating back and forth between individual projects, as the user's position on the page will be lost. This results in the user needing to click 'More' repeatedly each time they go back to the projects view, in order to get back to their place.
- There is nothing indicating the number of results or 'pages' left. As more projects are created on Ore, browsing or searching through projects will become difficult.

There are a few ways these issues could be solved:
- Replace the current method of pagination with a standard list of pages (e.g. Google results). This makes keeping your place becomes simple, and has the advantage of already being familiar to most users.
- Expand the current system to a more Discourse-esque pagination style (doesn't necessarily have to be infinite scrolling). We would probably want to either add a way of jumping to an individual result, or (more likely) starting at a specific page or offset.

**Comment by Zidane** [comment]
I think pages work best.

**Comment by windy1** [comment]
I agree pages would probably be best, it's going to be become difficult to navigate with the current system. I think also the table rows should be bigger and include a bit more information about the project as well.

**Comment by MichaelFedora** [comment]
@windy1 , **there's no page-back button** xD . Just going to put this here instead of open a new issue.

Otherwise it looks great!

**Comment by windy1** [comment]
Thanks, will be fixed in next commit.
