### ISSUE TITLE
User Icons missing from the "more"/extended plugins list

### ISSUE THREAD

**Issue by MichaelFedora** [SpongePowered/Ore#108]
Browser & Version: `Chrome v49`

Operating System: `Win10 x64 Home`

Steps to reproduce:
- Go to Ore home-page
- Scroll down, and click the "More" button to view more projects
- Look at the atrocious lack of user icons for the "extended-view" plugins
- ???
- Profit

This also relates to #107, I guess. :3

**Comment by windy1** [comment]
Closing with #107 as the more button no longer exists.
