### ISSUE TITLE
Add support for secondary categories

### ISSUE THREAD

**Issue by kashike** [SpongePowered/Ore#111]
Currently, projects can have one category while it would be nice when searching to be able to search for projects which have categories `X`, `Y`, and `Z` instead of just `X`.
There could be one "primary" category, and multiple "secondary" categories - the icon from the primary category would be used for the icon/etc, secondary categories would be used for searching primarily.

**Comment by windy1** [comment]
I think I would like to keep the single category and add a stackoverflow-esque tagging system instead. Thoughts?

**Comment by ryantheleach** [comment]
I think it's pretty safe to say the future direction is tags.
