### ISSUE TITLE
Feature: Organizations / Groups

### ISSUE THREAD

**Issue by pschichtel** [SpongePowered/Ore#112]
This is something I liked about the old Ore implementation and what I like about Github/Gitlab: The ability to group projects and developers together.
In Gitlab's groups I can assign roles to members that allow them to create new projects themselves and all members of the group are automatically members of the projects.

Something like that would be nice to have for teams that develop multiple plugins.

**Comment by windy1** [comment]
Yes this is something that is definitely planned. I decided to put it off so I could get some of the core features out of the way first.

**Comment by windy1** [comment]
In progress: https://github.com/SpongePowered/Ore/tree/organizations

**Comment by windy1** [comment]
Merged
