### ISSUE TITLE
Multiple owners set on plugin entries

### ISSUE THREAD

**Issue by dualspiral** [SpongePowered/Ore#113]
When setting up a project on Ore, there is no option to set another user as an Owner, perhaps correctly so. When setting up Nucleus on there, I gave Hassan Developer privileges. However, something has happened and now on my project I can see that both of us are down as owners - something that I had never set, nor expected to happen as I can't set owners anyway.

Project in question: https://ore-staging.spongepowered.org/dualspiral/Nucleus

I've also seen this happen on https://ore-staging.spongepowered.org/windy/BookOTD, where mbaxter is also an owner of windy's project.

**Comment by windy1** [comment]
I had noticed this as well. The offending users aren't actually set as owners in the DB so it has something to do with how the title is displayed.

**Comment by windy1** [comment]
Doesn't appear to be an issue anymore. Please re-open if issue reappears.
