### ISSUE TITLE
Handle forums being unavailable temporarily

### ISSUE THREAD

**Issue by lukegb** [SpongePowered/Ore#114]
Ore needs to support the forums returning error responses, and it should not crash as a response. Since Ore sees an internal view of the network it has a higher likelihood of having error responses returned to it if it hits a backend which is unhealthy.

Current culprits:
- The login action should fail gracefully - maybe a message box saying "login is temporarily unavailable", rather than exploding?
- Topic updates are probably susceptible to this and need a more nuanced response

**Comment by windy1** [comment]
The first one would require a shift to async login since there's not really anyway of telling if it fails or not since it will just not redirect back to Ore. Agreed on topic updates will be working on that soon.
