### ISSUE TITLE
Error pages

### ISSUE THREAD

**Issue by lukegb** [SpongePowered/Ore#115]
In `/public/errors`, please provide the following static (i.e. untemplated) web pages:
- 502.html - this page will be shown if the backends are unreachable or, for staging, during deploys
- 500.html - a generic "the server done broke" page
- 404.html - a generic "nope, not found" page
- 400.html - a generic "WTF are you doing" page

Please make sure that any resources that these pages depend upon are inside the `/public/errors` directory (i.e. don't rely on the CSS/JS/images served by the rest of the app), and please refer to them absolutely under `/errors` because these assets will be served directly by the frontend and not by the app.

**Comment by pie-flavor** [comment]
@lukegb what if you used https://http.cat/
