### ISSUE TITLE
Add ability to download plugin version jar from API

### ISSUE THREAD

**Issue by simon816** [SpongePowered/Ore#116]
Currently there is no nice way to do this.

I get a plugin version info from [`projects/:pluginId/versions/:name`](https://ore-staging.spongepowered.org/api/v1/projects/bookotd/versions/1.0.0)
I then have to fetch the `href` tag on [`projects/:pluginId`](https://ore-staging.spongepowered.org/api/v1/projects/bookotd) which I make the assumption is in the format `/:author/:slug`
Then fetch the actual file from `/:author/:slug/versions/download/:version`
And it returns a zip? The jar file would be much more desirable.

**Comment by stephan-gh** [comment]
Ore currently always packages JAR files in an additional ZIP file, see https://github.com/SpongePowered/Ore/issues/94
