### ISSUE TITLE
Display MC version on frontpage layout

### ISSUE THREAD

**Issue by Dockter** [SpongePowered/Ore#118]
@windy1, recommend displaying the MC version a plugin is for on the front page.  The current versioning displayed on the pane is odd....

Image:  http://www.almuramc.com/images/Ore/MCVersion.png

**Comment by humaidq** [comment]
This might be helpful for Forge mods, but I don't see this required for Sponge plugins. It is already cluttered and adding the version or even Sponge API version might be too much clutter. The version currently looks messy already.
I am not sure, maybe with clever redesigning this feature might be more appealing to add.

**Comment by Dockter** [comment]
MC version is completely relevant here.  There needs to be an easy way to identify which plugin is for which version.  Having managed over 50 plugins spread out across 3 different version of Minecraft, I can tell you, its helpful.

**Comment by ryantheleach** [comment]
SpongeAPI version is what's needed, not Minecraft version. the API version can change independently of Minecraft versions, so theoretically if all 1.10 added was new content, and not major game rewriting, we could still be on API version 5 when that hits. 

And even that doesn't necessarily mean that old plugins will break.

What is needed is some way of showing the minimum, tested, version of the API used.

**Comment by humaidq** [comment]
@ryantheleach I agree, it should show it is the minimum tested version of the API that is known to work with the plugin. But it should not include the Minecraft version. However I am not sure about Ore accepting Forge plugins.

**Comment by windy1** [comment]
I actually don't think this will be displayed for now. But as of https://github.com/SpongePowered/Ore/commit/4ee5eab7c538cb457e35fe4bb5687290f5cdbd08 dependencies to both forge and spongeapi will be shown on the front page and hovering over them will show you the dependency version of the project's recommended version. [For reference](http://imgur.com/a/bXvAW)
