### ISSUE TITLE
Sponsorship Logo Rotation on Ore Header

### ISSUE THREAD

**Issue by Dockter** [SpongePowered/Ore#119]
@windy1, We need to show our project sponsors on the header of the Sponge Ore page. (photo below).

Image: http://www.almuramc.com/images/Ore/SponsorRotate.png

Ideal configuration would be rotation of logo's based on project contribution, higher the contribution the higher likelihood the image is displayed (configurable).

I also need Google Analytics tied into Ore.

**Comment by simon816** [comment]
That would interrupt the search bar though

**Comment by ewized** [comment]
Why not add it in the sidebar under categories?

**Comment by humaidq** [comment]
Google Analytics is already added with this commit 13d4493. I don't like and I am against the idea of putting sponsors across all Sponges sites. Homepage is fine and enough.

**Comment by Dockter** [comment]
"Fine enough" doesn't pay the bills...   The site(s) need to be able to generate revenue to pay for events such as Minecon, that is unless you would like to write a check for those events.

**Comment by Dockter** [comment]
Good Analytics doesn't appear to be tracking ore at the moment from what I could see in the reports.

**Comment by windy1** [comment]
Is this not the same as https://github.com/SpongePowered/Ore/issues/121?

**Comment by ewized** [comment]
@windy1 This one wants the logos in the header, the other one talks about it being in the sidebar.
