### ISSUE TITLE
Revise display of selected categories/channels

### ISSUE THREAD

**Issue by Zidane** [SpongePowered/Ore#12]
After looking at the categories/channels selections, I feel that the better solution would have them be colored when selected (colored label) and uncolored when not. Much better than clicking a little eye :).

**Comment by Flibio** [comment]
I agree. I'll work on changing this.

**Comment by Flibio** [comment]
Making the entire row change colors may be a little much. Maybe making the entire row clickable, instead of just the eye?

**Comment by windy1** [comment]
I think the eye should be moved entirely and have the text "glow" when enabled. You might want to center the category icons as well within their cells while you're at it as well because they are currently misaligned.

**Comment by Flibio** [comment]
Ok, I'll go with that.

**Comment by Flibio** [comment]
@windy1 If they are all selected should they still glow?

**Comment by windy1** [comment]
@Flibio No, and there is something in the implementation you can use to prevent this. If all the categories are specified in the URL it should be treated as if there are none in the URL.

https://github.com/SpongePowered/Ore/blob/master/app/controllers/Application.scala#L34-L36
