### ISSUE TITLE
Sponsor Tag next to PluginName

### ISSUE THREAD

**Issue by Dockter** [SpongePowered/Ore#120]
@windy1, it would be ideal if our sponsors who post plugin's can have a tag next to the project name stating that are a "SpongePowered Project Sponsor" or something along those lines.

Image: http://www.almuramc.com/images/Ore/SponsorTag.png

**Comment by humaidq** [comment]
Maybe a star or a colourful icon will be better than big bulky text after the project name.

**Comment by phase** [comment]
Is this still something we want? Do we have sponsors who are wanting to upload plugins to Ore? I dislike the star idea, but a sponsor tag could work.
