### ISSUE TITLE
Featured Sponsor Section?

### ISSUE THREAD

**Issue by Dockter** [SpongePowered/Ore#121]
@windy1, it would be ideal if we could offer our sponsors this area for advertising their services:

http://www.almuramc.com/images/Ore/FeaturedSponsorSection.png

[Bottom Right Corner]

**Comment by humaidq** [comment]
Isn't it enough on the Sponge home page, spamming the different sites with sponsor images might not be a good idea.

**Comment by Dockter** [comment]
Not paying bills because our sponsors are leaving isn't a good plan either yet here we are.

**Comment by Dockter** [comment]
Windy, this spot is separate from the area I would ideally like to have the sponsorship rotation appear.  Click the images for clarification.

**Comment by windy1** [comment]
Is having two spots for sponsors really necessary? If so, fine, but I would really rather not tbh.

**Comment by Zidane** [comment]
@windy1 

Its all about visibility and if we desire to use the Foundation to get us out there at events for the community, we need to orient ourselves to deliver on that visibility.

**Comment by windy1** [comment]
Added but not enabled, the featured sponsor can be enabled by adding:

```
sponge.sponsors.featured.logo = "logo.png"
sponge.sponsors.featured.url = "http://example.com"
```

to the config.
