### ISSUE TITLE
Click-thru link to forum help from Ore

### ISSUE THREAD

**Issue by Dockter** [SpongePowered/Ore#122]
@windy1, recommend adding a help button as seen in the image below with the functionality to provide a direct link to the forums where a sticky forum thread can be used to give users a one-stop shop to find help with their server, plugins etc.  (1st step in troubleshooting issues).

http://www.almuramc.com/images/Ore/Help.png

**Comment by humaidq** [comment]
I think there should be a link to Ore's page in Sponge's docs which will contain all the information on setting up and maintaining a repository.

**Comment by Dockter** [comment]
That wouldn't be the function of this link.

**Comment by windy1** [comment]
I think this might be better placed in the footer instead.

**Comment by Zidane** [comment]
@windy1 

No one would ever see this then. Needs to be at the top.

**Comment by Dockter** [comment]
The idea behind this would be to reduce the repeated "I need help" calls on IRC or repeat forum threads.

**Comment by windy1** [comment]
Did we have a destination for this link in mind?

**Comment by windy1** [comment]
Related https://github.com/SpongePowered/SpongeDocs/issues/523

**Comment by windy1** [comment]
Going to close this as the link is there, it's just the documentation is incomplete. Refer to SpongePowered/SpongeDocs#523 for further updates.
