### ISSUE TITLE
Donor / Sponsorship tag next to authors name

### ISSUE THREAD

**Issue by Dockter** [SpongePowered/Ore#123]
@windy1, just another thought:

http://www.almuramc.com/images/Ore/DonorTags.png

**Comment by humaidq** [comment]
When you click on the profile itself it will show you if they are a donor or have a rank on the forum, it might be a good idea to implement this.

**Comment by Dockter** [comment]
I would like it to stand out.  Those who are financially supporting our project deserve this.  Similar to how Spout did their donor tags.
