### ISSUE TITLE
Duplicate file error on plugin upload

### ISSUE THREAD

**Issue by Milchshakee** [SpongePowered/Ore#124]
Browser & Version: `Firefox 46.0.1`

Operating System: `Windows 7`

Error message (if applicable): `version.create.error Found a duplicate file in project. Plugin files may only be uploaded once`

Steps to reproduce:
- Go to your plugin versions page and click "Upload new version"
- Select a file that has not been uploaded yet and differs from previous versions.
  The only file I uploaded is the [v1.0.2](https://github.com/Monospark/ActionControl/releases/tag/v1.0.2) of ActionControl and I'm trying to upload [v1.0.3](https://github.com/Monospark/ActionControl/releases/tag/v1.0.3).  
- Press "Upload"

**Comment by simon816** [comment]
In your mcmod.info file from `actioncontrol-1.0.3.jar` it still states version `1.0.2`

``` json
[
    {
        "modid": "org.monospark.actioncontrol",
        "name": "ActionControl",
        "version": "1.0.2",
        "description": "Control crafting, mining, combat and more!"
    }
]

```

**Comment by stephan-gh** [comment]
Your version in the `@Plugin` annotation isn't up-to-date, see https://github.com/Monospark/ActionControl/blob/v1.0.3/src/main/java/org/monospark/actioncontrol/ActionControl.java#L30

To prevent that and keep your plugin version up-to-date with Gradle, I'd highly recommend using [SpongeGradle](https://docs.spongepowered.org/master/en/plugin/project/gradle.html#using-spongegradle) for your project, which will automatically set the plugin version for your project (make sure to remove it from the annotation, it will set it automatically in your `mcmod.info` file).

**Comment by Milchshakee** [comment]
Thanks for the help, I'm going to try SpongeGradle now.
