### ISSUE TITLE
Allow uploading project icon

### ISSUE THREAD

**Issue by Aaron1011** [SpongePowered/Ore#125]
Currently, all projects display their owner's Gravitar when shown in the project list. It would be nice if owners could upload a custom image to be displayed instead.

**Comment by ryantheleach** [comment]
It would be cool to include this in a similar way that the mcmod info is already read, I've seen logo's in the mod info section on the client before.

**Comment by windy1** [comment]
Implemented with `project-icons` merge in the settings page. Will be added to the project creation page as well.
