### ISSUE TITLE
Cannot delete version

### ISSUE THREAD

**Issue by trentech** [SpongePowered/Ore#129]
Browser & Version: Google Chrome 50.0.2661.102 (64-bit)

Operating System: Mac OS X 10.11

Error message (if applicable): Unexpected exception[NoSuchFileException: /ore-1.0/uploads/plugins/TrenTech/Project Portals/Project Portals-0.11.0.zip]

Steps to reproduce:
- Click Versions Tab
- Click Details on any version
- Click Delete to delete file

**Comment by windy1** [comment]
This will be resolved once the uploads branch is merged.
