### ISSUE TITLE
Have Ore adhere to responsive UI

### ISSUE THREAD

**Issue by Zidane** [SpongePowered/Ore#13]
Noticing this across the product but how Ore displays its products and pages could benefit greatly by making use of the space available to the browser. Any way to do this without breaking mobile support?

**Comment by windy1** [comment]
lol at "mobile support". Have you looked at Ore on mobile recently?

**Comment by Zidane** [comment]
@windy1 

Haha nope :).

**Comment by kashike** [comment]
It's quite... interesting... to say the least.

**Comment by Zidane** [comment]
/me opens on mobile

Woooo boy...I see. Well it at least opens to a page that is somewhat coherent...better mobile support I've seen than other webpages heh :).
