### ISSUE TITLE
Ore doesn't seem to be updating

### ISSUE THREAD

**Issue by JBYoshi** [SpongePowered/Ore#133]
The latest changes to the Ore repository on GitHub don't seem to have made it to the live server. Based on some testing and experimenting, it seems to be on commit f091c0aeb5535ec48cbac6b8a86818654dc38f1f.

**Comment by JBYoshi** [comment]
It's fixed now. I'm able to use the features I need.

**Comment by JBYoshi** [comment]
Looks like it's happening again. @lukegb 

https://ore-staging.spongepowered.org/statusz

``` json
{"BUILD_NUMBER":"412","GIT_BRANCH":"origin/master","GIT_COMMIT":"c0103a713a1343d09c3bd6c137711bc5fe80bc1f","JOB_NAME":"Ore-Docker","BUILD_TAG":"jenkins-Ore-Docker-412","SPONGE_ENV":"staging","SERVICE":"Ore"}
```

**Comment by progwml6** [comment]
@JBYoshi I just ran an update manually

**Comment by JBYoshi** [comment]
It's got the updates now. Is there any way to set it up to automatically update?

**Comment by progwml6** [comment]
there is an intermittent bug with ore's auto updating that we are investigating

**Comment by JBYoshi** [comment]
Cool. Thanks!
