### ISSUE TITLE
Ore is not accepting new files

### ISSUE THREAD

**Issue by pie-flavor** [SpongePowered/Ore#134]
^ What the title said. [This](http://prntscr.com/bo4cqf) happens.

**Comment by windy1** [comment]
So I'm unable to reproduce this locally, any idea as to what might be causing this @lukegb? (Unless ore-staging is still not updating in which case this would make sense)

**Comment by JBYoshi** [comment]
@windy1 It has updated ~~(at least to 1a98258416ab7491e9ad601c0a72a6a6d75f6fb0; I can't get an error page to check if 672eec191673583909fa1bba956a21bae6d32587 made it, but I don't think that should affect anything)~~.

**EDIT:** Just realized that I can utilize this bug to get an error page :stuck_out_tongue_winking_eye:. It is updated to 672eec191673583909fa1bba956a21bae6d32587. The error is still present.

**Comment by pie-flavor** [comment]
what's the status?

**Comment by JBYoshi** [comment]
@windy1 @lukegb Status?

**Comment by windy1** [comment]
I am unable to reproduce this, please re-open if problem persists.

**Comment by JBYoshi** [comment]
Still occurs on the live server for me.

**Comment by pie-flavor** [comment]
@windy1 Still happens, just tried. http://prntscr.com/c5q9ah

**Comment by JBYoshi** [comment]
Probably needs someone watching the live server while reproducing the problem; I think it might be directory permissions or something similar. I assume there's only one machine being used as a server?

**Comment by KaiKikuchi** [comment]
I confirm it happens to me:

> Unexpected exception[NoSuchFileException: /ore-1.0/uploads/tmp/KaiNoMood/SimplePermissions-0.9.9.jar]

This was supposed to be my first upload. I've also tried again the jar file, same result.

So I made a ZIP file with the jar and the license file, and I named it "simplepermissions.zip", and it worked fine.

**Comment by JBYoshi** [comment]
Update: This only happens when there are periods in the file name (other than the file extension). Pickaxe-1.0.1.zip doesn't work, Pickaxe-1-0-1.zip does.

**Comment by ryantheleach** [comment]
To add, "TranslateWithBing-1.2.0-all.jar" worked, "EasySpawn-1.0.0.jar" did not, but "EasySpawn-1.0.0-OreTesting.jar"  does

Ore is experiencing difficulties.
Unexpected exception[NoSuchFileException: /ore-1.0/uploads/tmp/ryantheleach/EasySpawn-1.0.0.jar]
If you suspect this is a bug, please take a minute to report it to the issue tracker.

**Comment by ryantheleach** [comment]
https://github.com/SpongePowered/Ore/blob/f091c0aeb5535ec48cbac6b8a86818654dc38f1f/app/ore/project/util/ProjectFactory.scala#L65

Is immediately deleting the uploaded file, thinking it's an old file, in the pathological case that the uploaded file matches ore's internal format exactly. right?

**Comment by JBYoshi** [comment]
@ryantheleach Looks like it. @windy1 ^
