### ISSUE TITLE
Allow plugin jars whose mcmod.info file has more than one entry.

### ISSUE THREAD

**Issue by gravityfox** [SpongePowered/Ore#135]
[FoxCore](https://github.com/FoxDenStudio/FoxCore) has both the sponge plugin as well as a companion client mod bundled in. This means that the mcmod.info file has two entries, one for each.

Ore screams at me if I try to upload this file, saying that the plugin file is invalid.

This is annoying, because the whole thing is one entire package, and it's not something I want to separate.

Something should be done about combo jars that isn't just failing.

**Comment by lukegb** [comment]
@gravityfox Can you please attach the mcmod.info in question to this bug for reference?

**Comment by JBYoshi** [comment]
@lukegb From v0.9.2: https://gist.github.com/JBYoshi/2e4f62e426b5c645edce1df543d13435

**Comment by windy1** [comment]
Resolved in https://github.com/SpongePowered/Ore/commit/3d279789a56cef2e71404bd7e659145d4cda1fac, Ore will now just use the first entry found.
