### ISSUE TITLE
Error when downloading JAR

### ISSUE THREAD

**Issue by JBYoshi** [SpongePowered/Ore#136]
Browser & Version: Firefox 47.0

Operating System: Windows 8.1

Error message (if applicable): `Unexpected exception[StringIndexOutOfBoundsException: String index out of range: -1]`

Steps to reproduce:
- Try to download a JAR directly (example: https://ore-staging.spongepowered.org/windy/Ore-Test-Plugin/versions/recommended/jar)

**Comment by JBYoshi** [comment]
This only happens with the plugins noted in https://github.com/SpongePowered/Ore/issues/137#issuecomment-234082051. I'll assume the issues are related, and that if #137 is fixed, this should be fixed as well.

**Comment by windy1** [comment]
I am not experiencing this, please reopen if it's still occurring.

**Comment by JBYoshi** [comment]
Still happens. https://ore-staging.spongepowered.org/pie_flavor/Splish/versions/recommended/jar

Something tells me it would be [this line](https://github.com/SpongePowered/Ore/blob/dc3570ac84227c7a7c6af06139b862c9bd663765/app/controllers/project/Versions.scala#L412), but I cannot confirm. It seems it's because of some incompatibility during an Ore upgrade, probably between 7d0ecf3f4daed5da041a88c833d2865beec55dfc...935334811ace5311da2bd1b4567eec6c0801d5b1.

**Comment by windy1** [comment]
You are probably correct, however it seems I can no longer enter the Docker container ( @lukegb / @progwml6 ) so until I can do that I cannot diagnose the issue.

**Comment by JBYoshi** [comment]
I'll try using `git checkout` and a clean environment (I recently switched operating systems and never transferred the Postgres data :stuck_out_tongue_closed_eyes:) to try to reproduce this locally.

**Comment by windy1** [comment]
I have found the problem. The issue was that there must have been a brief period where versions file names where not being inserted into the DB properly. This shouldn't happen for new projects and I will write a script soon that corrects this for older projects.
