### ISSUE TITLE
Blank response when downloading ZIP

### ISSUE THREAD

**Issue by JBYoshi** [SpongePowered/Ore#137]
Browser & Version: Firefox 47.0

Operating System: Windows 8.1

Steps to reproduce:
- Try to download a plugin as a ZIP (click the download button).

Result: Nothing happens.

I tried using curl to download it, and it gave this output:

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0    50    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (18) transfer closed with 50 bytes remaining to read
```

**Comment by windy1** [comment]
Likely related to both #136 and #134. Cannot reproduce locally.

**Comment by JBYoshi** [comment]
Seems to be intermittent; it doesn't happen on all plugins. Posting my results here as I get them.

Ore Test Plugin: Error
MCClans: Error
PvPToggle: Error
SpongeeCord: Error
Splish: Error
Tattle: Error
Pieconomy: Error
Tattle: Error
NoXray: Success
ActionControl: Success
EntityDisguise: Success
ChangeSkin: Success
Nucleus: Success

Based on my experiments, the one thing all of the working plugins had in common was that none of their recommended versions had been reviewed by moderators.

**Comment by windy1** [comment]
This is likely another file permissions issue.

http://stackoverflow.com/questions/22183859/javascript-err-content-length-mismatch

**Comment by windy1** [comment]
Haven't seen this pop up in a while. Let me know if you are still experiencing this.
