### ISSUE TITLE
File size limit discussion

### ISSUE THREAD

**Issue by mbax** [SpongePowered/Ore#139]
- What is the current limit?
- How many files of projects posted on the forums are [above that limit?](https://korobi.io/network/esper/channel/sponge/logs/2016/07/07/#L62-74)
  - Can these files have their size reduced (shade plugin's minimizeJar, for instance) to meet the current limit?
  - Is there a larger limit that can be set that would allow most or all currently too-big-to-post files to be uploaded?

I'd appreciate input from the community, especially members creating large jars for their work.

**Comment by Dockter** [comment]
CH (Creeper Host) hasn't really given us any direction on this from a storage sense.  We have around 4tb of redundant storage that will be utilized for this repo.  That being said it can be expanded rather easily.

**Comment by me4502** [comment]
It'd be interesting to get some stats from someone who had access to DBO. I'm not sure how much access each person had - but my best guess for that level of info would be @lukegb.

It'd be worth allowing the higher end of plugins, plus a bit of a buffer. Of course there are probably some outliers that are 100% larger than the higher end, but I doubt they should be considered unless there was a very good reason for those to be that size. If a plugin needed 500MB schematics or other non-executable resources, I don't see why they can't be downloaded as needed.

**Comment by windy1** [comment]
I recently bumped the size up to 20MB, pretty sure this should be enough for most plugins, but maybe not?

**Comment by windy1** [comment]
Going to close this now. Let me know if you think the limit should be raised / lowered.
