### ISSUE TITLE
Unable to delete file

### ISSUE THREAD

**Issue by windy1** [SpongePowered/Ore#140]
Every once and a while I am unable to delete a project or version for some reason. This never happens locally so maybe it's an issue with permissions? Idk...assigning @lukegb and @progwml6 as I don't really have the amenities to fix this issue.

Error: https://app.getsentry.com/sponge/ore/issues/138727401/

**Comment by lukegb** [comment]
This means that you have an open file handle to a file in that directory, so you can't delete it. Make sure you're not leaking file handles.

**Comment by windy1** [comment]
The file in this particular case was called `.nfs00000000000141f200000001` which I am almost certainly not performing operations on.

**Comment by ryantheleach** [comment]
http://serverfault.com/questions/201294/nfsxxxx-files-appearing-what-are-those

**Comment by lukegb** [comment]
You misunderstand - if you have an open file handle to a file which you delete, then you get a `.nfs<blah>` file (which is still the file, in its "deleted" state). This is possibly the JAR file which you'd just deleted as part of deleting the directory. You need to close the file handle to the other file before you can delete the containing directory.

**Comment by windy1** [comment]
Hasn't occurred in a long time. Going to consider this one closed for now.
