### ISSUE TITLE
Step 4 of project wizard results in error for EasySpawn

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/Ore#141]
Error message (if applicable): Ore is experiencing difficulties.
Unexpected exception[PSQLException: ERROR: duplicate key value violates unique constraint "versions_project_id_version_string_idx" Detail: Key (project_id, version_string)=(120, 1.0.0) already exists.]
If you suspect this is a bug, please take a minute to report it to the issue tracker.

Steps to reproduce:
1. Upload EasySpawn.
2. errored during upload due to https://github.com/SpongePowered/Ore/issues/134 
3. Rename file to EasySpawn-1.0.0-OreTesting.jar
4. redo wizard.
5. Stalls out with this error after clicking publish on Step 4.

I suspect it's due to the project being in a strange state since the wizard never initially finished correctly.

Edit: apparently the project successfully created anyway?

**Comment by windy1** [comment]
This was likely a consequence of #134 which has now been resolved.
