### ISSUE TITLE
Suggestion: Update notification

### ISSUE THREAD

**Issue by TuxCoding** [SpongePowered/Ore#142]
What do you think about an update notification if the author uploads a new version.  I think it could be pretty useful if there will be automatic forum post in the discussion section including the changelog (like in Spigot).

**Comment by windy1** [comment]
This was already implemented in https://github.com/SpongePowered/Ore/commit/dc3570ac84227c7a7c6af06139b862c9bd663765

**Comment by TuxCoding** [comment]
Sorry I never noticed that.
