### ISSUE TITLE
Ore doesn't allow using the 'download' button on your own plugins

### ISSUE THREAD

**Issue by pie-flavor** [SpongePowered/Ore#143]
Browser & Version: `Chrome 52.0.2743.116`

Operating System: `Windows 10`

Error message (if applicable): `ERR_CONTENT_LENGTH_MISMATCH`

Steps to reproduce:
- Click the download button on an Ore project you own.

[Screenshot](http://prntscr.com/cb9u3e)

**Comment by Aaron1011** [comment]
This only appears to be an issue with Piconomy - I'm able to reproduce it when I try to download it. The jar on the server is most likely corrupted.

**Comment by windy1** [comment]
Duplicate https://github.com/SpongePowered/Ore/issues/137
