### ISSUE TITLE
Member order wrong

### ISSUE THREAD

**Issue by parlough** [SpongePowered/Ore#144]
Browser & Version: Chrome 55.0.2857.0 Canary (64-bit)

Operating System: Windows 10 Version 1607 - Latest Updates

Steps to reproduce:
- Go to Ore
- Go to a project page
- Look at the member list

I don't exactly sure how member roles work, like if you can give them special names or not. If you cannot the default ordering is wrong, and I feel should go owner then down to developer. If there are custom names for roles, some way to specify priority or order would be a good addition.

As you can see in the below picture, the owner is listed below the developer, which I feel should be the other way around.

![memberorderwrong](https://cloud.githubusercontent.com/assets/18372958/18420029/b8dcee2e-782e-11e6-80f5-22ef4cb38334.PNG)

**Comment by parlough** [comment]
I'm not exactly sure how it works with many people in the same role, but it possibly could use alphabetical order(within the rank) if it does not already. 

If nothing else the owner of the project should be at the top.

**Comment by kashike** [comment]
It should more than likely be sorted by "rank" and alphabetically within that "rank".
