### ISSUE TITLE
Says "1 projects" instead of "1 project" on profile page

### ISSUE THREAD

**Issue by parlough** [SpongePowered/Ore#145]
Browser & Version: Chrome 55.0.2857.0 Canary (64-bit)

Operating System: Windows 10 Version 1607 - Latest Updates

Steps to reproduce:
- Go to ore
- Go to a profile page of someone with one project(For example Windy's)
- Look to the upper right of the profile

It's a very minor detail, but having one project is going to be rather common and it just sounds strange. Here's what it looks like on windy's profile.

![1projects](https://cloud.githubusercontent.com/assets/18372958/18423736/4da6c474-786d-11e6-824a-7ca952b846f5.PNG)

**Comment by windy1** [comment]
Don't worry about it being a minor detail, it's usually stuff like this that go overlooked by my eye! Keep 'em coming! :)
