### ISSUE TITLE
Official tags

### ISSUE THREAD

**Issue by KieronWiltshire** [SpongePowered/Ore#147]
I think official tags should be added to specific plugins such as [Ore Package Manager](https://ore-staging.spongepowered.org/windy/Ore). 

I think something that shows users that this plugin is an official plugin maintained by the Sponge team would be something of high significance. It would also be awesome if this could be placed in it's own category too.

**Comment by phase** [comment]
Is this still something we want? The [OrePlugin](https://github.com/SpongePowered/OrePlugin) hasn't been touched, and I don't know if it's something we still want to do, or if we should give it a special tag.

**Comment by mbax** [comment]
I'd say drop this to low priority for now.

**Comment by phase** [comment]
It would only be useful for _one_ plugin so I don't really know if a tag is needed.

**Comment by Katrix** [comment]
We'll use the sponge org instead
