### ISSUE TITLE
JSON parse error

### ISSUE THREAD

**Issue by pschichtel** [SpongePowered/Ore#149]
Browser & Version: `Firefox 49`

Operating System: `Archlinux`

Error message (if applicable): `Unexpected exception[JsResultException: JsResultException(errors:List((,List(ValidationError(List(error.expected.jsstring),WrappedArray())))))]`
At first there was an HTTP 504, then I refreshed and resend the form data which resulted in this error.

Steps to reproduce:
- Try to create an organization

**Comment by windy1** [comment]
Interesting, I'll look into this however note that your organization was created successfully.

https://ore-staging.spongepowered.org/CubeEngine

**Comment by windy1** [comment]
Should be fixed with `discourse-api` merge.

**Comment by windy1** [comment]
Haven't seen any more occurrences.
