### ISSUE TITLE
JsonParseException when uploading a plugin

### ISSUE THREAD

**Issue by RobertHerhold** [SpongePowered/Ore#150]
Browser & Version: `Chrome 50.0.2661.94`

Operating System: `Ubuntu 16.04`

Error message (if applicable): `Unexpected exception[JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null') at [Source: [B@292db6b1; line: 1, column: 2]]`

Steps to reproduce:
- Try to upload a plugin. If it matters, the plugin owner was an organization rather than myself

**Comment by windy1** [comment]
Should be fixed with `discourse-api` merge.

**Comment by windy1** [comment]
Haven't seen any more occurrences.
