### ISSUE TITLE
IllegalArgumentException: undefined topic id

### ISSUE THREAD

**Issue by lucko** [SpongePowered/Ore#152]
Browser & Version: `Chrome`
Operating System: `Mac`

Error message (if applicable):

```
Ore is experiencing difficulties.
Unexpected exception[IllegalArgumentException: undefined topic id []]
```

Steps to reproduce:
- I simply posted a new resource update.
- The update did seem to post successfully, however I still got the error message.

I also noticed that when I first made the project, a corresponding forum post was not made for it. There's no "Discuss" tab.

https://ore-staging.spongepowered.org/Luck/LuckPerms

**Comment by windy1** [comment]
Fixed by a discourse side change.
