### ISSUE TITLE
Feature suggestion - Api version for the plugin.

### ISSUE THREAD

**Issue by ProsperCraft** [SpongePowered/Ore#153]
Require the plugin author to select what api versions their plugin works on, then display that information on the plugin page.

Right now on the forum most authors put it in the topic, along with the plugin version.

**Comment by ryantheleach** [comment]
If you do, please allow support to override it if it's read from the jar file itself. There are a few plugins I've written that havn't broken on 5, from 3 & 4 Which I've tested, but would show up as outdated even though they work fine.

**Comment by windy1** [comment]
If you add a plugin dependency with the ID `spongeapi` it will show up in the dependency information on the version page.
