### ISSUE TITLE
Keep original filenames of uploaded files

### ISSUE THREAD

**Issue by stephan-gh** [SpongePowered/Ore#156]
For [ServerListPlus](https://ore-staging.spongepowered.org/Minecrell/ServerListPlus) I have multiple different JAR files for each version (depending on the platform, it supports 5 different platforms), and the filename contains the platform the specific JAR supports, e.g. `ServerListPlus-3.4.7-Sponge.jar` or `ServerListPlus-3.4.7-Bungee.jar`.

Ore seems to rename all uploaded files to `PluginName-Version.extension`. Because of that the uploaded file is renamed to `ServerListPlus-3.4.7.jar` which causes confusion if you have multiple archives of the same plugin (but for different platforms).

Ore shouldn't modify the original filenames, or at least make that optional. Sometimes files need to be named differently to prevent confusion.

**Comment by windy1** [comment]
This has been implemented in the `security` branch.

**Comment by kashike** [comment]
https://github.com/SpongePowered/Ore/commit/5b15a5db700bac6d436dbdac63c474e9f335b52c
