### ISSUE TITLE
Spoiler in discuss posts move other posts out of sight

### ISSUE THREAD

**Issue by malte-laukoetter** [SpongePowered/Ore#157]
Browser & Version: `Chrome 54`

Operating System: `Win 7`

When a Spoiler is opend in an answer in the discuss view the other answers are moved out of view and can't be scrolled back in:

![](http://i.imgur.com/AihR4xO.png)
![](http://i.imgur.com/DNYAC1N.png)

Steps to reproduce:

* open https://ore-staging.spongepowered.org/Lergin/Laborus/discuss
* open the spoiler in the first answer

**Comment by Ewoutvans** [comment]
Tested again and still seems to be the case.

**Comment by Katrix** [comment]
Moved to minor issues list
