### ISSUE TITLE
Make downloads wget able

### ISSUE THREAD

**Issue by NyleGarcia** [SpongePowered/Ore#158]
when you try to copy the link 

what happens
https://ore-staging.spongepowered.org/user/plugin/versions/version#/download

that needs to happen
https://ore-staging.spongepowered.org/user/plugin/versions/version#/download/plugin.jar

**Comment by windy1** [comment]
This is intentional. Downloads need to go through a redirect to track the download count. Use curl instead.

**Comment by stephan-gh** [comment]
There is no reason why you couldn't use `wget`. It will still download it correctly, just name it `download` instead of the name of the plugin JAR.

If you want `wget` to name the file correctly, use the `--content-disposition` command line argument:

``` bash
$ wget https://ore-staging.spongepowered.org/bebabo10/SendToSpawn/versions/recommended/download
Length: 4340 (4.2K) [application/octet-stream]
Saving to: ‘download’
$ wget --content-disposition https://ore-staging.spongepowered.org/bebabo10/SendToSpawn/versions/recommended/download
Length: 4340 (4.2K) [application/octet-stream]
Saving to: ‘SendToSpawn-1.0.jar’
```
