### ISSUE TITLE
Establish color template across Ore

### ISSUE THREAD

**Issue by Zidane** [SpongePowered/Ore#16]
Maybe it is just me but even if yellow is our brand coloring, I have issues with reading the words that are yellow...they bleed together and I tend to have to re-read some names to make sure I'm reading this right.

This would be fixed if Ore had a black theme (YES YES YES YES YES YES) and the yellow on the black would be so so sexy but if we want to keep the light theme then we should consider different shades of yellow.

@Tzk , maybe you could help too?

**Comment by windy1** [comment]
Ehhh I don't _love_ the idea of a dark theme :p but I do agree that the yellow is a bit much / hard to read. I've considered just changing anchors to standard blue but leaving the buttons as is.

**Comment by kashike** [comment]
:+1: for a dark/black theme, the brightness on the current white one hurts my eyes

**Comment by Zidane** [comment]
I'm with @kashike , I stare at computer monitors at least 8 hrs a day and it used to not affect me...I'm coming up on 28 and now I understand what people mean when they talk about it making them tired :/.

I try and use dark themes now whenever I can.

**Comment by windy1** [comment]
I use dark themes as well but I don't think they are very appealing to the layman tbh. Let someone create a browser extension for it or something, unfortunately I think dark themes have a way of turning the average user off.

**Comment by Zidane** [comment]
@windy1 

Maybe a config option in our profile? We'd consider it very low priority as there are many more things to be done first.

**Comment by Zidane** [comment]
WITH THAT SAID, we should still look into the coloring though either way.

**Comment by windy1** [comment]
Thoughts on the current coloring scheme? I rather like the change to blue links if I do say so myself ;)

**Comment by Zidane** [comment]
I really like the blue change. I thought the mix of yellow in there would look bad but I'm convinced.

**Comment by windy1** [comment]
Agreed, it doesn't look nearly as bad as I thought it would either. Gonna close this for now.
