### ISSUE TITLE
Unable to modify version release bulletin

### ISSUE THREAD

**Issue by pie-flavor** [SpongePowered/Ore#161]
I assume that the description of the release is supposed to represent the reply to the original post, the same way the main page is supposed to represent the original post; however, it doesn't update - it just sits there. For an example, check my recent project [Boop](https://ore-staging.spongepowered.org/pie_flavor/Boop/versions/1.0.1) version 1.0.1's release text compared with the [forum post](https://forums.spongepowered.org/t/boop-notifies-you-when-youre-mentioned-in-chat/15672/4?u=pie_flavor).

Close the issue if it works as intended.

**Comment by windy1** [comment]
I don't want to implement this in the same way as how the main topic is updated but rather a one-time post to notify people it has been released. It currently just uses the description from the `mcmod.info` file but my intention was always to allow you to edit this _before_ you publish the release.
