### ISSUE TITLE
Updating the forum thread has stopped

### ISSUE THREAD

**Issue by pie-flavor** [SpongePowered/Ore#164]
^ title. See [Badge](https://ore-staging.spongepowered.org/pie_flavor/Badge/pages/Home) and its forum post [here](https://forums.spongepowered.org/t/badge-puts-prefixes-on-peoples-heads/15691).

**Comment by windy1** [comment]
The forum post wasn't linked to the project properly. I deleted your topic and Ore created a new one successfully. Not sure why this happened but I'll keep my eye out for more occurrences.

**Comment by pie-flavor** [comment]
Same problem for Boop: [project](https://ore-staging.spongepowered.org/pie_flavor/Boop/pages/Home), [thread](https://forums.spongepowered.org/t/boop-notifies-you-when-youre-mentioned-in-chat/15672). Is it possible to relink without destroying the thread?

**Comment by pie-flavor** [comment]
NVM, my b. Was excessively delayed.
