### ISSUE TITLE
Sorting by project amount or username on the authors page only sorts within that page

### ISSUE THREAD

**Issue by parlough** [SpongePowered/Ore#165]
Oddly enough only people with 1 project show up when it opens for the first time as well. Not sure if that is related. 

**Browser & Version:**
 
Google Chrome Version 56.0.2917.0 canary (64-bit)
Microsoft Edge 38.14393.0.0

**Operating System:** Windows 10 Version 1607

**Error message (if applicable):** None

**Steps to reproduce:**

* Go to authors page
* Try sorting by project amount or username
* See it is not right if you check other pages

**Comment by windy1** [comment]
Yes I am aware of this issue. There are a couple problems with the authors page that I've been meaning to get to.
