### ISSUE TITLE
Authors page column alignment(width) changes

### ISSUE THREAD

**Issue by parlough** [SpongePowered/Ore#166]
**Browser & Version:**
 
Google Chrome Version 56.0.2917.0 canary (64-bit)
Google Chrome Version 60.0.3082.0 (Official Build) canary (64-bit)
Microsoft Edge 38.14393.0.0
Microsoft Edge 40.15063.0.0

**Operating System:** 

Windows 10 Version 1607
Windows 10 Version 1703 - 15063.138

**Error message (if applicable):** None

**Steps to reproduce:**

* Go to authors page
* Try sorting by multiple categories
* Notice the width of the columns change, the arrow changes it as it seems to add space for it to use, when instead it should just be added on top of the width already present. This causes changing categories to not be smooth or consistent.

**Comment by parlough** [comment]
I updated this with some re-wording and other version information.

I'm not really sure how to show this well, but with screenshots you should be able to see the width difference:

Joined selected:

![image](https://cloud.githubusercontent.com/assets/18372958/25518025/975028f6-2bb7-11e7-9546-094d05dc6ae9.png)

Username selected: 

![image](https://cloud.githubusercontent.com/assets/18372958/25518035/a8667d98-2bb7-11e7-8804-3891cbce4257.png)

Projects selected: 

![image](https://cloud.githubusercontent.com/assets/18372958/25518045/bb38863c-2bb7-11e7-959e-b520347c7989.png)

Extra 
---

Taking these I've also noticed, for the username category, the section actually does not include the picture, so selecting it highlights only the username section, leaving a small piece where the photo is not highlighted. 

"Username" is also above the usernames not the photos, which I think may be better aligned completely to the left. Then the username category could be made slightly smaller as well then as it will never get to the space given.

**Comment by Katrix** [comment]
Moved to minor issues list
