### ISSUE TITLE
Hovering over search and authors buttons causes a white background while there is no background for the new project or profile butons

### ISSUE THREAD

**Issue by parlough** [SpongePowered/Ore#167]
**Browser & Version:**
 
Google Chrome Version 56.0.2917.0 canary (64-bit)
Microsoft Edge 38.14393.0.0

**Operating System:** Windows 10 Version 1607

**Error message (if applicable):** None

**Steps to reproduce:**

* Go to ore and log in
* Hover over the four icons on the right
* Notice how they act differently

**Comment by parlough** [comment]
So this is still a problem for the new project button. The profile button has a white background, but it is rounded instead of square like the other two. I believe they all should follow a similar style.

**Comment by parlough** [comment]
Yeah I believe they all should be square with a white background when hovered to match the majority there as well as how it works on the forums.

**Comment by Ewoutvans** [comment]
This seems to be fixed
