### ISSUE TITLE
Ore logo looks blurry, especially "A Minecraft package repository" on Google Chrome

### ISSUE THREAD

**Issue by parlough** [SpongePowered/Ore#168]
This for me only occurs on Chrome, not Edge. Possibly they do some rendering differently or it's only my install, but it almost hurts to look at on the Chrome version. Opening it in a new tab makes it look just fine, but not on the page. Possible a switch to SVG would be good here as well? 

**Browser & Version:**
 
Google Chrome Version 56.0.2917.0 canary (64-bit)

**Operating System:** Windows 10 Version 1607

**Monitor:** Asus 1080p IPS Display

**Error message (if applicable):** None

**Steps to reproduce:**

* Visit Ore on Chrome
* Make sure you're on the homepage
* Look at the Ore logo and compare it

![logougly](https://cloud.githubusercontent.com/assets/18372958/20242618/b2e57980-a8fa-11e6-9a9c-ba820b050d42.PNG)

**Comment by windy1** [comment]
I am unable to reproduce this.

**Comment by parlough** [comment]
I am not able to reproduce this on other browsers or devices, yet it remains constant here even after clearing cache and trying incognito. Not exactly sure what it is causing this, but oh well.

**Comment by windy1** [comment]
Canary is an unstable build of Google Chrome so it's likely it's an issue with the particular build you happen to be on.

**Comment by parlough** [comment]
Yeah that's what I assumed, but on Canary on my phone and laptop it didn't occur. I'll just keep watching and see if it changes.
