### ISSUE TITLE
Only one project per user returned by projects api page and in author list

### ISSUE THREAD

**Issue by malte-laukoetter** [SpongePowered/Ore#169]
Browser & Version: `Chrome 54`

Operating System: `Win 7`

Steps to reproduce:

* Compare the project amount of Projects of ZpknTr on https://ore-staging.spongepowered.org/authors and the amount of projects on the Profile Page: https://ore-staging.spongepowered.org/ZpknTr

or

* Search for `TimeIsMoney` on the project api site https://ore-staging.spongepowered.org/api/projects  (only GallupPoll from ZpknTr is shown there)

**Comment by windy1** [comment]
Only 20 projects are returned by the API at a time. You can offset the "window" of projects with the `limit` and `offset` query parameters. Limit is maximum 20. I was able to find TimeIsMoney by setting the offset to 20.

https://ore-staging.spongepowered.org/api/projects?offset=20
