### ISSUE TITLE
Blockers for production release

### ISSUE THREAD

**Issue by windy1** [SpongePowered/Ore#170]
Follows is a list of blockers that must be completed before Ore can be released into a production environment.

@SpongePowered/developers

* [x] Fix / Complete [SpongeAuth](https://github.com/windy1/SpongeAuth) unit tests
* [x] Deploy SpongeAuth
* [x] Setup CI for SpongePlay
* [x] Setup CI for PlayDiscourse
* [x] Configure mail properties for SpongeAuth and Ore
* [x] [Finish documentation](https://github.com/SpongePowered/SpongeDocs/issues/523)
* [x] Write Terms of Service
* [x] Migrate Discourse accounts to SpongeAuth with [import script](https://github.com/windy1/SpongeAuth/blob/master/scripts/importDiscourseUsers.py)
* [ ] Clear forum topics in Ore category
* [ ] Discuss how we will review plugins and who will be responsible for this
* [x] Discuss how the transition from the "Plugin Releases" section to Ore will happen
* [ ] Voice any last minute concerns you may have about security or whatever
* [x] Provide a default avatar image for SpongeAuth
* [ ] Things I'm forgetting?

In order for this transition to happen smoothly we'll need help from each team within SpongePowered. Docs team, community team, developers and system maintainers, so please speak up if you have any questions / concerns about Ore. :)

**Comment by progwml6** [comment]
@windy1 we should probably move some of these new repos into the spongepowered organization so that others can fix as needed

**Comment by windy1** [comment]
@progwml6 Sure I'll talk to someone about transferring ownership.

**Comment by JBYoshi** [comment]
It looks like most of the repositories have been transferred, with the exception of [windy1/PlayDiscourse](https://github.com/windy1/PlayDiscourse).
- [SpongePowered/OrePlugin](https://github.com/SpongePowered/OrePlugin)
- [SpongePowered/SpongeAuth](https://github.com/SpongePowered/SpongeAuth)
- [SpongePowered/SpongePlay](https://github.com/SpongePowered/SpongePlay)

**Comment by windy1** [comment]
I didnt transfer PlayDiscourse because its not really specific to Ore or Sponge as a whole.

**Comment by Dockter** [comment]
windy1, As I'm not a web dev, is there anything that I can do to help?  Testing, etc etc?

**Comment by windy1** [comment]
@mcsnetworks Actually yes, thank you for asking. PM'd you on IRC.

**Comment by progwml6** [comment]
before ore/spongeauth go live some internal sysadmin documentation will be needed(as discussed on irc)

for those 2 CI setups we will need to get FTP deploy sections added to the SBT build scripts so that they can be uploaded to maven

**Comment by windy1** [comment]
@progwml6 I'm not sure this new setup really warrants that much documentation because it's pretty damn simple but basically I've just been pulling releases I've been putting on github, unpacking them and running the binaries. As far as environmental variables go everything you need to know is in `application.conf` + `SENTRY_DSN`.

Same goes for SpongeAuth

**Comment by ronaldburns** [comment]
"Discuss how the transition from the "Plugin Releases" section to Ore will happen"

Could you disable starting new topics in the section with a pinned message at the top, "Please post your plugin releases in the new Ore repository." or something along the lines of that.

**Comment by windy1** [comment]
@rojo8399 Yes, after some internal discussion, this is likely how we will handle it.

**Comment by ronaldburns** [comment]
So are we just waiting for the ToS and how plugins will be reviewed?

**Comment by JBYoshi** [comment]
Someone still needs to clear the old topics from the Ore category (new topics are starting to pop up, so please be careful!), and the terms are 404ing.

**Comment by windy1** [comment]
@JBYoshi Some of the docs links on Ore need fixing, I've added it to my TODO. As for the old Ore category posts, we're going to let them sit for a little bit and offer the option to link your old post to your new project. If you want your old post linked just send me a PM on IRC or the forums with a link to your new project and a link to your old forum topic.

**Comment by amaranth** [comment]
Any progress on this? Seems like you're ready to launch aside from some policy discussion and this would be huge to expand the Sponge community.

**Comment by windy1** [comment]
@amaranth https://ore.spongepowered.org is live as we speak, I've just been working on a few issues before we have our "official launch" (namely security and some bugs) but it should be ready relatively soon.
