### ISSUE TITLE
Top bar fails to extend across 1440p(probably just higher than 1080p) displays

### ISSUE THREAD

**Issue by parlough** [SpongePowered/Ore#174]
**Problem:** Unlike the home page, forums, and docs the top bar does not extend to fill my display(which is 2560x1440). The rest of Ore does successfully align in the center though.

**Browser & Version:** Version 57.0.2967.0 (Official Build) canary (64-bit)

**Operating System:** Latest Windows 10 v1607

**Error message:** None

**Steps to reproduce:**

* Have a 1440p monitor
* Go to [Ore](https://ore.spongepowered.org/)
* Notice the top bar does not extend across your screen

![image](https://cloud.githubusercontent.com/assets/18372958/21575668/e6cacbd8-ced9-11e6-8b1c-dd7ad84ff553.png)

**Comment by windy1** [comment]
Fixed in https://github.com/SpongePowered/Ore/commit/07d866068564d1ab2a4a9323a52f1b9f6fb2eb66
