### ISSUE TITLE
Profile picture for organization fails to display

### ISSUE THREAD

**Issue by parlough** [SpongePowered/Ore#177]
**Browser & Version:** Version 57.0.2967.0 (Official Build) canary (64-bit)

**Operating System:** Latest Windows 10 v1607

**Error message:** None

**Steps to reproduce:**

* Have an organization
* Try uploading a profile through either method
* See that picture fails to display

![image](https://cloud.githubusercontent.com/assets/18372958/21575975/0c7a9aa0-cee6-11e6-9419-25d2321e9f2d.png)

**Comment by parlough** [comment]
After a while it defaults back to the Spongie.

**Comment by windy1** [comment]
See #224
