### ISSUE TITLE
Display SpongeAPI version on main page for projects

### ISSUE THREAD

**Issue by Zidane** [SpongePowered/Ore#178]
@windy1 

I know you show the sponge label beside projects but it doesn't show the SpongeAPI version it targets. Would like to display the version it targets and optionally be able to filter down for that as well.

**Comment by windy1** [comment]
This is actually already displayed on hover.

**Comment by Zidane** [comment]
@windy1 

I wonder if it would be best to always show it. It would get annoying to have to hover over 20 or so plugins if I was looking for a certain API version.

**Comment by parlough** [comment]
I mean maybe a way to filter by version compatibility would be nice, but I think displaying the version always is just unnecessary clutter. People generally want to find plugins by their functionality not API version plus generally plugins have more than one version for the commonly used API versions, so they could just go check out the plugin's versions page. 

Now displaying the Sponge version on each entry on the [versions page](https://ore.spongepowered.org/IchorPowered/Latch/versions) may make sense as they view that after finding a plugin which matches the functionality they are looking for. 

I think the version displaying on hover is kind of fun too. A nice little surprise.

**Comment by windy1** [comment]
Going to close this for now, please reopen if you think the UI for the Sponge version still needs work.
