### ISSUE TITLE
Add button to go to admin settings area for SpongeAuth in User settings

### ISSUE THREAD

**Issue by Zidane** [SpongePowered/Ore#179]
May not be clear to users that this is where they go and change core attributes of their Sponge profile such as their avatar. We should work on making this a lot more clear to users. If you have something better fitting in mind @windy1 by all means.

**Comment by windy1** [comment]
There is a "settings" button on the user profile page on Ore however there should probably also be a button or something in the forums.

Note: Please be aware there is currently an issue with syncing spauth->forum avatars.

**Comment by Katrix** [comment]
No idea how long this has been in Ore, but it has been there for some time
