### ISSUE TITLE
Coordinate navbar sizing and widget positioning with Forums page

### ISSUE THREAD

**Issue by Zidane** [SpongePowered/Ore#18]
Now that we've got the widths where we want them we should get @Owexz here to coordinate making his navbar the same size as Ore's and position the Sponge logo and Avatar widgets to be at the same positioning.

This will really help sell to people that Ore is a part of our web services and not a separate component.

**Comment by windy1** [comment]
The navbar is now near identical to the forums. Height is exactly equal, avatar placement is the same, as well as the dropdown.
