### ISSUE TITLE
Forum post fails to update with Ore markdown change

### ISSUE THREAD

**Issue by parlough** [SpongePowered/Ore#181]
When I set the markdown on Ore for my organization's project Latch, the forum post is not updated and has stayed as the original. The title did update with a description change successfully though.

Visit the ore page here: https://ore.spongepowered.org/IchorPowered/Latch

The forum post here: https://forums.spongepowered.org/t/latch-a-locking-plugin-that-provides-various-types-of-locks-to-protect-your-containers-and-blocks/16508/1

**Comment by windy1** [comment]
Are you still experiencing this?

**Comment by zachoooo** [comment]
I'd like to add that this is still occurring for me. The page does not update when I save changes.

**Comment by parlough** [comment]
@windy1 This is still occurring for me: 

This is my forum page: https://forums.spongepowered.org/t/latch-a-locking-plugin-to-protect-your-containers/16508

Ore page: https://ore.spongepowered.org/IchorPowered/Latch

**Comment by simon816** [comment]
Someone with backend access to the log files will have to see whether something is going wrong with your project.
From what I can see there's no issues with the code to update the topic.
I suspect the `postId` is invalid in the database.
Ore updates forum posts in two stages: topic title, then the post content
It appears to be updating the title correctly, so it's most likely [the postId here](https://github.com/SpongePowered/Ore/blob/master/app/discourse/OreDiscourseApi.scala#L178) is invalid for some reason.
For reference, the post ID should be `97972`

**Comment by felixoi** [comment]
Are you still experiencing this issue?

**Comment by Katrix** [comment]
Closing due to no response
