### ISSUE TITLE
Info icons and numbers wrong position related to description

### ISSUE THREAD

**Issue by parlough** [SpongePowered/Ore#182]
**Problem:** Sort of hard to explain, but generally the plugin information and its icons(views, downloads, etc) appear in the upper right hand corner but with the large description they move to the lower right for no reason(as they would not intersect with description). If you make the browser skinnier this will occur more even though no collision would occur. If anything this should be in relation to the name not the description at all as they on different vertical levels.

**Browser & Version:** Version 57.0.2967.0 (Official Build) canary (64-bit)

**Operating System:** Latest Windows 10 v1607

**Error message:** None

**Steps to reproduce:**

* Go to Ore
* See the icons and info appear on bottom right if description is long
* Make the browser skinnier to see it happen to more plugins unneccessarily

Here it occurs on Latch as its description is rather long. There is no reason for it to move down as the icons and info will not hit the title for a long distance.
![image](https://cloud.githubusercontent.com/assets/18372958/21580054/bfbd6452-cf9b-11e6-90e0-1d6c632867cc.png)

Here you can see it happen with other plugins as I made the browser skinnier. 
![image](https://cloud.githubusercontent.com/assets/18372958/21580058/d6ed1460-cf9b-11e6-83cc-36c4255673aa.png)

**Comment by windy1** [comment]
Have this one fixed locally, will push a fix soon.
