### ISSUE TITLE
Allow downloading signature file along with plugin jar

### ISSUE THREAD

**Issue by Aaron1011** [SpongePowered/Ore#183]
Currently, Ore only allows users to download the uploaded plugin jar for a version. It would be useful to be able to download the signature file uploaded by the plugin author as well, so that users can do their own verification if they want to.

**Comment by gabizou** [comment]
Not to be too tedious, but I believe we should be able to host the md5 files as well (since those can be used for extra verification).

**Comment by windy1** [comment]
You can actually download the signature, there's just no button for it currently: https://ore.spongepowered.org/SpongePowered/Ore/versions/1.0.0/signature
