### ISSUE TITLE
Failiure to create organisation prevents it being created in the future.

### ISSUE THREAD

**Issue by dualspiral** [SpongePowered/Ore#184]
When trying to create an organisation on Ore, I get told that I've reached the limit of organisations for my IP address - fair enough, might not be enabled yet. However, if I try to create an organisation with the same name again, the "Create" button is disabled, becuase (I suspect) the organisation name is now registered as taken - though I have no access to it!

For reference, I tried creating Nucleus and NucleusPowered, so they are probably in your database somewhere!

Steps to reproduce:

* Try to create a respository when you've reached your limit for your IP address.
* It will fail, try to create it again.
* The create button will be disabled and will show the "No" cursor upon hover. Changing the org name enables the button again.

**Comment by Dockter** [comment]
This sounds like the same thing:  https://github.com/SpongePowered/Ore/issues/190

Better feedback is also needed when you cannot create an organization when it already exists.  Showing just a red "x" next to the org name field is insufficient.
