### ISSUE TITLE
Login button should redirect back to page button was clicked on

### ISSUE THREAD

**Issue by lukegb** [SpongePowered/Ore#186]
(Similarly, the you-accessed-a-restricted-page-but-you're-not-logged-in-so-let's-log-you-in flow shouldn't just take you to the home page)

**Comment by Katrix** [comment]
Isn't this more of a bug? Took a look and it seems like the only thing missing for this to work is a flash in `Users#login` as the return url isn't set. All the other pieces seem to already be present.
