### ISSUE TITLE
Make avatar be a rounded rectangle to match style

### ISSUE THREAD

**Issue by Zidane** [SpongePowered/Ore#19]
The avatar currently looks a bit off. We should have it match the rounded rectangle of the Spongie logo.

**Comment by windy1** [comment]
I kind of like the rounded avatar TBH plus it matches the forums.

**Comment by Zidane** [comment]
That is true, hmmm...

**Comment by windy1** [comment]
I'm going to close this one for now feel free to reopen it if you feel it needs further discussion.
