### ISSUE TITLE
OCD (or perhaps not so minor meh) issues

### ISSUE THREAD

**Issue by Deamon5550** [SpongePowered/Ore#195]
- [ ] Orgs should have the ability to have multiple owners
- [x] The edit preview doesn't appear http://puu.sh/tfaFG/7f6ec40f93.png
- [ ] The ability to Edit the title of a version so that it can be more descriptive (eg. `8.2.0 for Sponge 6.0.0` rather than just `8.2.0`)
- [ ] Alternatively ore should display the sponge or minecraft version targetted by the version in the versions page list.
- [x] Uploading a new version of a plugin is giving a 500 error
- [x] Pressing the back button when at a latter stage of creating a new project takes you all the way back to the beginning and forgets everything you entered, I would expect it to just return you to the previous section with the information you entered still there.
- [ ] you cannot search for orgs

**Comment by parlough** [comment]
- [x] Cannot add yourself as a developer of a project your organization owns.
- [ ] Being apart of an organization who has a project or being a developer of a project does not seem to add that project to your user page. For example [nighteyes604](https://ore.spongepowered.org/nighteyes604) is apart of IchorPowered and a developer on Latch but it does not show up on his profile and it says he has 0 projects.
- [ ] Hovering over the buttons in the upper right puts a white box around them except the new project button. It should be given a white background and the plus should change white.
- [ ] The white box around the search and authors button when you hover is square but when you hover the user icon it is rounded.
- [x] I am not sure about this, but I feel it may be better to have the default sorting option to be "Recently Updated"
- [x] In the options to sort by "Recently Updated" has both words upper cased but the rest just have the first word(such as "Most views"). I am not sure which is better, but I feel they should be the same.
- [ ] The terms button on the footer still leads nowhere.
- [ ] While editing members on an organization or project, the name, edit, and trash buttons are very close. Maybe the trash button should come after the edit button as well.
- [ ] It may be interesting to have a link to the current hosted commit somewhere so people can see why a revision is not out yet or just to follow development.
- [ ] I don't really think the plus and avatar buttons need an arrow next to them(look at forums for example). They are a little bit buggy and add clutter.
- [ ] Where it says "This project is under review...", I think it would be beneficial to link to a page which includes information about the review process, how it works, who curates it, et cetera.

**Comment by windy1** [comment]
@Deamon5550 Is `#5` reproducible? I have not been able to.

**Comment by lukegb** [comment]
https://sentry.io/sponge/ore/issues/202114256/ for Deamon's 500 issue, maybe?

**Comment by Zerthick** [comment]
- [ ] Emojis are not supported on the pages of a plugin, but are supported on version messages.
- [ ] By default syntax highlighting is enabled for code blocks, IMO it should be disabled in favor of using the syntax of Github Flavored Markdown ` ```Java ` for example.
- [ ] Inserting images via HTML is not supported, not sure if this is something that would be supported but I thought I'd mention it.

**Comment by Deamon5550** [comment]
@windy1 now when I click to upload the signed file it just loops me back to `/versions/new` and resets the entry. The first time it did take me to the next page and then 404'd on the `/versions/8.0.0` page it tries to redirect to.

Perhaps this is related to the fact that I'm trying to retroactively upload an older version.

**Comment by parlough** [comment]
What you mentioned there is the same issue I am having, except it was not an older version. I don't believe that should affect the upload process anyway as it has no way to recognize it as an older version.

**Comment by me4502** [comment]
I also experience the 500 issue on upload. When it redirects to `https://ore.spongepowered.org/new/upload`, it returns a 500.

**Comment by ryantheleach** [comment]
@felixoi @phase I'd like someone to go through these and separate them into milestones.

**Comment by ryantheleach** [comment]
https://github.com/SpongePowered/Ore/issues/368 1.6
https://github.com/SpongePowered/Ore/issues/369 1.7
https://github.com/SpongePowered/Ore/issues/370 2.0
https://github.com/SpongePowered/Ore/issues/371 Misc Style Fixes
