### ISSUE TITLE
Please make the jar files wget friendly

### ISSUE THREAD

**Issue by ProsperCraft** [SpongePowered/Ore#197]
Sorry to compare to the Bukkit repository but they did this totally right for server owners.  On their plugin download site you can right click and get the exact url to the jar file.

Here is my workflow when it comes to updating plugins- I check the versions on the page, and if newer I copy the url and go to my console and remove the current plugin and type wget and paste the url.

With Ore you can't right click and get the url to the jar, and you can't even right click and get the download link.  This means I have to download it to my computer, then use scp to upload it to the server. Adding an extra step.

Please make the downloads wget friendly.

**Comment by parlough** [comment]
I was able to get a link which is a direct download. Go into the version you want to download then right click the download button within that version then you can choose "copy link address" and to my knowledge that link should work. For example this downloads version 0.1.0 of Latch: https://ore.spongepowered.org/IchorPowered/Latch/versions/0.1.0/download

You could also use the [OrePlugin](https://github.com/SpongePowered/OrePlugin) to download, install, and update plugins along with other functions from within the server without even visiting Ore.

**Comment by windy1** [comment]
wget works fine on these links you can use `/windy/ExamplePlugin/versions/1.0.0/download` for the original download or `/windy/ExamplePlugin/versions/1.0.0/jar` for just the JAR file.
