### ISSUE TITLE
(Unreviewed) file download route should be a POST

### ISSUE THREAD

**Issue by lol768** [SpongePowered/Ore#198]
**Problem:**

* Currently users can be handed direct download links to files which look safe because they come from Ore
* Users are given a modal dialog box to dismiss if they try and do this on the site, but the modal isn't actually a `<form>` that POSTs somewhere. Hence there's no assurance the user is aware of the warning.

**Possible solutions:**

* Make *all* download routes POST routes (covering both approved and unapproved files)
  * Add a GET route which checks the `User-Agent` for users of tools like curl and wget, who are assumed to know what they are doing. Users GETing the URL with a browser should be redirected to a warming page with a form to allow POSTing to the download page after understanding the file is potentially unsafe.
* Make unsafe (i.e. unreviewed) downloads require a POST, and allow direct links to safe files

**Things to consider:**

* The downloads should be on a separate domain for security reasons.
* When users hit the POST route (or the GET route with `wget`/`curl`), they should get a redirect to a one-time download URL on said user content domain.
* This is because the CSRF cookie needs to be inaccessible from the separate user content domain.

**Comment by Aaron1011** [comment]
I'm not really sure that I see the benefit in requiring the `POST` requests for downloading files. The underlying issue here is ensuring that users:

* Must confirm a download before it takes place
* Are aware that plugin downloads are potentially unsafe

The HTTP method used is really an implementation detail. Requiring `POST` would just makes thing more complicated, as checking the user agent for the `GET` request potentially makes it more difficult for plugins to be downloaded programatically (we can't be sure of the user agent set by the script used).

Both of these issues could be addressed by only making changes to the user interface. We could require an explicit confirmation on the modal dialog, or even require following a link to the 'real' downloads page.

**Comment by ryantheleach** [comment]
The idea would be to make it literally unable to provide insecure downloads to naive people, without seeing the warning.

**Comment by Aaron1011** [comment]
@ryantheleach: There's no need to change the HTTP request method used in order to accomplish that.

**Comment by windy1** [comment]
Hmm I think I'm with @Aaron1011 on this one. I think there are alternative methods we can employ to make unreviewed file downloads safer. One idea that comes to mind is having the normal download link be a 2 step process if the file is unreviewed. First GET the client would be issued a token that they would include in the second request. 

This way not only we can make it more difficult to download unreviewed files but also it would allow us to catalog every unsafe download for piece of mind.

**Comment by lol768** [comment]
To clarify, I figured `POST` would be easier since it'll force the CSRF filter to check the request.

You could easily reimplement it with a `GET` and query parameter, but the `POST` seemed the easiest way with the existing code.

-----
I guess the GET has the additional advantage that it'll work reasonably nicely without a User-Agent check (since it would include the token which would perhaps be tied to an IP? We'd need some way to stop users just giving out links with a token in already because then we'd be back to square one) - but this would make the URL you'd need to use with curl/wget a bit uglier.

**Comment by lol768** [comment]
Just to be clear on the actual problem:

If there is *any* way for a user to get a link to a file that works on its own from another machine/browser they can use it to give a victim a "safe" (read: unsafe) link to an unreviewed file that contains malicious code.

Curse's Trinium (legacy CurseForge platform) had this issue to a larger extent where file links were just hidden and it was a problem for the DBO staff - though it's still partially an issue with Elerium (new CurseForge platform) too (if you grab the http://addons.curse.cursecdn.com/files/x/y/z.jar type link directly).

**Comment by windy1** [comment]
@lol768 Right, my only objection to POST was that it's kind of anti-spec as far as HTTP goes. You're "GET"-ing the file so the route should still be a get. I will add csrf-like functionality to downloads for unreviewed files for sure. Unreviewed files will need to send two requests for confirmation and I will make sure it's pleasant for non-browser User-Agents, seeing as OrePlugin needs that to work anyways.

**Comment by lol768** [comment]
> Right, my only objection to POST was that it's kind of anti-spec as far as HTTP goes

Yeah I think that's a legitimate objection. I suppose you could treat it as the user "agreeing to download and submitting an assertion to that", but it doesn't really matter anyway.

Will be interesting to see how it's implemented :)

**Comment by mbax** [comment]
You're not GETing the file, you're POSTing your acceptance of risk. :3

**Comment by windy1** [comment]
Closed in https://github.com/SpongePowered/Ore/commit/91087487a32a884097f4dadec16f7f2781842de2
