### ISSUE TITLE
Make consistent the widths between projects/categories on Home

### ISSUE THREAD

**Issue by Zidane** [SpongePowered/Ore#20]
http://imgur.com/8ZNj5B4

Couple of things to note:
- The thickness of the bar under "Categories" (cut off at the top right) doesn't match the left
- Once the above is fixed, the lines should line up between the left grid view and the right grid view

**Comment by Flibio** [comment]
I'm planning on redesigning the projects list, so I'll make sure to do this.

**Comment by windy1** [comment]
No longer relevant.
