### ISSUE TITLE
Cannot upload new versions as organization

### ISSUE THREAD

**Issue by dualspiral** [SpongePowered/Ore#201]
Browser & Version: Tested both Firefox 50.1 and Chrome 55.0.
Operating System: Windows
Error message (if applicable): None appears

Steps to reproduce:

I suspect this might be limited to organisational accounts - I tried to do this with Nucleus in the Nucleus organisation:

* Go to the plugin version page, click on New Version.
* Select the plugin file, sign it.
* Click on upload.
* When the upload completes, it looks like the page just refreshes, with no plugin selected, and no error message.

For reference, 0.18.0-5.0 is uploaded, I was trying to upload 0.19.0-5.0, if that is relavent.

Plugin in question: https://ore.spongepowered.org/Nucleus/Nucleus

Note that I tried uploading a new plugin on the same organisation (Nucleus Mixins), which suceeded.

**Comment by bloodmc** [comment]
@windy1 @lukegb  Can you look into this please. Thanks!
