### ISSUE TITLE
Minor UI issues with project comments

### ISSUE THREAD

**Issue by Eviltechie** [SpongePowered/Ore#204]
- [ ] There does not appear to be any clientside verification when submitting a comment. For example: I can try to submit an empty comment. It will fire off a few requests before it kicks it back to me with the message "Content too short.".

- [ ] The icon choice and placement for "submit" is dubious. Usually submit buttons are located on the bottom right, this one is on the left side. Additionally, the icon is the same as the "undo" icon from any modern word processor. It confused me the first time I clicked on it.

- [ ] No labels/tooltips. Edit is labeled, but preview and submit have nothing.

**Comment by ryantheleach** [comment]
@felixoi This needs to be re-reviewed to work out why it's still open. I've edited the main ticket to have a checklist. (It won't help you until such a time you get pro, but tell me what's fixed and I'll check the boxes)

**Comment by phit** [comment]
I have another one, comments currently have no pagination leading to long loading times and super long pages. Example: https://ore.spongepowered.org/Nucleus/Nucleus/discuss

**Comment by phase** [comment]
Ugh, I wish pagination was a more common practice when things were getting started.

**Comment by Katrix** [comment]
Moved to minor issues list
