### ISSUE TITLE
Creating an organization

### ISSUE THREAD

**Issue by pie-flavor** [SpongePowered/Ore#209]
If I create an organization, it offers the error ["Username must be unique Email has already been taken"](http://prntscr.com/dzj9wm). If I try again to create the same organization, it offers the error ["error.spongeauth.parse"](http://prntscr.com/dzja55).

**Comment by windy1** [comment]
Thank you for the report, but in the future, please do not create organizations merely for the sake of creating them.

**Comment by pie-flavor** [comment]
I was just trying to get more information about the bug. You can delete all the organizations I've created thus far.

**Comment by turtledude01** [comment]
I had this issue aswell, there's probably a couple of organizations created by me that can be deleted until its fixed.

**Comment by Mohron** [comment]
Is this going to get a fix anytime soon for those of us actually working on a team that makes multiple plugins?

**Comment by windy1** [comment]
I will try but it can be difficult for those of us actually working on this project almost entirely independently...

**Comment by Mohron** [comment]
No rush, just asking since it seems you thought the only people using this feature shouldn't be using it anyway.

**Comment by Zidane** [comment]
@Mohron 

He was talking about @pie-flavor just creating Organizations just cause (which chews up those names from being used by others without @windy1 having to delete them manually...)

**Comment by Mohron** [comment]
I realize this. Just wanted to make it known that somebody actually wants to use this for their org.

**Comment by windy1** [comment]
Okay this should be fixed now. @pie-flavor @turtledude01 @Mohron let me know if you need previously created organization names to be freed up.

**Comment by pie-flavor** [comment]
@windy1 Yeah, clear away all variously punctuated forms of RadicalDelta, and everything I made.

**Comment by Mohron** [comment]
Same for devOnTheRocks/onTheRocks

**Comment by windy1** [comment]
@pie-flavor Deleted RadicalDelta and Radical_Delta, but there I cannot tell who created what in this bugged state so I couldn't get your other ones.

@Mohron Deleted DevOnTheRocks and OnTheRocks

**Comment by rexbut** [comment]
I always have the "error.spongeauth.parse" error when I try to create an organization

**Comment by windy1** [comment]
@rexbut what is the name of the organization you are trying to create

**Comment by rexbut** [comment]
I try to create the organization "EverCraft"

**Comment by windy1** [comment]
@rexbut try now

**Comment by rexbut** [comment]
Yes it's good, thanks

**Comment by ItsDoot** [comment]
Having this issue trying to create the organization "Frontier."

**Comment by windy1** [comment]
@xDotDash try now

**Comment by ItsDoot** [comment]
Works now, thanks.
