### ISSUE TITLE
Aha! Finally saw the 502 Page (It needs to be updated)

### ISSUE THREAD

**Issue by Zidane** [SpongePowered/Ore#21]
http://imgur.com/2O7vUmK

When your commit you just made @windy1 caused the staging to refresh, I was met with the above page...we should get this updated.

@lukegb ?

**Comment by windy1** [comment]
Yeah I just don't have any error status pages made yet so I guess there are some old ones still up.

**Comment by lukegb** [comment]
Was this actually fixed or did you just close it for fun?

**Comment by windy1** [comment]
https://github.com/SpongePowered/Ore/commit/9c393b4672eb3bb1f5996757f7b84fee0dacfcdf
