### ISSUE TITLE
3 day cooldown before being able to upload

### ISSUE THREAD

**Issue by lucko** [SpongePowered/Ore#217]
Browser & Version: `Chrome`    
Operating System: `Windows 10`    
Error message (if applicable): `You must wait a minimum of 3 days after changing your public key to upload files.`    

Steps to reproduce:

* Went to upload a project to Ore
* Added my public key to my account as per the instructions [here](https://docs.spongepowered.org/master/en/ore/publish.html#signing-your-plugin)
* Got the error above when I uploaded my jar + signature file [img](http://i.imgur.com/LJ4jnZw.png)

To clarify, I've never "changed" my key. I just added my public key to the site for the first time. I've had an account for a few months.

I don't even have more than one public key. :P

**Comment by JBYoshi** [comment]
Well, technically, you changed it from nothing to something.

But I agree, it's unexpected.

**Comment by windy1** [comment]
I have not been getting this for the first upload on fresh users locally. Interested to hear if anyone else has experienced this?

**Comment by malte-laukoetter** [comment]
I was able to directly upload my plugin after uploading the key for the first time (without a cooldown of 3 days, this was at the end of 2016).

**Comment by windy1** [comment]
Going to close this for now, please re-open if still experiencing.
