### ISSUE TITLE
Cannot Delete Previous Versions

### ISSUE THREAD

**Issue by Mohron** [SpongePowered/Ore#223]
https://ore.spongepowered.org/Mohron/SkyClaims/versions/1.0.0-beta10/delete
```Unexpected exception[NoSuchFileException: /home/ore/files/plugins/Mohron/SkyClaims/skyclaims-1.0.0-beta10.jar]```

I've tried to delete this file many times with no success. All other versions I have been able to delete.

**Comment by Mohron** [comment]
Now it seems I can't delete any of my outdated versions.

**Comment by Mohron** [comment]
This isn't live I presume? I just tried to remove my ghost versions with no luck.

**Comment by windy1** [comment]
Just deployed, try now.

**Comment by Mohron** [comment]
Works great! Thanks!
