### ISSUE TITLE
Organization improvements

### ISSUE THREAD

**Issue by windy1** [SpongePowered/Ore#224]
The current state of organizations definitely has room for improvements. This issue will serve as an ongoing list of planned / requested features to add to organizations. Going forward, please request new features for organizations here and I will add it to the list.
* [ ] Deleting / Disbanding
    * Not initially supported because of some complications on Discourse API's side. AFAIK it is not possible to delete account from the API (only deactivate) so if that cannot be resolved, some kind of notification system for mods will need to be added to mark accounts for deletion. This is a side-effect of the decision to make organizations have corresponding user accounts: a decision I stand by because it avoids username-organization name collision and leaves open the possibility to post on forum threads (from Ore) as Organizations some time in the future, which brings me to my next point...
* [x] Posting to forum thread as Organization
    * This one is easy enough, there would just be an additional "Post as" option within the discussion tab. Note that you *cannot* log into the forums as organizations (through normal channels at least) because the forum accounts created by Ore have long, random passwords that are not saved anywhere (very much intentional).
* [x] Renaming
    * Easy enough, more of an oversight on my part than anything
    * Moved to #350 (Katrix)
* [x] Discourse IP-throttling issues
    * I don't feel like I have the full picture on this one as I have only heard vague reports of this on IRC and haven't done much digging on my own. @lukegb can you please provide some insight on what exactly is happening here?
    * No idea what this was about but we use SpongeAuth now and haven't had a problem (Katrix)
* [x] More robust user-roles
    * Right now, organizational roles essentially [mirror project roles](https://github.com/SpongePowered/Ore/blob/master/app/ore/permission/role/RoleTypes.scala) but this should be expanded upon to allow more diverse leadership hierarchies such as the inclusion of an "admin" rank (#219).
* [x] Investigate avatar updates
    * This was working fine at one point, but I've heard spattered reports of it not behaving as expected.
* [ ] Paginate role list on organization overview page
    * Busywork

Please let me know if I'm missing anything critical or if you would like to see something not listed here added. Paging @SpongePowered/contributors  and @SpongePowered/developers for input.

**Comment by Katrix** [comment]
Moved to minor issues list
