### ISSUE TITLE
Non-reviewed channel

### ISSUE THREAD

**Issue by mbax** [SpongePowered/Ore#228]
A non-reviewed channel would allow for submission of snapshots that are deliberately not ready for their own proper version. The goal here is to allow for uploading files that may fix bugs or test out new features to a smaller userbase who want to help the plugin developer. Here's my proposal:

1. Allow marking of channels on project as non-reviewed. Needs clear info (hover infobox?) clarifying what this selection means.
  a. Consider only allowing marking one channel?
2. There must always be one regular channel. 
  a. Cannot delete last remaining regular channel leaving only non-reviewed channels.
  b. Cannot mark last remaining regular channel as non-reviewed.
3. Staff must be able to monitor for projects solely using non-reviewed channels.
  a. Consider active monitoring in which Ore will automatically flag a project that has received $x days worth of frequent non-reviewed submissions without any reviewed submissions. Staff must then check the project out to make sure it's not just directing users to skip releases.
  b. Consider passive monitoring in which information on project files across reviewed/non-reviewed channels is provided to staff for informational purposes but doesn't force it on staff.

**Comment by progwml6** [comment]
@mbax is this channel basically meant for jenkins builds to get uploaded automatically on build completion?

In that case i'd prefer to refer to it as no manual review. I'm assuming that in this case we might at some point run automated checks on files that should be ran on these as well

**Comment by mbax** [comment]
> is this channel basically meant for jenkins builds to get uploaded automatically on build completion?  

or Travis! Or, folks like me who would just upload things when wanting to specifically try something out without making too many people download it.

> In that case i'd prefer to refer to it as no manual review. 

I'm terrible at naming. :)

**Comment by windy1** [comment]
Closed in 1.4.0
