### ISSUE TITLE
Null Sponge API dependency version

### ISSUE THREAD

**Issue by Grinch** [SpongePowered/Ore#229]
Browser & Version: `Vivaldi 1.7.735.46`

Operating System: `Windows 10 x64 (build 15048)`

Error message (if applicable):

Steps to reproduce:

  * Honestly I'm not sure how it was triggered but this version of [TimeWarp](https://ore.spongepowered.org/Grinch/TimeWarp/versions/2.2.1-r6.0.0) says the Sponge API dependency version is null.

**Comment by malte-laukoetter** [comment]
If i would need to guess to problem is mostelikley that the dependencies field of sponge in the mcmod.info file hasn't a version next to it and sponge ore so doesn't know which version it should be:
```
"dependencies": [
    "spongeapi"
]
```

instead of 

```
"dependencies": [
    "spongeapi@6.0.0-SNAPSHOT"
]
```

**Comment by Grinch** [comment]
Hm strange. That would likely be the case. I'll go ahead and close this and try to figure out why my build decide to not populate the version.

**Comment by stephan-gh** [comment]
Fixed in https://github.com/SpongePowered/SpongeAPI/commit/015eb9e5adca98f3cdc5a63066e4d0f377327138
