### ISSUE TITLE
Description display overflow

### ISSUE THREAD

**Issue by lexware** [SpongePowered/Ore#24]
https://www.dropbox.com/s/uzsezoac4ntb6lv/Screenshot%202015-02-04%2019.02.15.png?dl=0 The text seems to run out of the box :|

**Comment by jomo** [comment]
```CSS
word-wrap: break-word;
```
fill fix this.

**Comment by gratimax** [comment]
I'll keep this open for future reference, but styling is not the biggest problem currently :wink: :
