### ISSUE TITLE
Display more information on downloads page

### ISSUE THREAD

**Issue by Zidane** [SpongePowered/Ore#24]
http://imgur.com/vOwxC9H

Instead of displaying an "i" to click for more information, lets take advantage of the space we have and display relevant details in a grid view much like the main page

We should have:

Version - Date - Download Size - Channel - Download button

Discuss!

**Comment by Zidane** [comment]
To add further, you can click on the specific version to see a page that a developer put up for it. Could be release notes or anything.

**Comment by windy1** [comment]
What are your thoughts on the current method of displaying the channel for a version? (It's that little color coded dot to the left)

**Comment by kashike** [comment]
Is it planned to be able to sort the download page (as well as creating links that go directly to a sort (`?channel=release` would show releases at the top or something))?

**Comment by windy1** [comment]
`?channel=Release` is already implemented and shows only `Release` channel versions. You can also have multiple channels `?channel=Release,Beta,Alpha`. More elaborate sorting is definitely planned.

**Comment by kashike** [comment]
Is the channel case-sensitive?

**Comment by windy1** [comment]
@kashike Currently yes. I'll probably change this though.

**Comment by kashike** [comment]
Tooltip text when hovering over the "eye" in the channels section would be nice as well.
