### ISSUE TITLE
Expose md5 and sha signatures for downloadable files

### ISSUE THREAD

**Issue by kinggoesgaming** [SpongePowered/Ore#240]
This will be useful for confirming signatures for downloaded files.

I am working on a plugin manager and verifying the hashes would be useful.

**Comment by mbax** [comment]
How about, instead, providing the signature file?

**Comment by kinggoesgaming** [comment]
@mbax i assume you mean the pgp signature file? That could be provided aswell

**Comment by windy1** [comment]
Signature files are already available @ `/:author/:slug/versions/recommended/signature`

**Comment by kinggoesgaming** [comment]
@windy1 is sha1/256 and md5 still on the table?

otherwise i can close the issue.

**Comment by mbax** [comment]
But why? The signature verifies the file is correct **and** verifies who signed it.

**Comment by kinggoesgaming** [comment]
yea just wanted the confirmation before closing, in case windy wanted to provide this anyways

**Comment by windy1** [comment]
I will include the md5 in the API since it is already stored internally anyways.
