### ISSUE TITLE
Show short commit hash somewhere on page

### ISSUE THREAD

**Issue by parlough** [SpongePowered/Ore#244]
I think it would be pretty cool to show the shortened commit hash of the latest commit that the live website is running somewhere, which you could click to go to that commit on Github. 

This may have been a feature before, I don't really remember, but I feel like it would fit well as this is a development community and it could help to identify what the latest additions/changes were.

**Comment by simon816** [comment]
Looks like this is [already done in the code](https://github.com/SpongePowered/Ore/blob/master/app/views/bootstrap/footer.scala.html#L26).
The production environment just needs to have `GIT_COMMIT` set

**Comment by progwml6** [comment]
this type of information will be re-populated again at ore.spongepowered.org/statusz when we setup a build system for ore soon. i'm not putting it on every page at this time

**Comment by Katrix** [comment]
Moved to minor issues list
