### ISSUE TITLE
Terms of Service

### ISSUE THREAD

**Issue by windy1** [SpongePowered/Ore#25]
We need to write up a "terms of service" for Ore as sort of a disclaimer so we aren't held responsible if someone downloads a plugin that blows up their server. 

IANAL.

**Comment by Zidane** [comment]
@windy1 

I'll work with gabizou and define these terms.

**Comment by windy1** [comment]
@Zidane Any update on this one?

**Comment by humaidq** [comment]
Should the Terms of Service be on Sponge Docs which contains terms of service for all other projects and have it all in one place?

**Comment by windy1** [comment]
@Zidane poke

**Comment by gabizou** [comment]
@windy1 We're taking care of it ;)

**Comment by windy1** [comment]
@gabizou poke :trollface:
