### ISSUE TITLE
Plugin search ability

### ISSUE THREAD

**Issue by XakepSDK** [SpongePowered/Ore#253]
Add ability to search plugins by name/keyworkd.

**Comment by parlough** [comment]
This is already there :)

![image](https://cloud.githubusercontent.com/assets/18372958/25302341/deb29a72-2701-11e7-8f86-fda34ce3fa17.png)

Just click on that magnifying glass and a search box to type in should show up.

Say I search for "latch", this comes up:

![image](https://cloud.githubusercontent.com/assets/18372958/25302348/f59ecd6e-2701-11e7-9237-7c645b8864f9.png)

**Comment by XakepSDK** [comment]
Oh, thanks =)
I did not notice at once.
