### ISSUE TITLE
API download confirmation page response code

### ISSUE THREAD

**Issue by jackbentley** [SpongePowered/Ore#254]
The download confirmation page probably shouldn't return a 200? The user's request for a download hasn't been fulfilled yet. This would help people to be able to catch the response when implementing the API.

I think maybe a 300 response would be more appropriate? Since they have a choice of accepting and downloading or not downloading.

_Also, as a side note, I feel the whole 'confirm download' thing is rather 'developer-unfriendly'. If someone's using the API, such things are implied when performing the request. For example, you probably wouldn't double check someone wants to delete an object when they send a DELETE request via an API. Maybe a query parameter for people already aware might be a good comprise for times sake?_

**Comment by mbax** [comment]
To just respond to the side note, the confirmation is only for files that have not yet been reviewed/approved.

**Comment by jackbentley** [comment]
@mbax Which makes all the more reason for the response code to be changed appropriately 😉

**Comment by windy1** [comment]
I agree that the response code should not be 200. It will be changed to `300 Multiple Choices`. I don't agree that these things are necessarily implied or assumed when making a request. The confirmation is to encourage API consumers to present the end user with the confirmation.

**Comment by jackbentley** [comment]
@windy1 Awesome! 😄 And, I understand why you're displaying it, it just thrown me as it's something unusual that I wasn't expecting to implement. I still think a query parameter would be nice - what if the end user is the API consumer? (bash script for example)
