### ISSUE TITLE
Add support for external downloads

### ISSUE THREAD

**Issue by Guichaguri** [SpongePowered/Ore#255]
External downloads are mainly useful when the plugin is universal (it works on Sponge, Bukkit, BungeeCord, even Forge and LiteLoader in some cases) and having to upload the same jar file everywhere is not optimal.
Spigot, for instance, is already supporting external plugin downloads.

**Comment by stephan-gh** [comment]
I don't really understand how that helps. The effort required to upload a JAR or to update the external link to the JAR on every plugin portal is almost the same. On the other hand, external links tend to break when the server it is hosted on goes down (I've noticed it on Spigot several times already!) and will allow the authors to bypass our review system.

**Comment by mbax** [comment]
There should be a negligible difference between "uploading a file and copy/pasting the changelog" and "updating a download link and copy/pasting the changelog" so I don't see a good reason to allow this. I do see reasons to not allow it, as listed above.

**Comment by progwml6** [comment]
For security reasons i'm going to have to recommend against this, due to the reasons mentioned above, and the ability to change the jar at the hosted location at any time. 

Additionally, If the workload is too much for uploading to multiple locations manually, build systems can handle changelogs & uploading to multiple places for you.

**Comment by Guichaguri** [comment]
Thanks for the response. Automating the build system would probably be the best option. Is there an API for Ore?

**Comment by windy1** [comment]
[Yes there is.](https://docs.spongepowered.org/stable/en/ore/api.html)
