### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by windy1** [SpongePowered/Ore#26]
Play can be localized through the `Messages` API. Currently there's a mix of string constants defined in the `conf/messages.en-US` file and in plain HTML mostly cause lazy but Ore can be localized by creating new files with language code extensions (`conf/messages.fr`).

Most strings in the views should be moved to language files.

**Comment by Zidane** [comment]
@windy1 

Did that last PR cover this? I'm assuming you're putting new strings you add into the lang file by default.
