### ISSUE TITLE
Unable to update plugins. 

### ISSUE THREAD

**Issue by axle2005** [SpongePowered/Ore#261]
Been unable to update a few of my plugins for about a week now. 

-File is 16KB in size. 
-Contains a valid mcmod.info

Browser & Version: ` Chrome 58.0.3029.96`

Operating System: `Windows 10`

Error message (if applicable): `Ore is experiencing difficulties, Unexpected exception[NullPointerException: null]`

Steps to reproduce:

* Step 1
Select file to upload. 
* Step 2
Sign file to upload
* Step 3
Click Upload.

**Comment by windy1** [comment]
Hi, looks like you managed to get you plugins up. Did you change anything to get it working?

**Comment by axle2005** [comment]
I recompiled it with gradle instead of maven... not sure if that helps with anything... probably somehow related to the mcmod.info file, although I can 100% guarantee that was present in the jar.

**Comment by windy1** [comment]
Are there any differences between the maven and gradle built files? If so can you paste them? Thanks.
