### ISSUE TITLE
Unexpected exception[NoSuchFileException: /home/ore/files/plugins/Revilo/MultiChat/multichat-1.5.jar]

### ISSUE THREAD

**Issue by Tenelia** [SpongePowered/Ore#266]
Indeed it is as the title says: Unexpected exception[NoSuchFileException: /home/ore/files/plugins/Revilo/MultiChat/multichat-1.5.jar]

Taken from https://ore.spongepowered.org/Revilo/MultiChat/versions

**Comment by windy1** [comment]
Duplicate of #258
