### ISSUE TITLE
3 days to submit after public key addition.

### ISSUE THREAD

**Issue by varrix** [SpongePowered/Ore#267]
When you change your public key, you must wait 3 days to submit a plugin. Not a big deal, but was wondering if this was intended to be applied to those who have yet to submit a plugin?

ie: New to ore, adds public key, changes public key(or not- does this happen even if you just add and not change?), goes to submit- needs to wait 3 days.

Now, if this was the intended behaviour- understandable. Any plans to reduce this to 1 day for anyone who is submitting their first plugin?

Thanks in advance!

**Comment by Icohedron** [comment]
I don't remember having to wait 3 days after adding my first public key in order to publish my first plugin.
I just started a couple months ago.

**Comment by mbax** [comment]
@Icohedron what's described above is changing the key prior to first submission. That is:

1) Sign up.
2) Set key.
3) Set key a second time because you **really like keys**.
4) Try to upload, denied because you changed it after setting it once.

**Comment by Icohedron** [comment]
Oh, oops. Didn't read the whole thing :sweat_smile:
Yea, there is a 3 day wait after setting it to something else, no matter how soon the change was compared to the last. I agree with the point being made that the cooldown should be shorter if you were to change it again within a short time frame or if it's your first upload.

**Comment by windy1** [comment]
Agreed, cooldown should not be enforced prior to first upload.

**Comment by Grinch** [comment]
@windy1 You should also make mention of this behavior BEFORE the delete action goes through. :p
