### ISSUE TITLE
Project name regex

### ISSUE THREAD

**Issue by windy1** [SpongePowered/Ore#27]
We need to come up with a regular expression for allowed project / channel / version names. Currently anything is permitted.

**Comment by kashike** [comment]
Related: https://github.com/SpongePowered/Ore/issues/9

**Comment by kashike** [comment]
I don't think there should really be a limitation on project/channel/version names - just slugify them for use in urls if there are any weird characters.

**Comment by windy1** [comment]
Ehh I honestly think we should disallow `~!@#$%^&*()/?.>,<'";:]}[{\|+=` at the very least. They don't really belong in names and are generally unappealing. A min/max size needs to be decided on as well.

**Comment by kashike** [comment]
I don't see a reason to disallow all of those, it limits names quite a bit.

**Comment by Tzky** [comment]
I'd only allow `A-Z`, `a-z` and `0-9` and _maybe_ some chars from above + `whitespace`. I can't think of any good reason to allow for ex. `@`, `$§` or other similar chars.

`@@@@@ SuperAwesomePlugin@@@@@` or `$$$ Economy $$$` <- no one wants those plugins or plugin names.

**Comment by kashike** [comment]
`a-zA-Z0-9-:!?. |` is what I'd suggest. It restricts things, but not too much.
- `Super Windy: Tornado Island`
- `Windy|Rain`
- `Have you seen Windy?`
- etc.

A filter could be written to disallow things like:
- `!!!!!!! Tzk !!!!!!!` (repeated characters)

**Comment by ryantheleach** [comment]
Or just remove things that are potentially malicious, and let the community sort it out?

If you are going to restrict it in addition to Kashikes suggestions
Allow & + - @ # ( ) [ ] , { }

Would allow stuff like "Trouble & Turmoil" "Ban++" "Minecraft@home" "Fast-Shop" "F# Noteblock Songs" "GriefPrevention (MinecraftPortCentral)"  "[FoxGuard] Heal Regions"

But ultimately I don't believe we should attempt to create validation rules for anything that doesn't directly cause conflict.

**Comment by windy1** [comment]
For now I decided not to limit characters allowed in project names. Names must be <= 25 chars and automatically has extra white space removed 

e.g.

``` java
"    My     Cool       Plugin     " -> "My Cool Plugin"
```
