### ISSUE TITLE
Error message appears when saving a page

### ISSUE THREAD

**Issue by pie-flavor** [SpongePowered/Ore#270]
An identical page to that of #269 appears, although the page still gets saved.

**Comment by lol768** [comment]
I've seen this, unsure if it's due to other pages in the BG rotating the CSRF token. Will look into it

**Comment by kashike** [comment]
Should be fixed with https://github.com/SpongePowered/Ore/commit/b47ccbe3afb63e9e1fea31a10575bd1241197f7f.
