### ISSUE TITLE
SSL Certificate Appears to be expired

### ISSUE THREAD

**Issue by Flibio** [SpongePowered/Ore#271]
The Ore SSL Certificate appears to have expired on June 28, 2017.

**Comment by simon816** [comment]
Probably outdated on your end. A new certificate was issued on 30th May, Let's Encrypt certificates last for 3 months.
See here: https://www.ssllabs.com/ssltest/analyze.html?d=ore.spongepowered.org&latest

**Comment by Flibio** [comment]
Thanks, is there any way I can refresh it?

**Comment by vectrixdevelops** [comment]
Refreshing your cache would probably do it.
