### ISSUE TITLE
Maximal amount of wiki pages

### ISSUE THREAD

**Issue by NeumimTo** [SpongePowered/Ore#272]
Is it possible to increase wiki pages limit? Currently we can have only 10.

**Comment by NeumimTo** [comment]
https://github.com/SpongePowered/Ore/blob/ac577384f5648a8ec83b7baba8e6c10c5543c99f/app/views/projects/pages/view.scala.html#L62 

after a little digging i found out that this is just configuration.

**Comment by phase** [comment]
This can be closed I believe.
