### ISSUE TITLE
Translation Support.

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/Ore#275]
Has Ore been designed with translation in mind?

If not, it needs to be converted. Having Ore be able to be translated, and plugin pages / plugins able to be translated will help contain **potentially** malicious rehosting.

**Comment by lol768** [comment]
Ore is somewhat localised as far as I'm aware, see https://github.com/SpongePowered/Ore/blob/master/conf/messages

Unsure what the state is with plugin pages

**Comment by ryantheleach** [comment]
I'm referring to being able to serve multiple locales, as well as the build tooling in place.

**Comment by Katrix** [comment]
Superseded by #544
