### ISSUE TITLE
API response should contain an api object

### ISSUE THREAD

**Issue by kinggoesgaming** [SpongePowered/Ore#278]
This allows for API libraries that want to support multiple versions, a confirmation object that shows what revision is used.

Something like

```json
{
    "api": {
        "version": "v1",
        "latest: true (or latest version string like "v2" perhaps)
}
```

will do :smile:

**Comment by phase** [comment]
The user should have to specify what API version they want in the URL, and they can support multiple versions by using different URLs.

```
/api/v1/blahblah
/api/v2/blahblah
```

**Comment by kinggoesgaming** [comment]
Just talking from a third party API user's verification support.

**Comment by kinggoesgaming** [comment]
now that `/api/*` nodes are deprecated in favor of `/api/v1/*` this should be unnecessary anyway... closing
