### ISSUE TITLE
Adding yourself as a member to an organisation project removes project privileges.

### ISSUE THREAD

**Issue by kinggoesgaming** [SpongePowered/Ore#285]
Recently realized that I could no longer could access the settings for my Spotlin project. After fumbling about I noticed that i had added myself as a developer in the project as the last thing i did. After Zidane kindly removed me as a dev, I could access settings again.

Steps to reproduce:

* In a organization user, add a project.
* Add yourself as a developer or lower
* lose access to project settings
* ...
* All hell set loose....

**Comment by lol768** [comment]
So I can see potential approaches for fixing here, assuming I understand correctly:

* Disallow users having multiple roles (owner and developer)?
* Fix the permissions checker to favour the best permission that the user has access to - either from the organisation or from the project itself (if there is a distinction to make here)

**Comment by vectrixdevelops** [comment]
@lol768 I like the second approach better, as multiple roles may be useful.

**Comment by Grinch** [comment]
@phase Could you take a whack at this?

**Comment by phase** [comment]
So you want your role as owner of a project to override your role as developer in the org? That shouldn't be too difficult.

**Comment by phase** [comment]
`user_organization_roles` has you listed as an _OrganizationOwner_ of `pxlpowered`.
`user_project_roles` has you listed as a _ProjectDev_ of `Spotlin`.

It looks like you were incorrectly made a _ProjectDev_ when you created the project.

This brings up the question of _Why would you want to lower yourself in your own Organization?_ I don't see a real use case for it.

Wait a minute, _how did you lower yourself?_ That isn't possible.

**Comment by phase** [comment]
I wasn't able to reproduce this locally.

I made a test organization, and I created a project underneath it. I am the owner of the organization, and I added myself as a member of the project as a developer. I am still able to access the settings.

![org](https://i.imgur.com/0I8MI3o.png)

![project](https://i.imgur.com/z3Pn91Z.png)

**Comment by progwml6** [comment]
@phase could not reproduce in either local or production testing. If you are able to reproduce feel free to re-open this

**Comment by phase** [comment]
Pre-mature close: I forgot to accept the invitation to become a developer on the project, and once I accepted it I lost permission to access settings. Locally, I forgot I had all permissions because I'm an admin.

**Comment by kinggoesgaming** [comment]
:clap: 

Yes I know I haven't been on this in a long while... basically everything minecraft related in general

Thanks kashike and phase :)
