### ISSUE TITLE
Projects not appearing in list of projects for an Author

### ISSUE THREAD

**Issue by Zerthick** [SpongePowered/Ore#286]
Hello, I've noticed that one of my plugins [ProtectionPerms](https://ore.spongepowered.org/Zerthick/ProtectionPerms) does not show up in the list of plugins under my [homepage](https://ore.spongepowered.org/Zerthick). Not sure if this is isolated or occurring on a larger scale yet.

**Comment by Zerthick** [comment]
Upon further investigation it looks like my [SayItem](https://ore.spongepowered.org/Zerthick/SayItem) plugin is duplicated twice, replacing the entry for ProtectionPerms

**Comment by phase** [comment]
![2017-10-26-214631_1920x1080_scrot](https://user-images.githubusercontent.com/7685133/32088335-52a94dee-ba97-11e7-88a4-f904dc13818a.png)
![2017-10-26-214636_1920x1080_scrot](https://user-images.githubusercontent.com/7685133/32088341-57f2a3a4-ba97-11e7-9383-532c0f58c8c4.png)

Now it looks like ProtectionPerms shows up twice. I'm not sure if it's replacing something or it's just off by one on that page.

**Comment by Zerthick** [comment]
Now it's replacing my [ColorAnvil](https://ore.spongepowered.org/Zerthick/ColorAnvil) plugin.

**Comment by phase** [comment]
ColorAnvil & SayItem have reappeared, and ProtectionPerms only shows up once. Is there another plugin that is missing from the list? Here's what I can see:

* Graveyards
* PlayerShopsRPG
* CommandBooks
* Mailboxes
* SayItem
* SerializeMe
* ProtectionPerms
* ActionMessage
* NoSleep
* ColorAnvil
* CommandCore
* Presents
* CoinPurse
* LinkMe

**Comment by Zerthick** [comment]
It seems to have somehow sorted itself out now, all my plugins are visible and appear only once.

**Comment by Zerthick** [comment]
After doing some plugin updates the problem has resurfaced. My ProtectionPerms plugin is being duplicated and the SayItem plugin is missing.

**Comment by phase** [comment]
Projects on user pages are sorted by star count. I had an issue earlier with sorting, so I assumed that it projects that weren't appearing were being sorted differently by different queries. I started ProtectionPerms and SayItem reappeared. This is a bug with project sorting.
