### ISSUE TITLE
Filter by Platform Version and Minecraft Version

### ISSUE THREAD

**Issue by n00b42** [SpongePowered/Ore#294]
- Filter by Minecraft Version
- Filter by Sponge API Version

**Comment by ryantheleach** [comment]
To effectively add this I think we need more support for specifying a range of versions that a release will work on.

I'd suggest filtering by Sponge API __only__.

 Minecraft Version, if added, can just be a parent category of Sponge API version if we go down that route.

**Comment by phase** [comment]
This should be included with the Tag system I described in #307.

**Comment by bloodmc** [comment]
Yes this needs to be done as the average user will have no idea what Sponge API version means. It's ok for it to be included somewhere but the main search should be by MC version.

**Comment by phase** [comment]
@ryantheleach said

> It should be Minor / Patch version aware, so if a plugin is uploaded with a 4.1 dependency, that would not show on a 4.0.0 filter.
> 
> However a 4.0.0 plugin would show on a 4.1 filter.

:+1: on that

he also offered this mockup for a _first time user_

![](https://user-images.githubusercontent.com/141554/35490294-aa019f96-04ee-11e8-92f9-eb2f09da2aea.png)

**Comment by phase** [comment]
Minecraft Versions are waiting on https://github.com/SpongePowered/DownloadIndexer/issues/7

**Comment by phase** [comment]
I'm adding SpongeForge, SpongeVanilla, & SpongeCommon filtering to this issue too.
See the discussion in https://github.com/SpongePowered/SpongeForge/issues/2367

**Comment by gabizou** [comment]
Will be able to filter by sponge implementation versions too, if a plugin depends on a specific sponge common (to work on sponge vanilla or sponge forge).

**Comment by phase** [comment]
~~changing the title again just for the fun of it~~

Changing the scope of this issue ~~again~~ to encompass all platform version filters, as I will do them all at the same time. Every platform will have an associated version parser. 

Long version strings will be shortened. Things like `-SNAPSHOT` are long and foreign to users. I think we should replace `8.0-SNAPSHOT` with `8.0*` or something similar (maybe the star can be blue or some different color?) to differentiate it from a normal version. Same goes for the new Sponge implementations' `RC`.

| Platform | Version Pattern| Version Example | Notes|
|------------------|----| --|--|
| Sponge API | `MAJOR.MINOR(.PATCH)?(-SNAPSHOT)?` | `8.0` | Patch won't exist for 8.0 and onward. |
| Sponge Common | `MCVER-MAJOR.MINOR.RC(-SNAPSHOT)?` | `1.12.2-8.0.2` | We need to support old & new patterns |
| Sponge Forge | `MCVER-FORGEVER-MAJOR.MINOR.RC(-RC##)?` | `1.12.2-2705-7.1.4` | We need to support old & new patterns |
| Sponge Vanilla | `MCVER-MAJOR.MINOR.RC(-RC##)?` | `1.12.2-7.1.4` | We need to support old & new patterns |
| Lantern | `MCVER-MAJOR.MINOR.RC(-RC##)?` | `1.12.2-7.1.4` | Same as SpongeVanilla, won't go into affect for a bit but it should be fine to use it now. |
| Forge | `MAJOR.MINOR.PATCH.BUILD` | `14.23.4.2705` | Confirm the format? |

A translation from Platform Version to Minecraft Version will be added for platforms that don't have the MC version in the format.

**Comment by phit** [comment]
can we add mc version to forge? should be easy to get from the version number just needs a table, i.e. when:
14.21 > 1.12
14.22 > 1.12.1
14.23 > 1.12.2

and add this in from of the version, example `1.12.2-14.23.4.2705`

also i dont agree with making snapshot just a small star, for all i care make it a big red warning, you really shouldnt depend on snapshots

**Comment by phase** [comment]
We could put the MC version somewhere else so that the tag is smaller.

**Comment by Katrix** [comment]
Now supported with the new Vue frontend
