### ISSUE TITLE
Firefox 57, cannot display collapsed child wiki pages

### ISSUE THREAD

**Issue by NeumimTo** [SpongePowered/Ore#297]
Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0

Steps to reproduce:
Create a wiki with similar page structure 
- Root
   - Page 1
   - Page 2
- AnotherPage

(eg https://ore.spongepowered.org/NeumimTo/NT-Rpg)
With firefox 57 its not possible to, display nested pages by clicking on the '+' 
I also tested this on ubuntu 17 and the result was same. Chrome on same machine wors fine.

**Comment by phit** [comment]
Same with Nightly 59.0a1

**Comment by phase** [comment]
I'm not able to reproduce this on Ubuntu 16 w/ FireFox 57.0.1, nor with Chrome. Are there any errors in the console?

**Comment by vectrixdevelops** [comment]
I just tried this with Windows 10 59.0a1 (2017-12-22) (64-bit) and the issue didn't seem to occur.

**Comment by phit** [comment]
figured it out, its uBlock causing it.. specifically 

![image](https://user-images.githubusercontent.com/2097483/34314615-969e313a-e775-11e7-8560-b513175874a5.png)

**Comment by vectrixdevelops** [comment]
uBlock a long with some others appear to use this filter list to block certain scripts and things by name. https://easylist.to/easylist/easyprivacy.txt (search for it on that list)

It probably needs to be renamed.
