### ISSUE TITLE
Roadmap?

### ISSUE THREAD

**Issue by connor4312** [SpongePowered/Ore#30]
I'd like to pick up some Django and contribute/by contributing. There seem to be several open issues, but many lack description or implementation status. Having a ROADMAP doc in the repo would help so that prospective contributors know where to focus their efforts.

**Comment by lukegb** [comment]
This'd be nice. Basically at the moment I don't really have time to contribute, at least until after my exams are over (so a few weeks time).

**Comment by gratimax** [comment]
I'll try to write this up as a Google doc (or perhaps a Markdown file, except edits there require unnecessary commits to the repository), because this does seem like a needed addition.

**Comment by connor4312** [comment]
Sticking a markdown file in the directory root is kind of a standard thing to do. It's related to and changes as the codebase changes, so it seems like a good place. Commits aren't bad, and storing it in vcs is good for historical purposes :wink:

**Comment by gratimax** [comment]
I gave something close to a roadmap [here](https://forums.spongepowered.org/t/custom-maps-auto-download-plugins-client-side/6757/24), if you haven't already seen it. I am working on the relevant markdown file and should commit it by the end of today.

**Comment by connor4312** [comment]
Great :smile:

**Comment by gratimax** [comment]
I've edited and committed the roadmap [here](https://github.com/SpongePowered/Ore/blob/master/ROADMAP.md). It's still rather rough so I'll leave this issue open for discussion. It is also missing more granular information like due dates or implementation plans, but I think that most of those belong in issues.
