### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by windy1** [SpongePowered/Ore#30]
Site needs a footer. Please discuss what you think it should contain here.

**Comment by Zidane** [comment]
@windy1 

I'm discussing this with Dockter as we may use it for sponsorship opportunities.

**Comment by Zidane** [comment]
@mcsnetworks

Did you have ideas for the footer regarding sponsorship?

**Comment by windy1** [comment]
Any update on this one @Zidane? As a side note any ideas for content that should go above the home page project table? It's a bit bare right now IMO.
