### ISSUE TITLE
Show who signed a plugin.

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/Ore#300]
As a user, I'd like to be able to see who uploaded and signed a plugin release.

Whether that be a user on Ore, an Admin, or a shared key / organization key.

**Comment by phase** [comment]
Here's an idea:

![image showing this off](https://i.imgur.com/UMiB9Xx.png)
![image showing my pointer hovering](https://i.imgur.com/ISKJWst.png)

A key next to the download linking to the user than signed it would look nice. Here's the HTML for that:
```html
<a href="{{ link-to-user }}">
    <i title="Signed By: {{ user }}" class="fa fa-key"></i>
</a>
```

The spacing may need to be modified. Is this what you envisioned?

**Comment by ryantheleach** [comment]
Thanks! The only difference I'd make, is make the key red, if the release was signed by a non project member. e.g. Ore admin, ex project member, etc, if it's intended that still be a possibility in the future.

Or maybe indicate their role.
