### ISSUE TITLE
Admin role for organisations doesn't persist

### ISSUE THREAD

**Issue by me4502** [SpongePowered/Ore#301]
Browser & Version: `Unknown`

Operating System: `Unknown`

Error message (if applicable): `None`

Steps to reproduce:

I'm currently `Developer` in the `EngineHub` organisation. Ever since the `Admin` rank was added, both the owner of the organisation and numerous people with global access on Ore have tried setting my rank to Admin. This has not applied each time.

* Try setting me to Admin on the EngineHub organisation
* It won't apply
* I'll still be developer

**Comment by phase** [comment]
I was able to replicate this [on a test organization](https://ore.spongepowered.org/Testing301) pretty easily. I can't change @connorhartley's role at all. It looks like role updates aren't being saved to the database.

Here's some rubber duck debugging for myself:

Frontend:
A [`form`](https://github.com/SpongePowered/Ore/blob/09ff55b85bf11270cc6e487707a3203f019645aa/app/views/users/memberList.scala.html#L95) is sent to `/organizations/Testing301/settings/members` correctly, but I'm not sure if the data that is being sent is correct.

Backend: 
[`conf/routes`](https://github.com/SpongePowered/Ore/blob/master/conf/routes) shows that a POST request sent to `/organizations/:organization/settings/members` will run through [`Organizations.updateMembers(organization)`](https://github.com/SpongePowered/Ore/blob/09ff55b85bf11270cc6e487707a3203f019645aa/app/controllers/Organizations.scala#L143), which calls [`OrganizationMembersUpdate#saveTo`](https://github.com/SpongePowered/Ore/blob/09ff55b85bf11270cc6e487707a3203f019645aa/app/form/organization/OrganizationMembersUpdate.scala#L24). 

`saveTo` is split into two parts: adding new roles, and updating existing roles. The latter [goes through the members in the organization](https://github.com/SpongePowered/Ore/blob/09ff55b85bf11270cc6e487707a3203f019645aa/app/form/organization/OrganizationMembersUpdate.scala#L44-L45), and [updates the roles in the DB](https://github.com/SpongePowered/Ore/blob/09ff55b85bf11270cc6e487707a3203f019645aa/app/models/user/role/RoleModel.scala#L53).

<br>

The first thing that stands out is this mess of code from `OrganizationMembersUpdate#saveTo`:
```scala
  // Update existing roles
val orgRoleTypes = RoleTypes.values.filter(_.roleClass.equals(classOf[OrganizationRole]))
for ((user, i) <- this.userUps.zipWithIndex) {
  organization.memberships.members.find(_.username.equalsIgnoreCase(user)).foreach { user =>
    user.headRole.roleType = orgRoleTypes.find(_.title.equals(roleUps(i)))
      .getOrElse(throw new RuntimeException("supplied invalid role type"))
  }
}
```

I need to do some debugging to see if it is finding the correct user and the correct role.

<br>

A real issue that's blocking me from debugging is not being allowed to create an organization locally without SpongeAuth. SA sadly has [0 documentation](https://github.com/SpongePowered/SpongeAuth), but I'll set it up in a second or see if I can work around it.
