### ISSUE TITLE
WIP Tags

### ISSUE THREAD

**Issue by vectrixdevelops** [SpongePowered/Ore#307]
Based on what Owen said in the SoS 15 stream, that the work in progress plugins section will be removed from the Forums and replaced by a tag that can be added to plugins on Ore, a long with a warning at download.

**Comment by phase** [comment]
Currently, there are two "tags" that are displayed with plugins: _Sponge_ and _Forge_. These tags contain the version of the software they they are compatible with. (There are [two plugins](https://ore.spongepowered.org/?page=1&platform=Forge) in the current DB that contain a _Forge_ tag, but for some reason their version number is null.)

What's interesting about this is that these "tags" aren't _tags_, they're [boolean fields in the Project class](https://github.com/SpongePowered/Ore/blob/a457726575afaf42082c133fa2d5ec2c4f5b1c43/app/models/project/Project.scala#L59-L60).
```scala
private var _isSpongePlugin: Boolean = false,
private var _isForgeMod: Boolean = false,
```

What I propose is that we remove these and put in an actual _tags_ system that we can use to label plugins with. (These tags should have consistent artwork with the badges I described in #306.) I think if we're going to implement this, we need to have some use cases. Here are some tags that come to mind (with the data they may store):

* Sponge (Version)
* Forge (Version)
* WIP
* Approved (person who approved)
* Sponsored (Sponsor)? (#120)

Anyone got any other ideas for tags? Does this sound like a good system?
