### ISSUE TITLE
Whose signature should be used on upload?

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/Ore#318]
It's currently possible (as a staff role) to upload to other peoples projects, with #302 being merged, this is now (somewhat) transparent to the end user. (I'd argue uploads with signatures from those other then the **current** project team, should be highlighted as red to indicate error, red for ex-members and staff uploading on someones behalf to make sure they standout)

However, during upload, it's impossible to upload on another users behalf (currently, on the web frontend)

If the binaries have been signed off by an author, I see no reason why staff, or an organization account (used for a CI server or something strange?) shouldn't be able to upload using a provided signature, and binary (not key) for another author.

Maybe there is some security aspect I'm not considering, (I suspect it was originally done as a secondary guard against key theft).

 But is this functionality wanted?

I ran into it when uploading a plugin on behalf of Phit, when investigating the missing jar issue, to work out if it was possibly a sketchy internet connection, but found I had to sign with my own key, rather then using phits signature he sent me.

I would have thought, once signed it would have been all good?

**Comment by phit** [comment]
I would argue this should stay, as a extra layer of security (as you said, loss of key). If you have a CI or org account create a key for that user to sign your stuff. No reason to share your personal key with your CI or Org.

**Comment by Faithcaio** [comment]
I like the idea of a separate upload key for orgas.

**Comment by progwml6** [comment]
there are 2 issues here that need to be addressed here.
1: orgs need to be able to add keys(with corresponding names like "team jenkins"
2: staff need to be able to upload for other people to troubleshoot bugs
