### ISSUE TITLE
UX: Filtering based on installed Sponge version.

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/Ore#321]
I'd like to see a UX that heavily promotes filtering of plugins based on their installed version of Sponge.

This will make it easier to educate users on which plugins are considered working on what versions of Sponge.

It should be Minor / Patch version aware, so if a plugin is uploaded with a 4.1 dependency, that would not show on a 4.0.0 filter.

However a 4.0.0 plugin would show on a 4.1 filter.

As a spicy addition, I'd also like to see some way of users to be able to test and provide feedback, say on plugins that worked on API 4, that still worked on API 5, that would allow an API 4 plugin to show in an API 5 list with a warning. e.g. "Users have signaled that this plugin remains compatible on API 5, but an official update from the author is not yet available"

**Comment by phase** [comment]
Filtering based on tags is planned once the Tags PR is merged (#308).

See #294

**Comment by ryantheleach** [comment]
This is supposed to be a larger picture ticket, to work beyond basic filtering support and really drive the point home. 

#294 would be a dependency/blocker of this ticket.

What I'm imagining, is that first time users? all users? would see explicit UI for API version and choosing their currently installed sponge version so it selects the right filter for them.

Think like a wizard, as opposed to a boolean advanced search.

**Comment by phase** [comment]
Ah, that would be neat.

**Comment by ryantheleach** [comment]
![image](https://user-images.githubusercontent.com/141554/35490294-aa019f96-04ee-11e8-92f9-eb2f09da2aea.png)

Is what I'm imagining for a first time user, or a new session where the old session was some time ago.

**Comment by phit** [comment]
switch the API and Minecraft version label, as this is for users Minecraft version is more important and should be the big number

**Comment by ryantheleach** [comment]
I heartily disagree. 

The API version is the thing that counts and is the thing that makes the semantic difference. To put emphasis on the Minecraft version over the API version instills the notion that MC version counts more.  to have the MC version emphasized defeats the entire point of having such a large banner at the top.

This provides a subtle hint as to what they should consider when choosing a plugin for later,

If you just wanted filtering by MC version, then I would suggest just using the existing categories as this is a large screen real estate sacrifice for the sake of education.

**Comment by phase** [comment]
Condensing to #294
