### ISSUE TITLE
Project Activity Log

### ISSUE THREAD

**Issue by SimonFlash** [SpongePowered/Ore#323]
During our discussion about #322, one of the arguments in favor of having the automated posts is that it keeps track of the projects activity and notifies users when a version is released. However, this is done in a roundabout way because the notification comes from the post and not Ore itself. In response to this, we talked about having an activity log for the project that documents releases and various other actions.

The activity log would essentially be a timeline of events that have occurred with the project, such as:

* Project status changes (like being marked as discontinued)
* New releases
* New discussion posts

This could even be taken a step further to include other events like:

* Changes to the docs
* Changing the recommended version
* GitHub commits, issues, etc. (would require the project to be linked to GitHub)

On the subject of including GitHub events, I would presume that the majority of people concerned about development proceedings would already be doing so from GitHub itself. To prevent an unwanted duplicate system, it should be possible to disable notifications for certain events for the project (what's displayed on the activity log) and the user (what they receive notifications for). This is starting to get into a subject worth of it's own issue, but the import part is to note that having many events displayed on the activity log should not cause users to receive endless notifications.

As much as I like having everything customizable, I believe that events like new releases should always be posted to the activity log. Other events such as discussion posts or development updates should be customizable to the project.

**Comment by Katrix** [comment]
A form of this already exists in Ore, but is limited to moderators. It's at the moment unlikely that we'll expose this to normal users.
