### ISSUE TITLE
Longterm Goals

### ISSUE THREAD

**Issue by phase** [SpongePowered/Ore#324]
# Version 1.5

We're on our way to 1.5. Tags (#308) and maybe some other features will be added in within the next month or so, but other then that all the big bugs have been fixed.

Can we call a feature freeze at the end of January? We're going to need one for...

# Version 2.0

@felixoi and I have been talking, and Ore is highly unmaintainable. For Version 2.0, we want to rewrite the frontend in [Vue.js](https://vuejs.org/) (with [Flow](https://flow.org)) using a [REST API](https://docs.spongepowered.org/stable/en/ore/api.html). The backend for Ore will stay in Scala for 2.0. We can rewrite it in a different language if need be later.

**Comment by phase** [comment]
Design PRs will also need to be merged before 1.0 (#310, #319).

**Comment by ryantheleach** [comment]
API Libraries and Descriptors should be published.
Prog says that we should be able to make our Javascript side API shim available to others with docs.

**Comment by phase** [comment]
For the REST API, @progwml6 wants to modularize the JS that interacts with Ore and the frontend JS, so that people can write tools that can use the REST JS to make Ore tools. This REST JS will be in its own NPM repo.

Ore needs a way to generate the REST API from the existing classes. [There isn't a lot the current Web API](https://docs.spongepowered.org/stable/en/ore/api.html) can do. We need to rewrite all of it using templates. [API Blueprint](https://apiblueprint.org/) can be used, it's what [CreeperHost](https://creeperhost.docs.apiary.io/) uses.

**Comment by stephan-gh** [comment]
[SpongeDownloads](https://github.com/SpongePowered/SpongeDownloads) uses [Swagger](https://swagger.io) ([`swagger.yaml`](https://github.com/SpongePowered/SpongeDownloads/blob/master/swagger.yaml)): https://spongedownloads.docs.apiary.io

It doesn't really matter though because Apiary supports both. It might make sense to check which one works best for Ore. It's definitely good to use one of them for documentation though (and possibly code generation too but only if that works properly).

**Comment by progwml6** [comment]
code generation is my goal here as it would be much less overhead for developing based on our apis both internally and for those who want to develop bots/panels that use our information

**Comment by dualspiral** [comment]
Just a note, [Ore's version is currently 1.4.1](https://github.com/SpongePowered/Ore/blob/master/build.sbt#L3), so the next version would either have to be 1.5 or 2.0.

**Comment by ryantheleach** [comment]
For those 'playing along from home' I've created a [rough road map](https://github.com/SpongePowered/Ore/milestones) that I've shown to staff for feedback, as of yet any scheduling beyond 1.x.x is unofficial and subject to change.

Scheduling within 1.x.x is a rough draft by myself and is under review, I may have been a little [bold](https://en.wikipedia.org/wiki/Wikipedia:Be_bold).
