### ISSUE TITLE
Any downloaded version - latest version (if equal filenames was used)..

### ISSUE THREAD

**Issue by realGWM** [SpongePowered/Ore#326]
Browser & Version: `Firefox 57.0.3-1`

Operating System: `Arch Linux`

(I dont think info above will be helpful, but it was in the template... xD)

Steps to reproduce:

1. Download any version of plugin - it will be latest version...
Video: https://youtu.be/RAFGkm3BIRo

**Comment by progwml6** [comment]
this project has multiple files with the same name in the same project (GWMCrates.jar) -

All files should be stored in plugins/<organization/user name>/<project>/<version>/FILES
icons can be stored in plugins/<organization/user name>/<project>/icons as they are now

the script written to handle corrupted files or something in scala needs to be written to move all plugins to new directories

A solution is needed for the versions that are missing jars

**Comment by progwml6** [comment]
the missing jar versions will likely just be deleted
