### ISSUE TITLE
Docker build fails on fresh clone

### ISSUE THREAD

**Issue by masterkoppa** [SpongePowered/Ore#33]
Docker build seems to be failing at the static file collection step.  

See [https://gist.github.com/masterkoppa/9601d86f82141ce6c5d7](https://gist.github.com/masterkoppa/9601d86f82141ce6c5d7).

There's a mention of something similar going on with the heroku instance, are they related? If not, any pointers on how to potentially fix this? I'd be willing to give it a shot, but I don't have extensive django experience. (Mostly rails lately)

**Comment by masterkoppa** [comment]
Additionally I didn't want to create another issue for this, but would there be interest in creating a development environment inside docker? 

Using [docker-compose](https://docs.docker.com/compose/) you can easily mount the codebase in a volume and avoid having a local install of PostgreSQL while still having the benefits of simply refreshing the page to view your changes.

I've done this successfully in the past for other projects, figured I'd ask before I submit an unwanted pull request. [Example](https://github.com/masterkoppa/Ore/blob/docker-compose/docker-compose.yml)

**Comment by gratimax** [comment]
Docker failing _is_ related to static files, just like heroku. I will rework the Dockerfile and deployment in the future. I am in the process of learning the more advanced stuff of docker, so hopefully an eventual deployment would look like this:

- volume for static files
- app docker container
- nginx docker container, using staticfiles from volume
- postgres docker container

And with some of Ore's "someday features", these other containers would be added as well:

- message queue/redis container
- worker/job runner containers

**Comment by gratimax** [comment]
I transplanted your compose commit into https://github.com/SpongePowered/Ore/tree/docker-compose. I'll try to add nginx and fix staticfiles as soon as I can. Once I do that, staging dev will be easy, fixing #31.

**Comment by masterkoppa** [comment]
Cool sounds like you were headed on the right track. Glad that commit was useful, I'll be keeping an eye out for those static file fixes and see how I can help in the future. Looks like a really promising project, keep it up :+1:

**Comment by gratimax** [comment]
The compose build now works on the "docker-compose" branch, I'll be merging it shortly.
