### ISSUE TITLE
Simplify downloads for headless servers

### ISSUE THREAD

**Issue by worm424** [SpongePowered/Ore#334]
When trying to download from ore on a headless server using curl -O -J -L https://ore.spongepowered.org/Nucleus/Nucleus/versions/1.2.2-S7.0/download
it's provides a download link in a readme file involving tokens see below with a warning that it hasn't been reviewd
curl -O -J -L -d -X "https://ore.spongepowered.org/Nucleus/Nucleus/versions/1.2.2-S7.0/confirm?downloadType=0&token=zxzxzxzxzx&csrfToken=zzxzxzxzxzxz"

Can we remame the file from `README.txt` to something like `<plugin-slug>-<channel>-<version>-README.txt` and add support for Wget maybe with warning to use at your own risk

**Comment by ryantheleach** [comment]
This is painful intentionally.

This only happens for unapproved plugins, and approved plugins, that will download the plugin itself, and should work with wget afaik.
 
The renaming of the readme is a minor usability issue, but I think we can safely fix that.
