### ISSUE TITLE
Forum group / Ore sync broken?

### ISSUE THREAD

**Issue by JBYoshi** [SpongePowered/Ore#338]
The Ore profile pages show a list of the user's groups in the top-right corner ([sample](https://ore.spongepowered.org/kashike)). However, I noticed that my Sponge developer group hasn't been synced to Ore yet, even after six months. There are also a couple other users I found that don't have their roles synced either.

Browser & Version: Safari 11.0.2

Operating System: macOS 10.13.2

Steps to reproduce:

* Look at another Sponge staff member's Ore page (such as kashike's, which is linked above)
* Notice that "Sponge Developer" or a similar role appears on the page
* Look at [my Ore page](https://ore.spongepowered.org)
* Notice that "Sponge Developer" appears on the first page, but no labels appear on the rest

I marked this as "low priority", but there may be some difficulties with syncing roles when we add new reviewers, so it might change.

**Comment by ryantheleach** [comment]
I've removed it as low priority, as it shows that there is a sync issue that I suspect may also indirectly affect bans etc. But as it's not yet shown to be critical, I've scheduled it for after launch.
