### ISSUE TITLE
"More" button shows up always (even if un-needed)

### ISSUE THREAD

**Issue by Zidane** [SpongePowered/Ore#34]
The more button should be smart about showing up. Right now it shows even if a category has no projects.

As for showing up with projects, set a decent amount of projects before seeing it...whichever wouldn't tax the backend too much (20?)

**Comment by windy1** [comment]
My reason for this is that it will be (hopefully :p) a non-issue once projects start getting uploaded. Currently up to 50 projects are displayed on first load.

**Comment by windy1** [comment]
Handled in https://github.com/SpongePowered/Ore/commit/36c1b62d4852538006a8e2152921ca83bb09f1be
