### ISSUE TITLE
Give a warning if clicking on external link

### ISSUE THREAD

**Issue by Ewoutvans** [SpongePowered/Ore#342]
The links for issues, source, license are configurable by the user and could be set to malicieus website. We should add a modal with the full url in display and a disclaimer to inform the user that they are leaving the site and to what site they are going.

**Comment by phase** [comment]
Duplicate of #218

**Comment by mbax** [comment]
Thanks for the issue, @Ewoutvans !

Clicking through the above issue will eventually end you at the spot where we merged in code to make this happen. It'll go live soon :)
