### ISSUE TITLE
Unable to change organization logo

### ISSUE THREAD

**Issue by vectrixdevelops** [SpongePowered/Ore#344]
Browser & Version: All

Operating System: All

Error message (if applicable): N/A

Steps to reproduce:

* Hover over existing logo to see the message 'Edit Avatar' to change the logo appear.
* Click it and it doesn't work.

**Comment by phit** [comment]
also mentioned in this issue https://github.com/SpongePowered/Ore/issues/195
> Uploading an avatar for an org doesn't display anything at all.

Gonna leave this open as #195 needs to be split up anyway

**Comment by Ewoutvans** [comment]
I've pinpointed the problem to 'Not implemented'

https://github.com/SpongePowered/Ore/blob/04d7b947eff2c852e720185ee398152dfd73fa31/app/controllers/Organizations.scala#L117-L119

I believe the avatar has to be send back to the auth/spongepowered for changing

**Comment by BrainStone** [comment]
Now I remember why I didn’t set my organization’s logo back then 😂

Also try hovering over the “Edit Avatar” Text for special effects 👌🏻

**Comment by vectrixdevelops** [comment]
@BrainStone It flashes. 😮
