### ISSUE TITLE
New version not uploading after first try, only after second try.

### ISSUE THREAD

**Issue by realGWM** [SpongePowered/Ore#345]
After uploading new version - I still can download only previous version.
Only after deleting and uploading new version it can be fixed.
For me it happens everytime I upload new version...
Video: https://youtu.be/ZoE800Oy0fY

**Comment by phase** [comment]
~~everything is currently on fire, please stand by while we douse the flames~~

I currently recommend naming your jars with their versions appended on,

* `GWM-Crates-1.5.5.jar`
* `GWM-Crates-1.5.6.jar`

This will be solved momentarily.

**Comment by ryantheleach** [comment]
@phase @Ewoutvans @felixoi What's the status on this? 8 days feels like forever on Ore at the moment :-P

**Comment by phase** [comment]
This should have been fixed with #333

**Comment by ryantheleach** [comment]
@GreWeMa Can you test this? I believe that it's been pushed to production?

**Comment by realGWM** [comment]
@ryantheleach OK, I will test it when I upload new version!

**Comment by realGWM** [comment]
Confirmed, bug is fixed, thank you!
