### ISSUE TITLE
Discussion: Remove offline functionality

### ISSUE THREAD

**Issue by felixoi** [SpongePowered/Ore#349]
Currently, Ore supports cached site calls without an internet connection. It's called "offline mode".
I don't think that this mode is necessary since Ore is a plugin repo and the downloads aren't cached.

**Comment by ryantheleach** [comment]
Is this actively getting in the way of anyone?

**Comment by felixoi** [comment]
It just brings up some weird issues for some users.

**Comment by mbax** [comment]
What kind of weird issues? What subset of users (and how is that subset determined)?

**Comment by progwml6** [comment]
@felixoi feel free to remove this in your next pr

**Comment by malte-laukoetter** [comment]
The reason that was added was to allow the website to be installed on smartphones as an app as this needs at least some basic offline support: https://developers.google.com/web/fundamentals/app-install-banners/

**Comment by progwml6** [comment]
if you are interested in that feature, file an issue about it. the current implementation was causing other bugs that were breaking things
