### ISSUE TITLE
Login with forum credentials

### ISSUE THREAD

**Issue by pschichtel** [SpongePowered/Ore#35]
I think it would be nice to be able to login using the existing forum account.

**Comment by lukegb** [comment]
@gratimax has some stuff in the pipeline for this, I believe.

**Comment by gratimax** [comment]
The plan is to basically do the inverse of that. I'm in the process of writing an accounts system for "Sponge accounts". To use the forums, Ore, or any Sponge-related website you would login in with a Sponge account. The transfer would be almost completely transparent to current users, we would make sure to keep user data safe and whole and make the login experience as seamless as possible with Sponge-related websites.

A separate account system enables other features, like perhaps a "Sign in with Sponge" button that developers could use as an accounts system with their website:
![Sign in with Sponge](https://cloud.githubusercontent.com/assets/1261779/8325752/ba2891ac-1a10-11e5-9c02-59505dc69097.png)

**Comment by pschichtel** [comment]
Even better

**Comment by JBYoshi** [comment]
So, how would account migration work (forums/Ore staging -> Sponge account)? Would the Sponge team take care of that?

**Comment by TheDoctorsLife** [comment]
I'd imagine forums -> sponge account, seeing as that's the only place for an account right now.

**Comment by JBYoshi** [comment]
It looks like lukegb has already gotten SSO with Discourse working. b14d22f9a3aa8b34f3d7c0d2e76c8456f4bf0fd1

**Comment by pschichtel** [comment]
can that be tested on the test instance?

**Comment by pschichtel** [comment]
Ok just tested it, the first time when I wasn't logged in on the forum yet, the login did not redirect me back to Ore

**Comment by gratimax** [comment]
Right now the SSO works the other way. If you are signed into the forums and try signing into Ore, you will be signed in automatically without entering a password.

**Comment by JBYoshi** [comment]
Can this be closed?

**Comment by gratimax** [comment]
Yeah, thanks
