### ISSUE TITLE
Create admin pages for staff to modify Organizations/Users/Projects

### ISSUE THREAD

**Issue by Zidane** [SpongePowered/Ore#354]
I consider this a showstopper for Ore going live with projects from the forums.

Staff need the ability to have, based on level of permissions, capabilities to administer and change aspects of the project, Organization, and user profiles.

For example, I got a request from a user to take ownership of another project. I need a way to go and do that. Stuff like that. Especially to fix the broken state of projects we already have.

**Comment by simon816** [comment]
Should changing project ownership be possible by users or just staff?

**Comment by parlough** [comment]
I believe owners should be able to transfer ownership to someone else with a following confirmation, that then places them as admin instead.

**Comment by mbax** [comment]
That's out of scope of this issue, surely. But yes, they should have the power (but it should come with a pretty hard warning. See GitHub's transfer approach.

**Comment by simon816** [comment]
What level of permissions should we have for various actions?

Here are the staff roles we have currently:

|Trust Level|Roles|Permissions|
|---|---|---|
|Default|<ul><li>Sponge Contributor</li><li>Sponge Adviser</li></ul>|<ul></ul>|
|Limited|<ul><li>Sponge Documenter</li><li>Sponge Support</li></ul>|<ul><li>EditPages</li></ul>|
|Standard|<ul><li>Ore Moderator</li><li>Team Leader</li><li>Community Leader</li><li>Sponge Staff</li><li>Sponge Developer</li><li>Web Developer</li></ul>|<ul><li>EditChannels</li><li>EditVersions</li><li>HideProjects</li><li>ReviewFlags</li><li>ReviewProjects</li><li>ViewHealth</li><li>ViewLogs</li><li>PostAsOrganization</li></ul>|
|Lifted||<ul><li>EditSettings</li><li>CreateProject</li><li>EditApiKeys</li></ul>|
|Absolute|<ul><li>Ore Admin</li><li>Sponge Leader</li></ul>|<ul><li>ResetOre</li><li>SeedOre</li><li>MigrateOre</li></ul>|

(Only GlobalRoles are shown here, users in different scopes can have different permissions)


The simplest option would be to have a "UserAdmin" permission for all actions, and assign it to the Standard trust level, but we may want more fine-grained permissions.

**Comment by ryantheleach** [comment]
> Discord: @mbax says:

> I'd like to propose that only the Ore-related roles grant any additional Ore powers. This would avoid the situation of someone being added as a developer, realizing they can now click 'approve' on their plugin, and doing so. Or accidentally deleting something. Basically, a barrier set by additional roles needing to be granted

> Someone wants to help out? Great! Ask for it, someone talks with them about the process, makes sure they know what to do and what not to do, and role granted.



This sounds like some form of rejigging might be needed, but makes sense to me.

**Comment by progwml6** [comment]
unless you have ore specific tags you should not have any ore backend access,
