### ISSUE TITLE
Ore staging website down

### ISSUE THREAD

**Issue by JBYoshi** [SpongePowered/Ore#36]
When I go to https://ore-staging.spongepowered.org or https://ore.gratimax.net, I get redirected to www.spongepowered.org. How do I get to Ore now?

**Comment by lukegb** [comment]
This is just a thing while I sort some stuff out on the backend.

Don't worry, it'll be back "soon"!

**Comment by JBYoshi** [comment]
Thanks!

I'll leave it open for now just so people know it's already reported.

**Comment by JBYoshi** [comment]
It's no longer redirecting, but it's "taking too long to respond".

**Comment by TheDoctorsLife** [comment]
I get a redirect to https://ore-staging.spongepowered.org/ from https://ore.gratimax.net/. On the page https://ore-staging.spongepowered.org/ firefox tells me "Server not found". Further inspections reveal this,
```
benjamin@benjamin-Laptop ~ $ host ore-staging.spongepowered.org
ore-staging.spongepowered.org is an alias for _entry.spongepowered.org.
_entry.spongepowered.org has address 139.162.218.147
benjamin@benjamin-Laptop ~ $ host _entry.spongepowered.org
_entry.spongepowered.org has address 139.162.218.147
benjamin@benjamin-Laptop ~ $ host 139.162.218.147
147.218.162.139.in-addr.arpa domain name pointer li1381-147.members.linode.com.
```

**Comment by JBYoshi** [comment]
@TheDoctorsLife That redirect is intentional. https://ore.gratimax.net was the old site. I just wanted to check if it happened to work. I believe _entry.spongepowered.org uses the HTTP Host header to display the correct site.

**Comment by lukegb** [comment]
Aaaand we're back. Thanks for flying Staging Airways.

I took the opportunity to flush the DB, so anything that was previously there is now gone (!)

**Comment by gratimax** [comment]
"took the opportunity"
:wink:

**Comment by JBYoshi** [comment]
Thanks!

**Comment by TheDoctorsLife** [comment]
@JBYoshi I know, I was just stating at the time  the server was down.
