### ISSUE TITLE
Project owners should not be able to star their own projects

### ISSUE THREAD

**Issue by Zidane** [SpongePowered/Ore#36]
Hahaha...no.

Tsk @windy1 !

**Comment by Flibio** [comment]
GitHub allows it :smirk:

**Comment by kashike** [comment]
Why not?

**Comment by Zidane** [comment]
Then star the project by default. Its just stupid and because github does it isn't a valid excuse.

**Comment by Grinch** [comment]
What are the stars meant to represent? 'Watch this Ore listing', '+1', or 'Favorite'?

**Comment by windy1** [comment]
All of the above I suppose. You can currently view the projects a user has starred on their user page.

**Comment by Grinch** [comment]
Then I'd say it doesn't make sense for a user to star his own projects. Since you'd be able to see their projects already on their user profile.

**Comment by Flibio** [comment]
Maybe prevent the the project from displaying under the user's starred projects if it is their own project?

**Comment by ewized** [comment]
I do not see a big issue as other social networks let you like and heart your own posts and tweets.

**Comment by Grinch** [comment]
@ewized Ore is not a social network, so those aren't really comparable.

**Comment by ewized** [comment]
@Grinch If the stars are only to show others what you like I do not see a problem, but if the stars are used for some type of chart listing I understand.

**Comment by Grinch** [comment]
@ewized I would certainly hope you'd like your own project. :p Regardless, it just seems silly to be able to star your own in my opinion.
