### ISSUE TITLE
Error on deletion of version

### ISSUE THREAD

**Issue by parlough** [SpongePowered/Ore#361]
Browser & Version: `Chrome Canary - Version 65.0.3321.0 (Official Build) canary (64-bit)`

Operating System: `macOS High Sierra - Version 10.13.3 Beta`

Error message (if applicable): 

<img width="1101" alt="screen shot 2018-01-14 at 2 57 41 pm" src="https://user-images.githubusercontent.com/18372958/34920647-6f9e428c-f93b-11e7-8899-236c62d5f5f2.png">

The version no longer exists in my versions list though, so it seems to be successfully deleted to some extent.

Steps to reproduce:

* Go to versions on your plugin
* Pick a version(possibly only works on versions existing before file system changes)
* Click delete button

**Comment by ryantheleach** [comment]
Needed for roadmapping
- [x] Investigate depth of bug, is this leaving the database in an inconsistent state or is it just a 'cosmetic' error?

**Comment by phase** [comment]
This was an error in #333. The error is thrown when the files are being deleted, but the version is removed from the DB before that, so it _"works"_.
