### ISSUE TITLE
Cannot upload same plugin version for different API release

### ISSUE THREAD

**Issue by parlough** [SpongePowered/Ore#362]
Browser & Version: `Chrome Canary - Version 65.0.3321.0 (Official Build) canary (64-bit)`

Operating System: `macOS High Sierra - Version 10.13.3 Beta`

Error message (if applicable): I tried uploading the same plugin version for a different API release, with changes to the code to be functional, but I get the following error. I could include the API version in the plugin version, but I would rather not, and I feel it is a common use-case to release the same version for different API versions.

<img width="1145" alt="screen shot 2018-01-14 at 3 11 11 pm" src="https://user-images.githubusercontent.com/18372958/34920783-2bb831b0-f93e-11e7-9752-75f6c6c5f4db.png">

Steps to reproduce:

* Make changes to plugin for different API release
* Build and sign new jar
* Try uploading jar, even with different name (latch-0.4.5 previously and now latch-0.4.5-s5.2.0)

**Comment by parlough** [comment]
I think this was a mistake on my part due to generating my mcmod.info incorrectly. Will re-open if it still fails after that.

**Comment by parlough** [comment]
This issue actually remains, the `mcmod.info`s are different, just with the same plugin version. So it seems the point of this issue is should plugins be allowed to upload multiple of the same version, with different dependencies.

**Comment by progwml6** [comment]
version numbers are considered unique to a project currently. I would suggest putting the api version in the version string as well to get around this

**Comment by parlough** [comment]
After some discussion, it does seem unique version numbers are important, but it is clear we still need future discussion on how to best handle multiple releases for different API versions per release.
