### ISSUE TITLE
Order of members in organization is wrong

### ISSUE THREAD

**Issue by parlough** [SpongePowered/Ore#364]
Browser & Version: `Chrome Canary - Version 65.0.3321.0 (Official Build) canary (64-bit)`

Operating System: `macOS High Sierra - Version 10.13.3 Beta`

Error message (if applicable): You would expect the owner to be above the admin.

<img width="379" alt="screen shot 2018-01-14 at 4 32 36 pm" src="https://user-images.githubusercontent.com/18372958/34921500-e8f4a24a-f948-11e7-95f8-055bef68e7c6.png">

Steps to reproduce:

* Go to https://ore.spongepowered.org/IchorPowered
* Look at the organization members
* See how Vectrix as an admin is higher than Meronat as an owner

**Comment by parlough** [comment]
This issue may be related to https://github.com/SpongePowered/Ore/issues/365

**Comment by ryantheleach** [comment]
Moved to 1.7 , it might get fixed as a part of #354 but if it doesn't it isn't critical for launch.
