### ISSUE TITLE
Cannot change role of admin even if you are owner of the organization

### ISSUE THREAD

**Issue by parlough** [SpongePowered/Ore#365]
Browser & Version: `Chrome Canary - Version 65.0.3321.0 (Official Build) canary (64-bit)`

Operating System: `macOS High Sierra - Version 10.13.3 Beta`

Error message (if applicable): I cannot change Vectrix's rank/role or delete him from the organization at all even though I am the owner. At least there is no UI to do so, unlike there is for nighteyes who is only a developer.

<img width="379" alt="screen shot 2018-01-14 at 4 32 36 pm" src="https://user-images.githubusercontent.com/18372958/34921514-29a55302-f949-11e7-9be4-e2e82d30e935.png">

Steps to reproduce:

* Add an admin to your organization
* See you cannot change their role or delete them

**Comment by progwml6** [comment]
this and #364 should probably be fixed with #354
