### ISSUE TITLE
I don't need notifications when I make my own release

### ISSUE THREAD

**Issue by parlough** [SpongePowered/Ore#367]
**Problem:** When you make a release for one of your plugins and you are following the plugin you get a notification. The initial response may be to just say don't follow your own plugin, but others may also have the ability to make a release and I'd like to know about that.

A possibly solution is to just prevent it from notifying you if you were the one who authored the release or allow some configuration option somewhere.

**Steps to reproduce:**

* Follow your plugin
* Make a release
* Check your notifcations

**Comment by progwml6** [comment]
note to implementer: ensure that notifications for versions you uploaded get notified when approved by sponge staff

**Comment by Ewoutvans** [comment]
Both of these where fixed with #390 so this can be closed
