### ISSUE TITLE
New OCD Issue: Misc Style Fixes

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/Ore#371]
- [x] Hovering over the buttons in the upper right puts a white box around them except the new project button. It should be given a white background and the plus should change white. _(background on hover was removed)_
- [x] The white box around the search and authors button when you hover is square but when you hover the user icon it is rounded. _(background on hover was removed)_
- [x] I don't really think the plus and avatar buttons need an arrow next to them(look at forums for example). They are a little bit buggy and add clutter.
- [x] While editing members on an organization or project, the name, edit, and trash buttons are very close. Maybe the trash button should come after the edit button as well.
- [ ] Where it says "This project is under review...", I think it would be beneficial to link to a page which includes information about the review process, how it works, who curates it, et cetera. - @Meronat

**Comment by ryantheleach** [comment]
Can someone just review / tick each item to make sure nothing was missed?

**Comment by progwml6** [comment]
@Ewoutvans @felixoi

**Comment by felixoi** [comment]
3. Disagreeing on point 3, the caret 🥕 is good to indicate that there is a dropdown.
4. Needs to be checked
5. Should this be on docs or on ore itself?

**Comment by ryantheleach** [comment]
@Meronat 5. ?

**Comment by phase** [comment]
`#5` should probably be on the docs along with the TOS.

**Comment by Katrix** [comment]
Moved to minor issues list
