### ISSUE TITLE
Search is down?

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/Ore#376]
Search for https://ore.spongepowered.org/?q=anything
get Ore's error page.
```
Ore is experiencing difficulties.
Unexpected exception[SlickException: Read NULL value (null) for ResultSet column <computed>]
If you suspect this is a bug, please take a minute to report it to the issue tracker.
```

**Comment by ryantheleach** [comment]
@phit reports that he can not reproduce, maybe it's something to do with being Ore staff, or something session specific?

**Comment by me4502** [comment]
I get this whenever I go to the page of any plugin.

**Comment by felixoi** [comment]
I cannot reproduce this.

**Comment by Ewoutvans** [comment]
Its a problem when a flag has no comment. Flags are only loaded when you have a admin role it should be fixed it in #375 

A workaround for now is not being logged in

**Comment by phase** [comment]
When was that deployed? What version is currently deployed?

**Comment by phase** [comment]
This is good to close
