### ISSUE TITLE
Internet Exploder support?

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/Ore#378]
Browser & Version: `IE (vomit) 11.125.16299.0 (11.0.49)`

![image](https://user-images.githubusercontent.com/141554/35152982-864435ae-fd74-11e7-9283-53b9272e89e0.png)

Operating System: `Windoze`

![image](https://user-images.githubusercontent.com/141554/35152955-5d613fa6-fd74-11e7-9055-5a6a02c5f344.png)

Edge works: 

![image](https://user-images.githubusercontent.com/141554/35153002-9cfa3460-fd74-11e7-8531-06e1825a95d2.png)

I just happened to type "internet explorer" out of habit after I needed a different browser to work around a bug, and couldn't be assed using incognito mode.

This bug really should be pending checking on the amount of hits the forum / home page get on Internet Explorer.

Checking Ore for browser stats would be counter productive however, as people don't tend to use broken shit if they can help it.

**Comment by progwml6** [comment]
as long as edge works I don't think IE is worth the extra hastle at this time, as most machines w/ ie also have that installed by default

**Comment by ryantheleach** [comment]
Maybe a IE only warning saying to use Edge then? It was getting pretty messed up.

**Comment by progwml6** [comment]
we should in that case say we do not support this browser(and show it in other applicable cases when warranted). We really shouldn't be recommending specific browsers.

**Comment by mbax** [comment]
> We really shouldn't be recommending specific browsers.

What about recommending all major browsers?

```
How about you try:
Apple Safari, Google Chorme, Microsoft Edge, Mozilla Firefox, Opera
```

**Comment by codeHusky** [comment]
How about just saying something along the lines of "Use a more modern browser"

**Comment by mbax** [comment]
> How about just saying something along the lines of "Use a more modern browser"

That isn't enough information for many folks using IE ;)

**Comment by codeHusky** [comment]
We can recommend Edge to people who's browser report they're on Windows 10?

**Comment by mbax** [comment]
>We can recommend Edge to people who's browser report they're on Windows 10?

> We really shouldn't be recommending specific browsers.

**Comment by codeHusky** [comment]
It's not like I entirely agree with that, since not recommending anything specific to people who are literally using IE in 2018 might be kinda futile

**Comment by Grinch** [comment]
Wanted to chime in here.

We really shouldn't bother implementing support specifically for Internet Explorer. I know a large part of the world still uses it (to the dismay of many) but at the same point, unless I've missed something, it's pretty much in maintenance mode and only receives security updates.

Absolutely no one should be using this browser these days and if they are then that is their own problem. Simply bring them to a page that explains that Ore isn't supported on said browser and recommend using another major browser (show a list with direct links to their respective sites).

**Comment by progwml6** [comment]
lets implement Grinch's solution above. Any outdated browsers should be fed this page if they don't support necessary features for ore to function

**Comment by ryantheleach** [comment]
" Any outdated browsers " 

I'd advise blacklisting IE only, rather then trying to whitelist all the browsers we support. 

Ideally we would be switching this based on features, but I'm not sure that's going to be possible.

Trying to do this for all unsupported browsers is going to end in tears for anyone trying to machine read it, or using funky browsers like IceWeasel

**Comment by Valandur** [comment]
You can easily detect browser features with https://modernizr.com and an update message showing new browsers for your system can be done through https://browser-update.org

**Comment by progwml6** [comment]
@ryantheleach code should be configured to allow easily adding additional browsers/versions of browsers in the future if bugs are reported for things that shouldn't be supported
