### ISSUE TITLE
Using back and forth buttons on a plugin's version page removes additional info

### ISSUE THREAD

**Issue by Valandur** [SpongePowered/Ore#385]
Browser & Version: Chrome Version 64.0.3282.119

Operating System: Windows 10

Steps to reproduce:

* Go to a plugin that has enough different version for there to be multiple pages
* Click the forwards button to go to the second page of versions (notice that this page already has no information like Sponge version, and all the "dots" are black)
* Navigate back to the first page again, and notice that this page now looks like the second page looked, instead of how it looked at the beginning
* Reload the page and notice how the formatting changes again to include additional info like Sponge version

**Comment by felixoi** [comment]
This is already fixed in latest master but not pushed to production. Can be closed.
