### ISSUE TITLE
Google Authentication is broken

### ISSUE THREAD

**Issue by bloodmc** [SpongePowered/Ore#386]
Browser & Version: `Latest Chrome and Firefox`

Operating System: `Windows 10`

Error message (if applicable): `Unexpected exception[SlickException: Read NULL value (null) for ResultSet column <computed>]`

Steps to reproduce:

* Step 1 Click Login
* Step 2 Login with Google Auth
* Step 3 Get redirected to error page
Refreshing brings you back to same error.

**Comment by Ewoutvans** [comment]
This issue is "the same" as #376 
and is fixed in master but has not yet been pushed to production

**Comment by lukegb** [comment]
https://sentry.io/sponge/ore/issues/435903004/

**Comment by bloodmc** [comment]
I can confirm this is fixed. Thanks.
