### ISSUE TITLE
Advanced search/filtering support and display

### ISSUE THREAD

**Issue by progwml6** [SpongePowered/Ore#387]
Users should be able to search and filter based on Minecraft version, or API version as well as both. Other tags should be filterable as well if possible.

Large numbers of end users do not understand the concept of API versions, thus the MC versions should be displayed as well.

For Minecraft version, and API compatibility: the versions set in the mcmod.info should be the defaults, and overridden by plugin developers when needed via a UI. If the Minecraft version is not set the data should be auto populated and tagged as autopopulated via a table of api versions to MC versions that needs to be created, and updated regularly (spongedownloads has the rest of this type of info)

**Comment by phase** [comment]
#294 #321 

The structure for filtering by tags needs to get implemented first, and then we can get all the glitter in.
SpongePowered/DownloadIndexer#7 will be needed.

**Comment by phase** [comment]
Condensing to #294
