### ISSUE TITLE
Log DB/File Actions

### ISSUE THREAD

**Issue by phase** [SpongePowered/Ore#392]
Admin/mod actions should be logged. A global page for all actions and a per-user page seems like the best idea.

cc @progwml6

**Comment by progwml6** [comment]
Just to clarify: if it requires permissions to accomplish it MUST be logged this includes reviewing, editing, etc.

**Comment by phase** [comment]
Including normal user actions?

**Comment by mbax** [comment]
> Including normal user actions?

* Edit a page
* Upload a file
* Edit any properties of a file
* Edit any properties of a project

Should log at a minimum who did it, when they did it, and with what IP they did it.
