### ISSUE TITLE
Sponsor images not found

### ISSUE THREAD

**Issue by phit** [SpongePowered/Ore#393]
Browser & Version: any

Visit any page with sponsor images, the files are 404'ing

> progwml6: File an issue and tag @Felixoi he is supposed to look into it today

URL currently seems to point at 
`https://ore.spongepowered.org/assets/assets/img/sponsors/apexhosting.png`
correct path
`https://ore.spongepowered.org/assets/images/sponsors/apexhosting.png`

**Comment by phase** [comment]
I believe this to be a error with the configuration. `conf/application.conf` needs to be updated on prod with the correct urls.

**Comment by progwml6** [comment]
fixed in the prod config
