### ISSUE TITLE
Approval Queue NoSuchElementException

### ISSUE THREAD

**Issue by phase** [SpongePowered/Ore#394]
`[NoSuchElementException: None.get]`

`In /home/phase/projects/scala/Ore/app/views/users/admin/queue.scala.html:175`

```diff
171    </div>
172    <script nonce="@nonce">
173        $(function(){
174            var momentNow = moment();
-175            var maxDiffrence = @config.ore.getConfig("queue").get.getInt("max-review-time").get;
176            $('span[data-ago]').each(function() {
177                var momentAgo = moment($(this).data('ago'))
178                $(this).text($(this).data('title') + momentAgo.fromNow());
179                if (momentNow.diff(momentAgo) >= maxDiffrence) {
```

`conf/application.conf` needs to be updated on prod, _again_. This is a reoccurring theme, sadly.

This needs to be added under `ore`:

```
    queue {
        max-review-time = 86400000                  // 1 day (millis)
    }
```

**Comment by ryantheleach** [comment]
var maxDiffrence = @config.ore.getConfig("queue").get.getInt("max-review-time").getOrElse(86400000);

**Comment by phase** [comment]
Do you want to PR that or should we just force it to be in the config?
