### ISSUE TITLE
Release Channel Requirements

### ISSUE THREAD

**Issue by DrZoddiak** [SpongePowered/Ore#398]
Browser & Version: `Chrome` | `63.0.3239.132 (Official Build) (64-bit)`

Operating System: `Windows10`

Error message (if applicable): `Invalid channel name.`

Steps to reproduce:

* Input invalid tag: i.e "bad tag"
* Get awarded with error message.

I'm requesting that there show requirements for the tags. Such as "No spaces", or "No special characters" or whatever else it doesn't allow.

**Comment by Ewoutvans** [comment]
<img width="650" alt="schermafbeelding 2018-01-31 om 13 13 29" src="https://user-images.githubusercontent.com/3961526/35622641-da9b7082-0688-11e8-9b4a-ce67bc67ccb2.png">

A channel can be 15 characters long and be formatted as `[a-zA-Z0-9]`
We could add this info to the message

**Comment by mbax** [comment]
>We could add this info to the message

Please do! :)
