### ISSUE TITLE
Migrate to django

### ISSUE THREAD

**Issue by gratimax** [SpongePowered/Ore#4]
Currently the repository is written with Tornado(and momoko as a db driver), however, there are several problems that have arisen:

- Code looks like it's normal, synchronous code with a whole bunch of `@gen.coroutine` plus `yield`, making me question the purpose of asynchronicity at all.
- The ecosystem for python modules that actually use the tornado IO-loop is very small, as discovered in #1 and #2.
- As an extension to that point, file hosting would most likely have to be done using greenlets or a library that uses greenlets. Greenlets are basically like synchronous threads, making the whole IO loop pointless.
- Seeing as how the application (currently) is a standard server-side application, there's no reason to use an asynchronous framework(which are most used for REST-like services that need very quick request/response times).

The most popular other option in the python world is django, so I think I will go with that. I am unwilling to change languages as that would be too much wasted work. Any discussion is welcome.

**Comment by lukegb** [comment]
This is basically done now, we've just got to keep going :palm_tree:

**Comment by gratimax** [comment]
Officially done since 6a9617db
