### ISSUE TITLE
Duplicate Uploads

### ISSUE THREAD

**Issue by Grinch** [SpongePowered/Ore#40]
We shouldn't allow people to add new versions with files that have the same md5 as past versions.

**Comment by windy1** [comment]
This could be a nightmare for projects with a lot of releases. I'm not sure it's worth it tbh.

**Comment by Grinch** [comment]
Only if you're generating the md5 for every existing release whenever they make a new release. Simply generate one during the creation process and store it. If they remove/change a release remove or adjust as needed.

Then after it's created in the creation process just compare the one that was generated against the existing list of md5's.

Hope that made sense. :p
