### ISSUE TITLE
Add API version range to plugins

### ISSUE THREAD

**Issue by Eufranio** [SpongePowered/Ore#408]
Currently, the main page only shows one API version. This is confusing for people who don't understand the system, as they think the version displayed is the ONLY supported by the plugin. My suggestion is that plugin devs could specify a working version range, something like API5 ~ API7, that would be displayed in the main page instead a single version.

**Comment by mbax** [comment]
This feels like a part of #387

**Comment by phase** [comment]
Well, [they can do exactly that](https://ore.spongepowered.org/simon816/Chat-UI-Library/versions). They need to specify the range in their plugin metadata. Ore scans the `mcmod.info` file for the Sponge API dependency version, so you need to put it in manually if you want to specify the range.

https://github.com/simon816/ChatUI/blob/be2b3b911e996830b38c7631dcb31486d1ca8ac1/build.gradle#L72

**Comment by Valandur** [comment]
Sorry to coment on a closed issue!,  but is the plugin metadata retrieved from the newest version? Because i have to build and upload different versions of my plugin for different Sponge APIs,  so I cant really put a range in the plugin metadata, as that would be inaccurate.

**Comment by phase** [comment]
Hmm, the tags displayed on the home page are for the _recommended_ version, which you can set manually.

And always feel free to comment on a closed issue, there may be grounds to reopen this if we want to choose a different behaviour for recommended version tags.

**Comment by Valandur** [comment]
I guess this is tied to #366, because I would like to recommend, say version 34 of my plugin, without recommending a specific Sponge version, since my plugin is built against multiple Sponge versions using different jars.

**Comment by Eufranio** [comment]
Same ^
