### ISSUE TITLE
Project visibility states

### ISSUE THREAD

**Issue by mbax** [SpongePowered/Ore#413]
For non-standard project states, a notice should be displayed at the top. 

1. Public
    * Visibility: Everyone.
    * Notice: None.
    * Standard state for a project.
2. New
    * Visibility: Everyone.
    * Notice: "This project is new, and the author may not have finished writing the documentation."
      * Extra notice to anyone who can edit project pages: "This notice will expire in 24 hours. Click 'here' to remove it early."
    * Entry point: Create Project.
    * Exit point:
      * Owner clicks button in notice to publish early.
      * Automatically turned over (thanks, cron?) after one day.
3. Needs changes
    * Visibility: Staff and anyone with project page edit access.
    * Notice: "This project requires changes: [changes listed here]"
      * Extra notice to anyone who can edit project pages: "Click here to indicate you have completed these changes"
    * Entry point: Staff clicking "Needs changes" button (from queue or from project page), filling out what needs changing, and submitting.
    * Exit point: Any non-staff who can view can click a button in the notice indicating changes are done.
4. Soft deleted.
    * Visibility: Staff
    * Notice: "Project deleted by [user]: [reason]"
    * Entry point: Owner or staff click delete button, fill in reason for deletion (will show on notice), and submit.
    * Exit point: Staff clicking button to change state, choosing "needs changes" "new" or "public"

"Hide project" presently exists but would go away under this system.

**Comment by simon816** [comment]
How about a "draft" state when you first create a project.
Currently it'll go public with no information, people may want to get the project pages set up before going live.

**Comment by mbax** [comment]
That's a neat idea, @simon816 !

**Comment by mbax** [comment]
Updated main issue with modifications to be more clear, and incorporate draft.

**Comment by phase** [comment]
Should pages in the `draft` state have an Unstable tag?

**Comment by mbax** [comment]
Updated to rename 'draft' to 'new' to avoid confusion. An actual drafting process can be added 1.7.0 or later, and handled via separate ticket.

**Comment by JBYoshi** [comment]
Can this be closed since #429 is merged?

**Comment by mbax** [comment]
@JBYoshi I'm told that's only part one of the code necessary to do this. :)

**Comment by felixoi** [comment]
I think a better name for this is `project status` and not `visibility`.
