### ISSUE TITLE
Delete button should not hard delete.

### ISSUE THREAD

**Issue by mbax** [SpongePowered/Ore#414]
Project delete button should merely flip the project to the staff-only hidden state. See #413 

File delete button should do the same sort of thing.

Admins (not moderators) should have a way to hard delete things as necessary for legal reasons but otherwise this shouldn't be doable.

**Comment by ryantheleach** [comment]
I thought projects that were hidden were still viewable by the owner?

**Comment by simon816** [comment]
There's not much point keeping deleted project files around forever. I'd say a 90 day grace period before permanent deletion.

**Comment by mbax** [comment]
These are all pretty hard deletes.
https://github.com/SpongePowered/Ore/blob/f1ebd3c07adaf9a31285a78c692a43f856685d05/app/db/impl/access/ProjectBase.scala#L132-L198

**Comment by ryantheleach** [comment]
The issue I have is if projects arn't truly deleted, then that means all the constraints for unique names need to be re-evaluated or uniquified on delete.
