### ISSUE TITLE
Incorrect page names in navigation for sub items

### ISSUE THREAD

**Issue by dualspiral** [SpongePowered/Ore#417]
Browser & Version: `Firefox & Chrome`

Operating System: `Linux`

Error message (if applicable): `none`

Steps to reproduce:

* Visit https://ore.spongepowered.org/Nucleus/Nucleus/pages/Home
* Click on `Configuration` on the right hand side
* See that there are two `command.conf` entries when one should be `main.conf`
* Select one of the `command.conf` entries (or visit https://ore.spongepowered.org/Nucleus/Nucleus/pages/commands.conf)
* Notice that they are labelled correctly when a sub item is selected

On the Nucleus home page:

![home](https://user-images.githubusercontent.com/1904167/35941806-720f1bae-0c4b-11e8-8f57-a3ac67a4168a.png)

On the Nucleus command.conf page:

![conf](https://user-images.githubusercontent.com/1904167/35941805-71f338c6-0c4b-11e8-93bd-3f02b2f5ef2e.png)

**Comment by felixoi** [comment]
This has been fixed in https://github.com/SpongePowered/Ore/pull/411. Try to force reload the site because currently the javascript files are not versioned..
