### ISSUE TITLE
Alphabetize the category list in all areas

### ISSUE THREAD

**Issue by Grinch** [SpongePowered/Ore#42]
Main page, project creation, settings of a project need it. Makes it easier to look at. :p

**Comment by windy1** [comment]
They are currently sorted by relevance in my opinion. Misc shouldn't come before Protection IMHO

**Comment by Grinch** [comment]
I don't think relevance should really matter. What is more relevant to you or I may be insignificant to someone else. Alphabetizing it would just make it a generic A-Z list that is quick to look through.

**Comment by Zidane** [comment]
I think I agree with @Grinch on this one. My eyes naturally go for alphabetical and people's "tastes" differ.
