### ISSUE TITLE
As a User, I would like to see a notification badge for private messages on forum.

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/Ore#423]
I'm not sure if this is needed, but some users on the forum look at the forum very rarely, and instead just log into ore.spongepowered.org.

Having a notification for new messages on posts or pm's might be useful as Ore grows in popularity.

I'm not sure if this should only be moderator mails for Ore approvals, or if those will even use the forum at all, but I've had one incident where a pm was missed for quite a while until the user noticed it by logging into the forums.

**Comment by Katrix** [comment]
Out of scope for Ore. We want to move away from Discourse's terrible API, not closer to it.
