### ISSUE TITLE
Discuss Page Discussion and Requirements

### ISSUE THREAD

**Issue by Zidane** [SpongePowered/Ore#43]
So thinking forward to the Discuss page, following are my requirements:
- [x] Embed Discourse discussions into the project page
- [x] Create thread on forums for Ore project but un-list it. May not be desirable with the below.
- [x] @windy1 discovered that Discourse doesn't provide a "reply" box for embedded discussions. We'll need to create one for Ore's purposes
- [x] You'll get notifications on the forums for replies to the Ore thread. You can comment on the forums to that thread and those replies end up on the Ore discuss page. A good example is what Neowin does at www.neowin.net where the main site pages comments are just forum posts on a forum thread in the background. This doesn't mean you can't comment on the Ore discuss page. Just two avenues of approach.
- [ ] The generated forum post should ONLY have a link to the Ore thread. This one should be discussed further, my Neowin example puts the main post content into the forum thread OP but trims it some.

Any more thoughts or opinions? Post them here...the discuss page is a big part of Ore and a requirement before beta status.

**Comment by windy1** [comment]
So the way I have it setup now is to sync the project's "home" page with the forum post (with a link back to the project above). Thoughts?

**Comment by windy1** [comment]
Handled in https://github.com/SpongePowered/Ore/commit/d5d3e3373cb4c4e47b21e1d064a38984fdd57d14 More advanced reply box to come
