### ISSUE TITLE
Incorred Header Alignment

### ISSUE THREAD

**Issue by SimonFlash** [SpongePowered/Ore#432]
When linking to a header, the first few lines are cut off due to the Sponge navigation bar. See the gif below:

![Does anyone read these things?](https://gyazo.com/40a44baed71e4651a0ea05dd015f70b7.gif)

**Comment by ryantheleach** [comment]
What browser are you using? (possibly https://github.com/SpongePowered/Ore/issues/378)

**Comment by SimonFlash** [comment]
*Definitely* not Internet Explorer xD

The gif above was on Edge, but I just replicated with Chrome as well.

**Comment by felixoi** [comment]
Accepted.

**Comment by SimonFlash** [comment]
This is still an issue for me. Replicated on Edge (shown below), Chrome, and Internet Explorer (because I can 🌎).
![Antidisestablishmentarialism... or something like that :/](https://gyazo.com/ca8df2d0708639c65bd77eada01eb0a4.gif)
