### ISSUE TITLE
API: List users (default) entry count not limited to 25

### ISSUE THREAD

**Issue by ST-DDT** [SpongePowered/Ore#436]
Browser & Version: `Firefox Quantum 58.0.2 (64bit)`

Operating System: `Windows 10`

Steps to reproduce:

* Open https://ore.spongepowered.org/api/users

The side takes quite a while to load and then returns 1216 (all) users.
According to the [docs](https://docs.spongepowered.org/stable/en/ore/routes/list-projects.html) this list should be paginated/restricted to 25 entries per page, but all values are returned.

I assume that the API validation is wrong here.
If the Docs are wrong please fix the docs or create an issue in that repository.

I found this while looking at https://github.com/SpongePowered/SpongeDocs/issues/665.

**Comment by ST-DDT** [comment]
Is there any ETA for that change in the API?
Because the docs have already been changed in https://github.com/SpongePowered/SpongeDocs/pull/669
We need to track these changes otherwise we will forget about them.

**Comment by progwml6** [comment]
i can't give an exact ETA, however this will go out in the next few days once some of these open PR's are reviewed
