### ISSUE TITLE
Weird Ore Error

### ISSUE THREAD

**Issue by liach** [SpongePowered/Ore#44]
![oreerror](https://cloud.githubusercontent.com/assets/7806504/14402150/e7a29c6e-fddf-11e5-81a0-ac8a7bad6ea1.PNG)

This happens when I uploads a forge mod.

**Comment by windy1** [comment]
Cause: https://github.com/SpongePowered/plugin-meta/blob/master/src/main/java/org/spongepowered/plugin/meta/gson/ModMetadataAdapter.java#L83

Are you missing the "modid" field? I'll add a failsafe for this.

**Comment by liach** [comment]
https://github.com/liachmodded/UHC-Reloaded/blob/master/forge/src/main/resources/mcmod.info

Oh I see. The mod id's case issue.

**Comment by windy1** [comment]
@liach You're using `“` (U+201C) in some places instead of `"` (U+0022) in your meta file. Change them to regular quotations and see if the problem persists.
