### ISSUE TITLE
Queue "In Review" bugs

### ISSUE THREAD

**Issue by mbax** [SpongePowered/Ore#446]
* "Queued by" is presumably missing a username, or is improperly labeled and should just say "Queued"
* Stored time appears off. Might be based on difference between local user clock and Ore clock, as I am UTC-5

![image](https://user-images.githubusercontent.com/181668/36555771-faa4ba92-17d0-11e8-88bc-0aa4775ff9e2.png)

**Comment by phase** [comment]
So `Dec 31, 2016 03:58` is not when it was queued? Or are you talking about the `Status` section?

**Comment by mbax** [comment]
Status section where it says "in 5 hours"

I believe the PR linked above fixes both issues here, or at least is meant to fix them both.
