### ISSUE TITLE
Discussion: How to count project downloads and project views

### ISSUE THREAD

**Issue by felixoi** [SpongePowered/Ore#451]
Currently we are saving the client ip address as well as we set a cookie to lookup if the client viewed or downloaded a version before. This creates a database table with a huge amount of data and it doesn't make the life harder to fake views. To fix this he would have to setup a job, wich removes entries every ~20 days. This would have the side effect that the view count also increments if the user visited the project before, after the entries are deleted.

A new idea would to hold this in memory. Just use a `Set` and store ip adresses in it. Then check on a request if the `Set` doesn't contain the ip address and increment it.

**Comment by phase** [comment]
Well we need to back it up somehow. We could serialize the set of IPs & store that string/binary in the table.

**Comment by felixoi** [comment]
For what you need to back it up?

**Comment by phase** [comment]
We need to backup the view count in the DB.

**Comment by felixoi** [comment]
Adding a views column in the projects table is enough for this.

**Comment by phase** [comment]
> This would have the side effect that the view count also increments if the user visited the project before, after the entries are deleted.

If we don't want to count duplicate views, we need to store the IPs somewhere. Serializing the set would probably make it smaller.

**Comment by progwml6** [comment]
we should not be storing these IP's for long periods of time, just enough to discourage people from constantly downloading files to pad view counts, for this purpose a few days should be long enough

**Comment by felixoi** [comment]
Well, it's pretty easy to do it anyway. I think then a `Set` would be enough, because it just resets it when Ore is restarted (e.g. for deployment)

**Comment by progwml6** [comment]
if ore stays up for weeks, that list could get huge, and if we are ever able to scale out ore storing this in ram won't work either

**Comment by felixoi** [comment]
OK you got me with the scaling. We will just leave the current behaviour.
