### ISSUE TITLE
Version Channels 

### ISSUE THREAD

**Issue by OscarOrSomething** [SpongePowered/Ore#46]
Right now, There is a section below 'Create a Version' in the versions tab showing some channels but nothing in it does anything

Suggestions:

  - Allow Selection of channels when creating a version
  - Allow editing channels
  - Allow filtering by channels
  - Allow setting default channels by user/org?
  - Allow email notifications by channel?

**Comment by OscarOrSomething** [comment]
About halfway through a PR for this.

**Comment by OscarOrSomething** [comment]
Made PR: pr#47

**Comment by gratimax** [comment]
Fixed in #47. Awesome work @OscarOrSomething! :tropical_drink:
