### ISSUE TITLE
Restrict image width

### ISSUE THREAD

**Issue by Flibio** [SpongePowered/Ore#46]
Image width can get a little out of hand when viewing a project. See an example [here](https://ore-staging.spongepowered.org/Flibio/EconomyLite/pages/Home)

**Comment by 12awsomeman34** [comment]
@windy1 
![](http://i.imgur.com/Q488M6O.png)
My image is cut in half and is far too great in height (compared to exact same image on forums).

**Comment by windy1** [comment]
Thanks fixed in c155759cb89aaf92e0dd9feb80d3c30d135ec872
