### ISSUE TITLE
Ore logo does not look sharp

### ISSUE THREAD

**Issue by bloodmc** [SpongePowered/Ore#476]
Ore logo needs to be fixed as it is not clear.

https://ore.spongepowered.org/assets/images/ore-desc.png

**Comment by phase** [comment]
We've got:

[![i](https://raw.githubusercontent.com/SpongePowered/Ore/master/public/images/ore-dark.png)](https://github.com/SpongePowered/Ore/blob/master/public/images/ore-dark.png)

which needs to be an SVG, and we can use it with some HTML to replace the logo on the front page.

**Comment by bloodmc** [comment]
That looks far better. We also need to fix the text beside the logo "A Minecraft package repository".

**Comment by felixoi** [comment]
We can just add the text with HTML and style it

**Comment by bloodmc** [comment]
Sure, whatever works.

**Comment by phit** [comment]
I took some time to redraw the whole logo in Photoshop with paths, so they cleanly export as SVG and to Illustrator.

Colored with background https://phit.link/s/ore-colored.svg
Colored without background https://phit.link/s/ore-colored-nobg.svg
White without background https://phit.link/s/ore-white-nobg.svg
Black without background https://phit.link/s/ore-black-nobg.svg

Sources: https://phit.link/s/ore.psd https://phit.link/s/ore.ai
