### ISSUE TITLE
My avatar is missing...?

### ISSUE THREAD

**Issue by JBYoshi** [SpongePowered/Ore#48]
On the [Sponge forums](https://forums.spongepowered.org/users/jbyoshi/), my avatar shows my Minecraft skin (same as my GitHub avatar, but round). On [Ore](https://ore-staging.spongepowered.org/JBYoshi), it uses the default Gravatar icon. Could someone fix this?

It seems to happen with other Ore accounts as well, but not all. I'm not sure what the cause is.

**Comment by Zidane** [comment]
Check open issues before creating new ones...

**Comment by JBYoshi** [comment]
Sorry. Didn't see #41.
