### ISSUE TITLE
Add sync_sso

### ISSUE THREAD

**Issue by Ewoutvans** [SpongePowered/Ore#483]
Add sync_sso.
sync_sso is a url endpoint in Discourse (forum) to update user accounts (username, email...).
We need this feature so if name changes get added in the feature they are automatically handled by Ore.

[More info](https://meta.discourse.org/t/official-single-sign-on-for-discourse-sso/13045#heading--syncronize_records)

**Comment by phase** [comment]
What is this and what does it do?
