### ISSUE TITLE
Activity log link to file review info puts the ID in the URL instead of the name

### ISSUE THREAD

**Issue by mbax** [SpongePowered/Ore#486]
e.g. `https://ore.spongepowered.org/mbaxter/Spectastic/versions/1/reviews` instead of `https://ore.spongepowered.org/mbaxter/Spectastic/versions/1.1.0/reviews`

**Comment by phase** [comment]
I believe this has been fixed. The links are working on https://ore.spongepowered.org/mbaxter/Spectastic/versions/1.2.0
