### ISSUE TITLE
Secret-Key

### ISSUE THREAD

**Issue by randombyte-developer** [SpongePowered/Ore#49]
Just this:
https://github.com/SpongePowered/Ore/blob/d525dda78ec0e732ac6b8d408bae2aafb2238ea3/ore/settings/base.py#L37
https://docs.djangoproject.com/en/1.9/ref/settings/#std:setting-SECRET_KEY

**Comment by lukegb** [comment]
https://github.com/SpongePowered/Ore/blob/d525dda78ec0e732ac6b8d408bae2aafb2238ea3/ore/settings/production.py#L5
