### ISSUE TITLE
TOS Acceptance

### ISSUE THREAD

**Issue by mbax** [SpongePowered/Ore#491]
1. Track in DB which users have accepted the TOS. 
2. Prompt all new accounts to accept TOS.
3. Prompt all returning accounts to accept TOS prior to continuing actions.

**Comment by JBYoshi** [comment]
Maybe also track which version of the TOS a user accepted and then prompt them again when it changes?

**Comment by felixoi** [comment]
Implemented in auth.

**Comment by progwml6** [comment]
The upload apis need to have tos checks added

**Comment by phase** [comment]
Closed with https://github.com/SpongePowered/SpongeAuth/pull/186
