### ISSUE TITLE
Mark all projects owned by people who didn't accept the TOS as "Changes Required"

### ISSUE THREAD

**Issue by mbax** [SpongePowered/Ore#492]
To be pulled in a while after #491 :

Mark as changes required with reason "Pending TOS acceptance" any default state or new state projects owned by anyone who hasn't accepted the TOS. And preferably to then revert to default state those projects on acceptance.

**Comment by progwml6** [comment]
this setting must bar anyone from performing authenticated actions unless the TOS acceptance flag is enabled in auth, including through the API'S

**Comment by phase** [comment]
Closed with https://github.com/SpongePowered/SpongeAuth/pull/186

**Comment by mbax** [comment]
How did a change to SpongeAuth mark all projects owned by people who didn't accept the TOS as changes required?

**Comment by phase** [comment]
my b

So we just want to set all projects to a state of "Pending TOS acceptance" if they haven't accepted it on Auth?

**Comment by felixoi** [comment]
@mbax can you please state why you need these projects marked?

**Comment by Katrix** [comment]
Should be done
