### ISSUE TITLE
Support for reporting/flagging a project

### ISSUE THREAD

**Issue by Grinch** [SpongePowered/Ore#495]
Need to add a button somewhere that is clearly visible to let us report or flag a project.

**Comment by progwml6** [comment]
for clarification, this should allow end users to report a project, when the button is clicked they should be promped to explain why they are flagging it for moderation staff to review

**Comment by Ewoutvans** [comment]
Already existing, you can only see the 'Flag' button if you are not a member of the project yourself
when clicking it it opens the following modal:
<img width="613" alt="schermafbeelding 2018-03-09 om 21 05 39" src="https://user-images.githubusercontent.com/3961526/37227479-ae85131e-23dd-11e8-9dfe-75f01bacce29.png">

**Comment by mbax** [comment]
And if you're a member of the project but being not the owner don't have access to all things, and you see a problem on the project that you can't fix? ;)

**Comment by Ewoutvans** [comment]
I checked it again, everybody can flag a project except the project owner. (members can flag)
