### ISSUE TITLE
Multiple PGP keys per user

### ISSUE THREAD

**Issue by dualspiral** [SpongePowered/Ore#497]
Would it be feasible to add multiple PGP keys to a user? I'd like to use oreDeploy to push CI builds from my CI server to my project, but I do not want to use my own PGP key to sign those builds because I don't want my private key on that server, just in case I do something really stupid on there and accidentally expose it. That way I can still create releases and just revoke my CI key if I need to.

This should, of course, be subject to the three day rule, and the user should be notified though e-mail that a key was added.

**Comment by progwml6** [comment]
If a user adds multiple keys, the keys will need names for display purposes

**Comment by ryantheleach** [comment]
If this code is going to be refactored, I recommend associating keys with a user or organization.

Keys on shared jenkins services that multiple devs have potential access to should be marked as such by belonging to a shared organization between them.
