### ISSUE TITLE
Permissions system

### ISSUE THREAD

**Issue by gratimax** [SpongePowered/Ore#5]
Ore will have a permissions system, similar to Github's or DevBukkit's except it will provide more granular support for how permissions actually work.

## List of Permissions

There are no nested permission groups, the nesting imposed on the following list is simply how permissions will appear in forms.

- version.*
    - version.create
    - version.edit
    - version.delete
- file.*
    - file.create
    - file.edit
    - file.delete
- project.*
    - project.edit
    - project.transfer
    - project.delete
- project.team.* (managing project-specific teams)
    - project.team.create
    - project.team.edit (name, description)
    - project.team.manage (manage team members)
    - project.team.delete

### Organization-Only permissions

- project.*
    - project.create
- org.team.* (managing organization teams)
    - org.team.create
    - org.team.edit (name, description)
    - org.team.manage (manage team members)
    - org.team.delete

## Permissions model

Users can have teams, on Organizations or on projects themselves.

A user implicitly has the “owner” role on a project underneath them. This cannot be removed, except by transferring the project to someone else.

This system is, technically, more flexible than the github one in that permissions are assigned separately, i.e. instead of Read/Write/Admin, you can assign individual permissions (like change_description, etc.).

```python
Permission:
	slug - SlugField
	name - CharField
	description - TextField
	applies_to_organization - BooleanField

Team:
	name - CharField
	description - TextField
	users - ManyToMany to RepoUser
	permissions - ManyToMany to Permission
	is_owner_team - Boolean (owner group flag)

	(is_abstract)

ProjectTeam(Team):
	project - ForeignKeyField(Project)
	
OrganizationTeam(Team):
	organization - ForeignKeyField(Project)
	projects - ManyToMany to Project (we need to be careful with making sure this only refers to projects in the Organization)
	is_all_projects - Boolean
```

### Permissions-checking algorithm

1. take project, check if user has any matching ProjectTeams
    1. for each matching ProjectTeam:
        1. does the ProjectTeam have is_owner_team set
        2 does the ProjectTeam have that permission?

2. take project’s namespace - is it an Organization?
    1. if so, check if user has any matching OrganizationTeams (i.e. Organization=Organization, project is in Organization#projects or is_all_projects is set)
    1. for each matching OrganizationTeam:
        1. does the OrganizationTeam have is_owner_team set
        2. does the OrganizationTeam grant that permission?

Big thanks to @lukegb, as well as @Jake0oo0 for their work so far on the permissions system

**Comment by lukegb** [comment]
ae44e5efacc443ad69cd89f7ef9a5a69acb44ae0 was a first draft at team management for projects

**Comment by lukegb** [comment]
I'm going to close this for now, because I'm pretty happy with where we're at in terms of the underlying permissions model.

This will need work in #15.
