### ISSUE TITLE
[WIP] API Specification

### ISSUE THREAD

**Issue by windy1** [SpongePowered/Ore#5]
This Issue is to work on defining the API specification for Ore API v1 either in the main Ore implementation or in Pore. Pinging @lukegb

---
#### `GET /api/projects/`

``` json
[
    {
        "id": "<project_id>",
        "name": "<project_name>",
        "description": "<project_description>",
        "owner": "<project_owner>",
        "developers": [ "Spongie", "Dev1", "Dev2", "Dev3" ],
        "teams": [ "SpongePowered", "Team1" ],
        "channels": [ "Alpha", "Beta", "Release" ],
        "recommended": "<download_link>"
    }
    ...
]
```

---
#### `GET /api/users/:user/`

``` json
{
    "name": "<user_name>",
    "type": "<dev|team>",
    "starred": "<starred>",
    "teams": [ "SpongePowered", "Team1", "Team2", "Team3" ],
    "projects": [ "Plugin1", "Plugin2", "Plugin3" ]
}
```

---
#### `GET /api/projects/:owner/:name/`

``` json
{
    "id": "<project_id>",
    "name": "<project_name>",
    "description": "<project_description>",
    "owner": "<project_owner>",
    "developers": [ "Spongie", "User1" ],
    "teams": [ "SpongePowered", "Team1" ],
    "channels": [ "Alpha", "Beta", "Release" ],
    "recommended": "<download_ref>"
}
```

---
#### `GET /api/projects/:owner/:name/channels/:channel/`

``` json
[
    {
        "version": "1.0.0",
        "description": "<version_description>",
        "url": "<download_ref>"
    }
    ...
]
```

---

More...

**Comment by lukegb** [comment]
I'd sooner have references to other things in the API, or nested sub-objects than just sticking strings and disjointed download URLs in things.

I mean, I'm OK with having, e.g.

``` json
"recommended": "/projects/:owner/:name/releases/:version",
"recommended_primary": "/projects/:owner/:name/releases/:version/:filename",
```

keys on projects.

Channels should probably be under `/projects/:owner/:name/channels/:channel` rather than dangling directly off the project.

**Comment by windy1** [comment]
@lukegb Agreed, I think nesting channels in the list view runs this risk of becoming to verbose so I think references might be best there but nesting could probably be good for the detailed view.

**Comment by lukegb** [comment]
I guess our nomenclature is going to diverge regarding the key naming, since you're using `dev` and `team`, and I guess we'll use `org` and `user`, and in Ore land we don't currently have any way of flagging which devs are associated with a project (besides just dumping everyone on a team associated with it, but they might easily only have rights to edit the wiki and not be considered devs, etc.)

**Comment by lukegb** [comment]
`/projects/:author` should probably not return user information, that's silly. That should live somewhere else - either under `/users/:author` or under `/authors/:author` (or in my world `/namespaces/:author`)

**Comment by lukegb** [comment]
This should probably get written up in Swagger or something nice and consistent so that we can just autogenerate API clients (hooray)

**Comment by kashike** [comment]
I think it would be a good idea to version all versions of the API: `/api/v1/projects/:owner/:name/`, etc

**Comment by windy1** [comment]
@kashike Already implemented see `controllers/Api`

**Comment by windy1** [comment]
Closing this as it's wildly out to date. I'll probably write up a more complete spec later.

**Comment by liach** [comment]
@windy1 Are those api info here up-to-date still?

**Comment by windy1** [comment]
No that's why I closed it. I'll write a proper spec when I can but for now here's a list of all the API routes.

https://github.com/SpongePowered/Ore/blob/master/conf/routes#L12-L29

Note that "Ore API v1" is not released yet so I'll probably be making changes to those.
