### ISSUE TITLE
Discussion threads are going into wrong spot on Forums

### ISSUE THREAD

**Issue by Zidane** [SpongePowered/Ore#50]
@windy1 

We have: https://forums.spongepowered.org/c/plugins/ore
and: https://forums.spongepowered.org/c/plugins/ore-topics

You're putting the projects into the latter area. I'd just have @Owexz to remove everything in the ore section and you put your stuff in there. Obviously this isn't the final area these would go.

**Comment by windy1** [comment]
Yeah I saw that. I made a new category because I couldn't figure out how to delete all the topics in one go.

**Comment by Zidane** [comment]
Apologies for non staff who can't see the above, we'll open it up soon.

**Comment by windy1** [comment]
@Zidane Any opposition to opening up the category?

**Comment by Zidane** [comment]
@windy1 

Category is now open to the public.
