### ISSUE TITLE
Version page <title> is "Issues"

### ISSUE THREAD

**Issue by JBYoshi** [SpongePowered/Ore#50]
https://github.com/SpongePowered/Ore/blob/d87784ead806dab28a49896b62a331588626b2ba/ore/versions/templates/versions/list.html#L4

**Comment by lukegb** [comment]
I DON'T SEE THE `Issues` WITH THIS

**Comment by JBYoshi** [comment]
> I DON'T SEE THE `Issues` WITH THIS

*like*
