### ISSUE TITLE
Organization name issues

### ISSUE THREAD

**Issue by Dockter** [SpongePowered/Ore#504]
General questions/concerns about Organizations:
* can't rename an existing organizations.
* can't name an organization > 20 characters.  Trying to create "Almura Development Studios" for @Zidane and I to start posting our projects.

**Comment by phase** [comment]
1. #350

2. Organization _names_ are the _slugs_ that will be in the URL, just like on GitHub. _Display names_ are not implemented. If this is a requested feature, it can be added, but for now you can only choose the slug once.

**Comment by phase** [comment]
& #341

**Comment by phase** [comment]
I'm going to close this since these issues are already in separate issues (#350 & #341).
