### ISSUE TITLE
Member since on user page doesn't use forums join date?

### ISSUE THREAD

**Issue by Zidane** [SpongePowered/Ore#51]
@windy1 

This isn't an issue but more a question. Do we want the date joined to be your join date of the forums or the join date you first logged into Ore?

**Comment by Grinch** [comment]
Personally I think we need a 1:1 match for the user profile on Ore and the forums. You're not making an account with a website, you're making an account with a platform. You joined the **community** on xx-xx-xxxx date.

**Comment by Zidane** [comment]
Good point @Grinch
