### ISSUE TITLE
Increase page size limit on non-home Ore pages

### ISSUE THREAD

**Issue by dualspiral** [SpongePowered/Ore#515]
In order to make Nucleus compliant with the Ore guidelines, I need to be able to add my configuration files. However, they are larger than the current limit (of what I believe) is 32kB). My configuration files that I would want to add to Ore are my `main.conf`, currently ~53kB and my `commands.conf`, currently ~61kB. (I've also had to contract my commands and permissions pages to make it fit, though in all fairness, those changes aren't negative for me and in the long run would be surpassed by #422.)

Keeping the 32kB limit makes sense for any page that is mirrored to Discourse due to the forum post size limit. However, for other doc pages the limit is possibly arbitary and prevents me from fulfilling the guidelines. Is it possible to raise the limit?

**Comment by progwml6** [comment]
it is possible, and who ever implements this should raise to 70kb for anything but the main post that is synced to discord
