### ISSUE TITLE
Discussion threads are only visible to the Sponge team

### ISSUE THREAD

**Issue by Flibio** [SpongePowered/Ore#52]
It appears that the discussion threads are only available to the Sponge team. Ore gets a 403 Forbidden error whenever trying to load them for me. I'm not sure if this is intended or not.

**Comment by Zidane** [comment]
@Flibio 

Its cause the Ore Topics section is hidden on the forums currently. We'll expose it soon.

**Comment by windy1** [comment]
Closing this as it's not so much an issue but rather a side-effect of being in pre-beta.
