### ISSUE TITLE
Missing data in API vs website

### ISSUE THREAD

**Issue by Cherry** [SpongePowered/Ore#525]
It seems that the json API is returning outdated data than that listed on the website.

For example:

https://ore.spongepowered.org/Nucleus/Nucleus/versions - there's a version released April 2nd, and April 12th, but...

https://ore.spongepowered.org/api/v1/projects/Nucleus/versions - the latest listed version was released on September 10th.

Is this something I'm misunderstanding with the API perhaps, or is the data not available?

**Comment by Katrix** [comment]
Seems to be that the offset defaults to an arbitrary value of 25. This should work https://ore.spongepowered.org/api/v1/projects/Nucleus/versions?offset=0.

Here is the line causing the issue.
https://github.com/SpongePowered/Ore/blob/master/app/ore/rest/OreRestfulApi.scala#L249

**Comment by Cherry** [comment]
Thanks. It seems like there's a few other cases in this file where the offset defaults to 25. Is this something we can expect a fix for soon, or should I throw in a PR? 😄

**Comment by felixoi** [comment]
PR's are always appreciated 🏆
