### ISSUE TITLE
BungeeCord Plugin support

### ISSUE THREAD

**Issue by phit** [SpongePowered/Ore#527]
Came up when talking about [SpongePls](https://forums.spongepowered.org/t/spongepls-bungeecord-forge-support/9891).
Ore support to parse Bungee plugins would be a nice addition in the future.
They should be fairly easy to detect as they all have a text file named `bungee.yml` in the jar root. 

e.g.
```
name: 'SpongePls'
main: 'co.ryred.spongepls.SpongePlsPlugin'
author: 'Cory Redmond'
description: 'SpongePls allows IPForwarding to sponge servers.'
version: '1.1-SNAPSHOT-b#35'
```

**Comment by simon816** [comment]
To me this seems out of scope for Ore.
If you're looking for bungeecord plugins then you visit the bungeecord plugin list (https://www.spigotmc.org/resources/categories/bungee-proxy.3/)
Also I'm not sure we would want this to be mixed with other plugins/mods on Ore, e.g. what is the plugin ID? What happens when there's a bungeecord plugin of the same name as a sponge plugin?
Should they conform to the guidelines, would the review process be the same?

**Comment by phase** [comment]
I think for now we want to focus our attention on mods for our API, Sponge, and later down the road, if there are a large number of people wanting to host on our platform, we can add support for other types of mods. This and #510 can be scheduled for a v2.2.0 or v3.0 release (maybe v3.0 can focus on specifically hosting other mods?).

**Comment by progwml6** [comment]
Forge mod support can come with plugins, they are handled nearly identically

**Comment by ryantheleach** [comment]
Should they conform to the guidelines, would the review process be the same?

Yes. Yes.

>What happens when there's a bungeecord plugin of the same name as a sponge plugin?

If they are related, then the same way that we currently bundle multiple artifacts under one brand/name?

If unrelated, it would have to follow the same way we already defined how to handle name collisions.

I don't see it as any different to a Forge mod or Sponge plugin, People are interested in having Sponge ecosystem specific proxy plugins that are compatible with Bungee, They need a place to promote them. The Spigot/Bungee Community is largely hostile against Sponge users, so why shouldn't we allow the **authors** of Bungee plugins that wish to host on our services the ability to do so, if they work well or complement our platform?

It's a no brainer to me to allow it, as long as it follows all previously set out guidelines.

**Comment by phase** [comment]
This might come sooner than expected. Support for this would not be difficult to add, and I am absolutely open to having other platforms hosted on Ore.

**Comment by ryantheleach** [comment]
I'd also like to consider adding [Velocity ](https://www.velocitypowered.com/) support then. I suspect they might be after a plugin repository to host their plugins shortly.

**Comment by phase** [comment]
@ryantheleach I've made that its own ticket.

**Comment by Katrix** [comment]
We have decided that for now, Ore will focus on the platforms we touch directly. As such I am closing this issue. People reading this are welcome to submit a PR to add the appropriate plugin loader to Ore, but even if they do, we will not enable it in our instance of Ore.
