### ISSUE TITLE
Allow viewing all 'stargazers' for a project

### ISSUE THREAD

**Issue by Aaron1011** [SpongePowered/Ore#534]
By viewing a user's Ore profile, it's possible to see all of the projects that they have starred. However, the inverse is not possible - there's no way to see all of the users who have starred a given project.

It would be nice if Ore had something similar to GitHub's [stargazers](https://github.com/SpongePowered/Ore/stargazers) page, where you can easily view all of the users who have starred a given project.

**Comment by Ewoutvans** [comment]
I would like to place this in the "stats". Adding it to the stats has the added benefit that non-logged in users can see the star count.

Mock-up
![schermafbeelding 2018-07-17 om 17 39 50](https://user-images.githubusercontent.com/3961526/42828181-70cb3636-89e8-11e8-872f-3fa44304abc4.png)
