### ISSUE TITLE
Back button at warning page doesn't work

### ISSUE THREAD

**Issue by XakepSDK** [SpongePowered/Ore#535]
Browser & Version: Mozilla/5.0 (X11; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0
Operating System: Arch Linux
Steps to reproduce:
* Go to plugin downloads page
* Find unchecked plugin
* Press download
* Warning page opens, back button doesn't work

**Comment by felixoi** [comment]
Fixed in master already.
