### ISSUE TITLE
Fully logging out of Ore is difficult

### ISSUE THREAD

**Issue by Aaron1011** [SpongePowered/Ore#538]
On Ore, a user can 'sign out' by clicking on their profile picture, and selecting `Sign Out` from the dropdown. However, this only signs the user out of Ore, not SpongeAuth - clicking the `Log In` button will immediately log the user back into Ore.

To fully sign sign out, the user needs to visit `auth.spongepowered.org`. Unfortunately, there is currently no direct link to this page - users must either know the domain name, or follow this convoluted process:

1. Visit their profile page on Ore.
2. Click the small 'Settings' cog on their profile page.
3. Click the SpongePowered logo in the header (**not** any of the dropdown items)
4. Click the `Log Out` button on the 'Sponge Authentication Portal' page.

Strictly speaking, this is not a security vulnerability. However, it is at best extremely annoying (if a user wants to let someone else sign in to Ore on the same computer), and at worst, may result in a user accidentally remaining logged in to Ore on a public computer.

One option would be to change the default behavior of Ore's `Log Out` button to log a user out of SpongeAuth. An additional button could be added for users wishing to retain the old behavior. However, the difference between the two should be clearly explained.

**Comment by JBYoshi** [comment]
Is there any case when someone would want to log out of Ore without logging out of SpongeAuth? If not, we can just replace that behavior completely.

**Comment by phase** [comment]
The logout button should probably just redirect to SpongeAuth.
