### ISSUE TITLE
Uploading a project and then deleting it prevents you from re-uploading a project with the same name.

### ISSUE THREAD

**Issue by HDR** [SpongePowered/Ore#540]
Browser & Version: `Chrome 66.0.3359.139`

Operating System: `Windows 10 Pro 64 Bit`

Error message (if applicable): `Ore/Sponge is experiencing issues`

Steps to reproduce:

* Step 1: Upload a project.
* Step 2: Delete it.
* Step 3: Re-upload a project with the same name.

Instead of re-uploading a new project it will try to update the old project that no longer exists.

**Comment by felixoi** [comment]
This is intended behavior to secure our users. Please message our staff if you need to recreate the project.

**Comment by ryantheleach** [comment]
@felixoi Can we replace the error message?
