### ISSUE TITLE
Show raw URL for Sources/Issues

### ISSUE THREAD

**Issue by Grinch** [SpongePowered/Ore#55]
Right now we mask it with our own URL. To allow the end-user to know what he/she is trying to go to we should show the raw URL instead of the masked one.

That or have a page in-between that says "You are leaving Ore... etc.".

**Comment by humaidq** [comment]
I think you should do the "You are leaving Ore" redirect page, then we can judge on that or remove it if people did not like it.  
Docker Hub uses GitHub (pretty much similar to Ore), but they don't include a link to the GitHub page. But I like it having the GitHub link, it gives people more freedom and not limiting them to Ore.

**Comment by Grinch** [comment]
@hmksq I think that would work fine. This lets people visually see the URL they're about to be directed to and if they feel it's malicious or suspicious (eg. links to a https://totallynotavirus.com/notavirus.exe) then they can click cancel and flag it.

**Comment by windy1** [comment]
Tbh i think its already pretty clear that the link takes you away from ore with the external link icon. I would like to keep the redirects in place so you can find a projects source for any given name. Maybe just add some hover text to the link with the real url?

**Comment by kashike** [comment]
So keep the redirect link ability? Just don't use the redirect in hrefs?
