### ISSUE TITLE
Can‘t login to the ore after change username

### ISSUE THREAD

**Issue by Tollainmear** [SpongePowered/Ore#552]
Browser & Version: `chrome`

Operating System: `win10`

Error message (if applicable): 
![qq 20180609223142](https://user-images.githubusercontent.com/25898067/41192762-5e2c2e66-6c35-11e8-9be0-c28619cd65c8.jpg)

Steps to reproduce:

* it's about a week days ago, I asked @lukegb to help me to change my username
* lukegb helped me to change my username soon
* I wan't to update a new version of my plugin today, but I meet this problem

BTW, if I changed my username, should I also change my PGP public key?

**Comment by Tollainmear** [comment]
Hi~ Help me plz, my plugin has a update needed to release qwq

**Comment by felixoi** [comment]
Hey can you tell us your ore username?

**Comment by Tollainmear** [comment]
the author in ore is still `Larsson_Tyrants`.

@felixoi 

I use `Larsson_Tyrants` for the past, and after lukegb's help, the username has change to `Tollainmear`.

**Comment by felixoi** [comment]
Can you retry please?

**Comment by Tollainmear** [comment]
@felixoi With a great Thanks that it was solved!

**Comment by Tollainmear** [comment]
<del>BTW after changing user name, should I regenerate the GPG public key?

and may I ask for you to changing the title of this [page](https://ore.spongepowered.org/Larsson_Tyrants/KaroglanSignEditor)(and link to https://ore.spongepowered.org/Tollainmear/KaroglanSignEditor)? 😅 That is the only one project I released on ore, so no more request would be draw.

if that was not supported would be also fine, because I don't want to give too much trouble.... if that is complex, I'll recreate it ;)

**Comment by Tollainmear** [comment]
Hi sorry to bother you again @felixoi 

I meet a new issue now, I can't use gpg before generated, and now I changed it and system let me wait about 3 days at least to upload new version....Can you help me to pass this limitation?

**Comment by phase** [comment]
I believe this is a security measure that we won't bypass for any users.

**Comment by felixoi** [comment]
@Tollainmear Sorry.. We are running into some errors after the rename we have not expected. We try to fix it up as fast as possible.

**Comment by Tollainmear** [comment]
Thanks for your help, plz take your time ❤️

**Comment by felixoi** [comment]
Reopened as reminder

**Comment by felixoi** [comment]
Project link is fixed now.
