### ISSUE TITLE
Easier review with external trusted building

### ISSUE THREAD

**Issue by randombyte-developer** [SpongePowered/Ore#553]
If the plugin developer decided to release the source of the plugin, then it would definitely be easier if the staff reviews the code instead of the decompiled source. The only problem is that the compiled jar and the source can differ. I suggest using 'external build systems'.

My only experience with such building systems is with [jitpack.io](https://www.jitpack.io). JitPack just executes the gradle `build` task and provides the created artifacts in a maven repo. A build is identified with its tag or commit hash.

I guess instead of uploading a jar to Ore, you pick a build from a trusted build service. For reviewing the code, the build's code can then be obtained from the source code hoster.

**Comment by Aaron1011** [comment]
@randombyte-developer: Something like this could work even in the absence of a trusted build source.

We can make a simple tool to build a repository locally, and compare the built jar to the submitted jar. Any jar entries that differ are displayed to the user for review. If the jars are identical (excluding things like signatures in META-INF), the user is free to review the source (and build script) from their IDE.

This could be made part of the [MinecraftDev plugin](https://github.com/minecraft-dev/MinecraftDev), which would allow easy side-by-side comparisons of the actual and decompiled source in the case where the two jars differ.

**Comment by mbax** [comment]
Too many ways to modify through build script/config, dependencies, etc!

**Comment by phase** [comment]
Sounds highly unsafe unless we compile the source ourselves, which isn't going to happen. I'm going to deny this feature considering the billion ways the system could be cheated.
