### ISSUE TITLE
Add a back button or Ore logo to the header

### ISSUE THREAD

**Issue by StealWonders** [SpongePowered/Ore#555]
When viewing a plugin the ore logo isn't there so you get all confused how to get back to the main page. 
Something like this should always be the header at top for easier navigation :)

![](https://i.gyazo.com/abfb39c2c65f29f126832fb4780ce133.png)

**Comment by StealWonders** [comment]
Here's a quick photoshop example of what I mean :)
Just needs to be made a bit better so it fits.
![example](https://user-images.githubusercontent.com/6114858/41819895-e8873666-77c8-11e8-9348-66dfe706389d.png)

**Comment by Ewoutvans** [comment]
You can click the sponge logo in the top navbar to go back.
[edit: the text “sponge” brings you back]

**Comment by StealWonders** [comment]
I know that by now but that seems very weird hence why I am suggesting this.

**Comment by mbax** [comment]
> You can click the sponge logo in the top navbar to go back.

Which is odd when you also hover over that to get a drop-down menu of options. Feels a bit odd. Would love more input.

**Comment by phase** [comment]
Clicking on the Ore logo/text should take you to the home page.

**Comment by felixoi** [comment]
I'm understanding your problem with the design inconsistency. We could have a look adding the ore banner to every page but definitely without the search bar. 

The hover and clickable sponge icon in the navigation is more complex because that's the navigation and workflow which is being used on every spongepowered website.

**Comment by Katrix** [comment]
Isn't this a problem with the banner itself though, and as such apply to all sponge sites? If so then shouldn't the banner itself be fixed instead of shoehorning in a really large second header?

**Comment by felixoi** [comment]
Discussed by devs, this will not happen. Sorry.

**Comment by mbax** [comment]
To be clear, we still want to improve the interface, just won't be doing this exact approach.
