### ISSUE TITLE
Remove ORMish DB code and replace it with something better

### ISSUE THREAD

**Issue by Katrix** [SpongePowered/Ore#556]
Creating this issue to gather discussion on the current state of the DB code in Ore, and possible improvements to it.

As I see it, the problems with the current code for handling the DB stuff are
1. Uses projection types, which won't be around forever, and they also work poorly with IntelliJ
2. Mutable case classes
3. "Fake" Option id values
4. Very tight coupling between the models and the DB
5. Class objects everywhere
6. Many parts are dynamic and can fail at runtime
7. Encourages too much code reuse instead of writing new/better queries

I think the best approach would be to move the majority of the DB accessors and similar to typeclasses which use dependent types instead. These typeclasses should be the only way to get or create the models. That would solve 1, 2, 4, 5 and 6, and partially solve 3. For the rest of 3, let's just create an `ObjectId` type which has a single public value outside the db package, which is `value`. It will act like Option and on the inside, but that should not be exposed to the outside as such a value should never escape to the outside.

Sadly I don't currently have any pseudocode to show, but if anyone is interested I can probably write some up.

Note that solving this issue would take a lot of code changes and should be done incrementally. For example, ObjectId is probably a nice place to start and should be its own PR.

**Comment by Katrix** [comment]
So, I've had some time to think of how to solve this issue, so I'll ramble down here a bit showing some code, and my current plans. If anyone has any better ideas or disagree with my thoughts, feel free to say so.

First, let's talk about the amount of code reuse that's currently happening. My proposed solution is that we need some type `Q[A]` which lets us do operations like filtering and sorting as chained methods. The type should not do anything unless it's interpreted. Luckily for us, Slick already has something like that called `Query`. The majority of methods on ModelAccess and friends should be removed or changed to return `Query` as you might want to do something else on the query they use afterward.

While we're at it, we should probably move from `Future` to `DBIO` in some cases. Do note however that `DBIO` always executes sequentially. 

Next, let's talk about the DB models, how to insert update and all that.

First of, the model type.
```scala
case class Model[A](
  id: ObjectId[A],
  createdAt: ObjectTimestamp,
  value: A
)
```

Here the model's value, and it's DB properties are correctly separated. While we probably won't get completely there, the value should know as little as possible about the DB.

`ObjectReference` and `ObjectId` also take a type parameter describing what type they reference. These will probably be aliased to avoid boilerplate.

`Channel` would, for example, look like this
```scala
case class Channel(
  projectId: ProjectId, //ProjectId is an alias for ObjectReference[Project]
  name: String,
  color: Color,
  isNonReviewed: Boolean
)
```

Lastly, let look at creating, updating and deleting models.
```scala
trait DAO[A] {
  def insert(value: A): DBIO[Model[A]]

  def get(id: ObjectReference[A]): OptionT[DBIO, Model[A]]

  def update(id: ObjectReference[A], value: A): DBIO[Unit] //Not sure what would be the best to return here
  def update(model: Model[A]): DBIO[Unit] = update(model.id.value, model.value)

  def delete(id: ObjectReference[A]): DBIO[Unit] //Not sure what would be the best to return here
  def delete(model: Model[A]): DBIO[Unit] = delete(model.id.value)
}
```

Hopefully not too many surprises here. I would like to point out insert though. As `Model` is only something returned from the DB, we do not use it when inserting a new value. If we make the constructor private we shouldn't be able to construct a model instance even if we wanted to.

Also note that there is only a single update method (at least for now, might change later). While updating only the changed fields are a nice idea, it doesn't help much when in most cases more than one field is updated at once, and multiple DB requests are fired off at the same time that each update a different column.

**Comment by NeumimTo** [comment]
Currently the code-wise cleanest and simplest solution, in the java world, how to handle your db queries is to combine JPA, its implementation which is almost always Hibernate, and Spring Data 

http://projects.spring.io/spring-data/

SpringData sccessfully abstracts away almost all db queries (be it native sql, or hibernate's hql) developer has to write. 


I cannot read those alien scala runes but lets have an example in plain java. 

    @Entity
    @Table("user")
    public class User {
         @Id @GeneratedValue Long userId;

         private String userName;
        ...
    @Repository
    public interface UserRepository extends JpaRepository<Long, User> {

             Optional<User> findByUserName(String userName);

**Comment by Katrix** [comment]
While it might be clean and wonderful in Java, in Scala it would be seen as dirty magic code.  From the example above there are also many points it doesn't address. Hard to differentiate between data that comes from the DB, and data that was created in code, it's not immutable, there are magic annotations everywhere, lastly, there is a very tight coupling between the db and the model.

My current plan for this is to just throw away most of the abstractions I don't really see us needing, not replacing them with other stuff.
