### ISSUE TITLE
Perform more validation and return errors

### ISSUE THREAD

**Issue by Katrix** [SpongePowered/Ore#557]
Currently, we do lot's of validation, but it's not always that we return errors that describe why a user got kicked out somewhere in the loop. Most of this work should be done after #517 has been merged. Once that has been merged, we should review all usages of OptionT that escape into the controllers, and convert them to EitherT. From stuff which already uses EitherT, we should make sure the reason the left is chosen is evident. If we're feeling fancy, we should also try to return more than one error message to a user if more than one is applicable.

**Comment by dualspiral** [comment]
It depends on what errors you mean. If they are user input validation errors, or errors where the user has made a bad (but could be legitimate) request, yes, I agree, error messages should be displayed.

However, the web developer training in me screams "no, don't show errors". In a production environment, whenever Ore encounters an error, particularly of a 5xx or 403 kind, then we should log, but not display the errors. For example, the error where files were in the wrong place should never have been displayed to end users, we just completly open up what we expect the file system to look like. 

OWASP have a good page on errors: https://www.owasp.org/index.php/Improper_Error_Handling

**Comment by Katrix** [comment]
For the most part for this, I'm talking about rather benign errors. For example, if a channel was moved from reviewed to non-reviewed if a user is about to download something in that channel they are sent back to the version list with no explanation. Another example which spurred this is if any download confirmation fails, then no message is shown, for example, if the confirmation expired, or they already downloaded the version.
