### ISSUE TITLE
Creating a new project resets to beginning after "invite members" page

### ISSUE THREAD

**Issue by parlough** [SpongePowered/Ore#558]
Browser & Version: Chrome Canary - Version 69.0.3481.0 (Official Build) canary (64-bit)

Operating System: macOS High Sierra - Version 10.13.6 Beta and Windows 10 Build 17692

Error message (if applicable): While I am uploading a new project, after the invite members page, I get sent to the beginning of project creation again.

From here:
<img width="1493" alt="screen shot 2018-07-04 at 8 09 21 pm" src="https://user-images.githubusercontent.com/18372958/42297651-93f24e6e-7fc6-11e8-9d6f-5f45cb9f9fdf.png">
To here:
<img width="1473" alt="screen shot 2018-07-04 at 8 09 31 pm" src="https://user-images.githubusercontent.com/18372958/42297653-9585b72a-7fc6-11e8-9ea9-d77fc253d28e.png">

Steps to reproduce:

* Go to create a project
* Upload jar and sig
* Fill up necessary information(I chose IchorPowered as owner)
* Go to add member page(either add somebody or don't and click next)

The project I was trying to upload is here - https://github.com/ichorpowered/eggers/tree/v0.1.0

**Comment by Ewoutvans** [comment]
Can confirm that this is an issue; also takes ages to load for some reason

As you can see the members also shows my private account as owner, this should be the Organization.
Demo:
![kapture 2018-07-17 at 19 20 37](https://user-images.githubusercontent.com/3961526/42834155-923d1c04-89f6-11e8-9e9f-398baa1860e1.gif)

**Comment by Ewoutvans** [comment]
After long time debugging I managed to figure out that the moment you press the button, https://github.com/SpongePowered/Ore/blob/c661b29b8e6e48709d2992333f49fea8da32849c/app/controllers/project/Projects.scala#L193
gets called but. For some reason the factory still thinks is under the key `username/slug` (username being the one who is logged in) and not `organization/slug`
