### ISSUE TITLE
Use nicer 404 page for top-level URLs

### ISSUE THREAD

**Issue by Aaron1011** [SpongePowered/Ore#559]
Browser & Version: `Chromium 67.0.3396.87`

Operating System: `Arch Linux`

Steps to reproduce:

1. Visit https://ore.spongepowered.org/Nucleus/this_is_a_fake_project. `Nuclues` is a real organization, but `this_is_a_fake_project` is not a real project.
2. Note that a nice 404 error page is displayed. 
3. Visit https://ore.spongepowered.org/this_is_a_fake_url
4. Note that a completely empty page is rendered, with only a `404` code set in the HTTP response to indicate that the page is missing.

**Comment by Katrix** [comment]
Hm, that's weird. The code is all there from what I can see. Maybe it's not getting picked up?

**Comment by simon816** [comment]
Anything that doesn't use the `views.html.errors.notFound()` view will not display a nice 404.
We need to go through a search for `NotFound` and check it uses the view: https://github.com/SpongePowered/Ore/search?q=NotFound&unscoped_q=NotFound

Anything extending `OreBaseController` should use the `notFound` function

**Comment by Katrix** [comment]
Typically yes, but the ones not intended for users should be left alone.

**Comment by Aaron1011** [comment]
This appears to be fixed on `ore.spongepowered.org`
