### ISSUE TITLE
Unable to upload different plugin IDs

### ISSUE THREAD

**Issue by dags-** [SpongePowered/Ore#56]
Currently, Ore prevents you from uploading artefacts with a different plugin id to the one originally used to create the project:
![screen shot 2016-04-13 at 20 13 33](https://cloud.githubusercontent.com/assets/4276064/14506154/55b15cb8-01b4-11e6-8ec4-34221216ba5d.png)

Could there instead just be a warning that the user has to acknowledge before uploading?
This'd allow intentional changes - Ore allows projects to be renamed, so a user may want to change their plugin ID to suit, for example.

**Comment by windy1** [comment]
No this is intentional. It is important that every version within a project has the same plugin ID. This will become clear once the API is more complete / package manager plugin is created.

**Comment by kashike** [comment]
It doesn't make sense, at all, to require a completely new project (lose stars, download counts, discussions, etc) just because someone can't change their plugin ID to match their project.

**Comment by liach** [comment]
And there is also some changes on plugin naming conventions in the future.

**Comment by windy1** [comment]
@kashike @liach @dags- The reason for this is because in the future Ore will be used to automatically resolve plugin dependencies through a Sponge plugin "package manager". If this is to work every version in any given project _must_ have consistent plugin IDs.

**Comment by kashike** [comment]
@windy1 It's still unreasonable to require developers to create a new project if they wish to rename their entire project (plugin ID included) - that's like saying you must create a new GitHub repository if you want to rename your repository. :tired_face:

**Comment by windy1** [comment]
Sorry this is the way it has to be. I'll add a notice to project creation about how a Project's plugin ID is final and cannot be changed. (Also you can still rename your project, just not the plugin ID)

**Comment by liach** [comment]
So @windy1 Will there be another way to checkout qualified plugin id by group in the future?

**Comment by windy1** [comment]
@liach Well qualified plugin IDs are no longer a thing but maven deployment from Ore is something that is planned.

**Comment by windy1** [comment]
@liach Note: you can already get a json view of projects using the plugin id

https://ore-staging.spongepowered.org/api/project?pluginId=bookotd

**Comment by dags-** [comment]
Would it be possible for Ore to migrate projects to a new ID maybe? - internally create a new project based on a new ID, transfer everything over apart from the old uploads/versions, then remove the original.

I'd imagine that's essentially what a user would otherwise have to do manually, but lose all their project stats/discussion thread?/metadata/etc in the process
