### ISSUE TITLE
Add `Copy URL` option to download buttons

### ISSUE THREAD

**Issue by Grinch** [SpongePowered/Ore#566]
Discussed it a bit with mbaxter but would be nice to see something like the image below put in to place. Essentially if you clicked either it would proceed with the respective action. If the file isn't reviewed yet then bring them to the typical page but change the action of the download button to do a copy to clipboard function.

![mockup_1](https://user-images.githubusercontent.com/963480/42729602-d26a633c-87a2-11e8-995f-170c1ca9aa35.png)

**Comment by phase** [comment]
I think a dropdown would be unintuitive and makes the user click twice to download (no including the "confirm to download unrecommended"). Maybe some text near the button?

**Comment by Ewoutvans** [comment]
I think a [Split button dropdown](https://getbootstrap.com/docs/3.3/components/#btn-dropdowns-split) would be better for this.

**Comment by phase** [comment]
I didn't know Bootstrap had that but that is a great idea!
