### ISSUE TITLE
Allow fuzzy searching

### ISSUE THREAD

**Issue by Aaron1011** [SpongePowered/Ore#567]
Currently, [Ore uses the SQL 'like' operator when performing searches using the homepage searchbar](https://github.com/SpongePowered/Ore/blob/892948092a778629911078e1618899a6b3396868/app/controllers/Application.scala#L115-L118). It would be nice if Ore performed a 'fuzzy' search, checking for similar matches instead of exact (substring) matches. Since Ore currently requires PostgreSQL, this could be done through a module like [pg_trm](https://www.postgresql.org/docs/9.1/static/pgtrgm.html)

**Comment by Katrix** [comment]
Resolved by #735
