### ISSUE TITLE
Setup project redirects back to Upload project if project owner is set to be organization

### ISSUE THREAD

**Issue by HaedHutner** [SpongePowered/Ore#568]
Browser & Version: `Google Chrome | 67.0.3396.99 (Official Build) (64-bit) (cohort: Stable)`

Operating System: `Windows 7 64-bit`

Error message (if applicable): `N/A`

Steps to reproduce:

* Start creation of new project on ore
* Select and upload signed plugin jar
* On the `Setup project` stage, change `Owner` from the default ( which is the user ), to an organization
* Fill out rest of form appropriately
* Click `Continue` at the bottom
* It brings you back to the `Upload project` stage

**Comment by phase** [comment]
The project was also a deleted project that the user was trying to recreate.
