### ISSUE TITLE
Intent to implement: Discourse commenting

### ISSUE THREAD

**Issue by lukegb** [SpongePowered/Ore#57]
In order to just get this show on the road, I intend to just implement Discourse comments as the commenting system (probably under a new tab). The thread author will magically create a new thread in the Ore forum, which otherwise will not be possible, and the contents of the main page will automatically be sent into the topic.

This will probably be OK in the short term (TM)

**Comment by gratimax** [comment]
:+1: I was going to do something like this in a 'Discussion' tab, sounds good!
