### ISSUE TITLE
Ore plugin icon does not update after uploading a new image or when reset

### ISSUE THREAD

**Issue by AuroraLS3** [SpongePowered/Ore#585]
* Browser: `Mozilla Firefox`

   * Installed add-ons:
     * Privacy Badger
     * uBlock Origin
     * Facebook Container
  * Disabling add-ons had no effect.

* Operating System: `Windows 10`

* Error message (if applicable): 
This error appears on dev tools console after uploading an image
`
XML Parsing Error: no root element found
Location: https://ore.spongepowered.org/Rsl1122/Plan/icon
Line Number 1, Column 1:
`

* Page link: `https://ore.spongepowered.org/Rsl1122/Plan/manage`

* Steps to reproduce:

    * Open Ore resource's Settings page
    * Click 'upload' under 'Icon' and upload a new icon
    * Upload a new image
    * POST request returns 200, but the icon is not updated

* Other notes
  * Reset button does not work either - Returns 403 Forbidden

**Comment by AuroraLS3** [comment]
The icon did not update because I did not save changes

**Comment by Ewoutvans** [comment]
when upload is successful we need to give feedback to users to 'save changes'

**Comment by Ewoutvans** [comment]
![kapture 2018-07-27 at 22 16 32](https://user-images.githubusercontent.com/3961526/43353470-3dc66d78-923a-11e8-8e37-4435dc2c144b.gif)
added an alert. this is now on master.
