### ISSUE TITLE
Jar is removed after re-selecting 'Select file'

### ISSUE THREAD

**Issue by 12awsomeman34** [SpongePowered/Ore#59]
After selecting a jar file for my project, then selecting 'Select file' once again and clicking cancel (perhaps realizing that I do wish to upload the first jar I initially selected) the first chosen jar is removed and I have to re-select it from 'Select file'.

Really just a minor inconvenience, but hopefully something that shouldn't be too difficult to resolve.

**Comment by windy1** [comment]
This appears to be impossible to fix. The issue is present only on Chrome and occurs because the browser clears the file input when "cancel" is clicked in the dialog, something we cannot control.
