### ISSUE TITLE
Selectively improved response to incorrect signature upload

### ISSUE THREAD

**Issue by mbax** [SpongePowered/Ore#590]
Proposing responses in these special cases:

* Public key uploaded instead: Re-explain they need to sign it, direct to documentation (which is great).
* Private key uploaded instead: Mark key as compromised, disallow further use by any user?

**Comment by phase** [comment]
If we're not storing an accidental private key upload and we're not exposing it to other users would it be compromised?

**Comment by mbax** [comment]
I'd argue that the moment you pass your private key to anyone or anything it should be considered no longer usable. Even if what you passed it to (Ore) doesn't store it long term. They don't know that for sure, so maybe the assumption shouldn't be made? 

Just an idea, not mandate. Looking for discussion.

**Comment by phase** [comment]
A message such as

```
Hey, that's a private key! You need to upload a public key!
(If you're uploading your private key willy-nilly, it has probably been compromised, and we
would recommend if you generated a new one)
```

would probably do.

**Comment by ryantheleach** [comment]
> Hey, that's a private key! You need to upload a ${ExpectedUploadType}!
> (Private keys must be kept private. Only you should have access. You shouldn't ever share it to Anyone, including Ore. You must generate a new private key, if you have shared it with anyone accidentally)

Just don't make the silly mistake of asking them for a public key on the **signature** upload :P

**IF** you want to be forgiving, and I'm not sure we should be, the language used definitely should **not** be forgiving. We should just silently let them try again, letting it be their own decision.

**Comment by dualspiral** [comment]
I am strongly in favour of invalidating a private key that is uploaded.

I don't think we should be forgiving at all and we should invalidate the key **and blacklist its fingerprint so it cannot be reused**.

If someone uploads their private key, it's no longer private. @mbax is right - they don't know what we store. What if there is a vulnerability in ore that we didn't see that allows an attacker to syphon off the key as it is uploaded? We don't know what network they may be running on, they may be subject to a man in the middle attack on some dodgy network at some internet café or something.

A private key should be private. As soon as you transmit it, it is not private, no matter what the other end does with it.

@ryantheleach is right, the language needs to be strong. However, when it comes to identity and trust, we most definitely should _not_ let them try again if we consider the trust to be broken. If we go down this route, we need to make it abundantly clear what is going on, what is bad, why it's bad, where to go from here - something like (as a suggestion):

---
**You just uploaded your private key.** By providing your private key to someone, **they can impersonate you, signing their plugins with your signature**. Your signature should be unique to you. **You should NEVER provide your private key to anyone.**

As you have shared your private key, **we can no longer trust that anything signed using this key has come from you.** Therefore, we have blacklisted your PGP key and **we will reject any plugin signed with this key**.

Please generate a new PGP key and _upload your new **public key** here_.

For a tutorial on signing your plugins and submitting them to Ore, _please visit this page on the docs_.

**Comment by ryantheleach** [comment]
So, assuming that dual's suggestion is what we are going to do , Security > UX.

From a dev perspective, can we effectively calculate the public key from the private key, and validate it against all keys?

Wouldn't this then be that we **are** storing the key temporarily, in order to calculate the public key?

I'd rather not touch it at all, or restrict the file uploader somehow to the correct type in the first place. So it never touches the browser. I think there's a point where alienating users from a platform with security, is worse then bad security. But I also understand the severity of the issue, (But arn't most keys password protected anyway).

>**we will reject any plugin signed with this key.**

Future plugins? or existing plugins too?

**Comment by lucko** [comment]
> I'd rather not touch it at all, or restrict the file uploader somehow to the correct type in the first place

Only accept files that end in `.pub`?

**Comment by mbax** [comment]
> Only accept files that end in .pub?

File extensions are meaningless, though. :(

Also, I created this issue thinking about signature uploads, where different methods/tutorialscan end in multiple extensions being the output. `.sig` and `.asc` come to mind.

**Comment by lucko** [comment]
> File extensions are meaningless, though. :(

I didn't mean as an alternative to invalidating uploaded private keys - more just to prevent it from happening in the first place.

Private keys tend to have no extension at all - e.g. just `id_rsa`, but I don't think it's possible to exclude.

> thinking about signature uploads

Could whitelist common signature extensions too? Idk, it was just an idea. :p

**Comment by lol768** [comment]
> I'd rather not touch it at all, or restrict the file uploader somehow to the correct type in the first place

You can totally check this on the client - `FileReader`+ look for `-----BEGIN PGP PRIVATE KEY BLOCK-----` or the absence of `-----BEGIN PGP PUBLIC KEY BLOCK-----` and refuse to upload/send to the server if the user screwed it up.

Of course, we can debate if the user should assume the JS compromised and thus also assume their key compromised afterwards.. but it feels a bit imposing to 'punish' the user by assuming this and blacklisting the key.
