### ISSUE TITLE
Text Wrapping

### ISSUE THREAD

**Issue by thegarfish** [SpongePowered/Ore#6]
Links such as this (http://ore.dev.gratimax.net/brappo/WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW) do not properly text wrap in their titles nor descriptions.

**Comment by gratimax** [comment]
We've reduced the size of most names to at most 32 characters in order to circumvent this problem(you don't really need a name that's this long anyway).
