### ISSUE TITLE
Confirm sync operates as expected

### ISSUE THREAD

**Issue by mbax** [SpongePowered/Ore#604]
Please modify this ticket to be a 1.6.0 showstopper and close it when we have confirmed that:

When Ore and Auth are both online:
* Staff role addition is synchronized within a minute.
* Staff role removal is synchronized within a minute.
* Ore handles any response Auth sends at it properly, without exception thrown.

When Ore is offline and Auth is online:
* Auth holds on to role changes and synchronizes within a minute of Ore coming back.

When Ore throws an error at Auth about role synchronization despite our best attempts above:
* Auth or Ore (or both) send angry, urgent messages to people who can promptly resolve this.

**Comment by felixoi** [comment]
Move it to auth please. It's not an ore issue. Ore provided the endpoint and auth has send to it correctly.

**Comment by mbax** [comment]
Requesting reopen of this issue, because it has been demonstrated that auth instantly sends info to Ore but Ore does not immediately (or even within the hour) update said information.

**Comment by felixoi** [comment]
I don't have to reopen this because we fixed it in the already merged PR https://github.com/SpongePowered/Ore/pull/620.
