### ISSUE TITLE
Project owner / staff ability to transfer project ownership to another member / organization

### ISSUE THREAD

**Issue by mbax** [SpongePowered/Ore#613]

**Comment by phase** [comment]
I think only the owner of a project can change the owner, and since the owner of the project is actually the Organization, we need to check if the user editing A) has admin rights on the site and B) is an owner/admin of the organization that owns the project.

Related to #399

**Comment by phase** [comment]
https://github.com/SpongePowered/Ore/blob/8c31847a5d15939757d24abe818c95abd5978166/app/views/users/memberList.scala.html#L106

**Comment by dualspiral** [comment]
I think this might be the same as https://github.com/SpongePowered/Ore/issues/260

**Comment by kinggoesgaming** [comment]
> I think this might be the same as #260

yes indeed it is. I will leave this up to the team to mark as dup and close
