### ISSUE TITLE
Bug:  Cannot edit channel assigned to file after initial update

### ISSUE THREAD

**Issue by Dockter** [SpongePowered/Ore#615]
Issue:  once you upload a file to Ore you cannot change its assigned channel.

**Comment by phase** [comment]
Is there a use case to make it mutable? You can select it when uploading a plugin.

**Comment by Katrix** [comment]
Created a release candidate/unstable build, and later decided to make that the release after testing for example.

**Comment by phase** [comment]
Ah that's a good one.
