### ISSUE TITLE
Bug: cannot re-upload resource with same name

### ISSUE THREAD

**Issue by Dockter** [SpongePowered/Ore#617]
If you upload a resource and have an issue with it (example, can't change channel name....) and you delete it, you cannot re-upload the file.

**Comment by felixoi** [comment]
This is wanted behavior since @mbax wants them to not hard delete.

**Comment by Dockter** [comment]
What is the reasoning behind this decision?

**Comment by kashike** [comment]
> You download a plugin, version 3.0, and find that it works great! It's a fabulous plugin. But, it has this one annoying bug. The developer, without you knowing, deleted 3.0 from the site and uploaded a new 3.0 a few hours later. You keep checking the project page for an update, because you know other people must be experiencing this bug. However, it's still 3.0!  Bah! You delete the plugin, disappointed. Meanwhile, other folks are enjoying it just fine because they grabbed the fixed one. You notice this on a friend's server, and start to go insane.

**Comment by Dockter** [comment]
OK, so this is a two fold issue.

1. Argument won on the above fact of static versioning and the our usage of maven.
2. It SHOULD allow for uploading of the same version number if the MD5Hash is the same, however this is a moot point if we have the ability to edit PLATFORM and CHANNEL which created the issue to begin with.

**Comment by phase** [comment]
> It SHOULD allow for uploading of the same version number if the MD5Hash is the same

I'm failing to see what you want to do. You want to reupload a jar that has the same version and has as another? Isn't it already there?

**Comment by Katrix** [comment]
Not something we'll ever do
