### ISSUE TITLE
Can't submit my project

### ISSUE THREAD

**Issue by MichaelFedora** [SpongePowered/Ore#62]
I have no idea what's going on, but I tried a couple times. It has worked before, in earlier versions though. Here is the info from the last time I did try:

url: `https://ore-staging.spongepowered.org/new/MichaelFedora/Fedora's-Economy/members`

```
Oops, an error occurred
This exception has been logged with id 6pn3li09n.
```

Maybe the webpage was never created? I dunno. (It might also be my ``` in Fedora's messing it up, though I am not sure.

**Comment by windy1** [comment]
Log out and log back in.

**Comment by MichaelFedora** [comment]
I did, it's still persisting.

```
Oops, an error occurred
This exception has been logged with id 6pn3okfpg.
```

**Comment by windy1** [comment]
Can you post your mcmod.info file please?

**Comment by MichaelFedora** [comment]
```
[
    {
        "modid": "io.github.michaelfedora.fedoraseconomy",
        "name": "Fedora's Economy",
        "version": "1.0",
        "description": "An Economy plugin that implements the Economy API.",
        "authorList": [
            "Michael Fedora"
        ]
    }
]
```

(yes I fixed the redundant `Economy` in a later to-be-released build .-. )

**Comment by windy1** [comment]
Thanks for bringing this to my attention.
