### ISSUE TITLE
Edit documentation button overlap with navbar

### ISSUE THREAD

**Issue by ItsDoot** [SpongePowered/Ore#627]
* Browser: `Google Chrome`

* Operating System: `Windows 10`

* Error message (if applicable): `N/A`

* Page link: `https://ore.spongepowered.org/DotDash/Solace` - though should affect any project page.

* Steps to reproduce:

    * Step 1: Click `Edit` to edit the documentation of a project.
    * Step 2: Expand the text area downwards to be longer than the screen height.
    * Step 3: Scroll to where the `Edit` button is in the same Y position as the navbar, to see it and the other buttons overlap the navbar.

![image](https://user-images.githubusercontent.com/9044780/44011341-a4a4059c-9e7d-11e8-84ec-c48b0d1bde1d.png)

**Comment by felixoi** [comment]
I'm going to fix this in https://github.com/SpongePowered/Ore/pull/622.

**Comment by Katrix** [comment]
Moved to minor issues list
