### ISSUE TITLE
The project nav bar is not aligned properly anymore.

### ISSUE THREAD

**Issue by humaidq** [SpongePowered/Ore#63]
I noticed that the project nav bar is not align properly, it was aligned correctly before. This shows clearly on a UHD screen.  
http://i.imgur.com/4OFWUCc.png (Firefox full screen, 3840 x 2160)  
This does not look intentional.

**Comment by windy1** [comment]
Hmm this is likely a result of some resizing I did to make sure everything can fit even with long names / all tabs and buttons visible but this doesn't seem right.
