### ISSUE TITLE
Version flag for "never to be reviewed"

### ISSUE THREAD

**Issue by mbax** [SpongePowered/Ore#633]
Special marking primarily aimed at old plugins that we aren't going to review. Removes plugin from approval queue. Still needs to be possible to manually approve it though, so can we keep the start review button on its individual version page? :)

**Comment by ryantheleach** [comment]
Do we explicitly want this? or should it just relegate to to the bottom of the queue, 'below the fold' so to speak. So should we ever run out of plugins to review, they eventually get seen?

**Comment by mbax** [comment]
Some files will not see approval. Basically this is a way to tag files as not showing up in the queue just like files in channels marked as not reviewed.
