### ISSUE TITLE
Hotkeys

### ISSUE THREAD

**Issue by gabizou** [SpongePowered/Ore#64]
Some proposed hotkeys that we could provide:

`F` : Search Ore
`A` : All plugins (main page)
`C` : Create new project
`O` : List organizations
`M` : Members

Just some thoughts of what would be cool for some "power user" features added in Ore.

**Comment by kashike** [comment]
would `H` be better for "home"/"main page"?

**Comment by windy1** [comment]
My only reservation is changing the page on a hotkey. That could get annoying real fast. Using "tab" for changing tabs in a project would be cool though.

**Comment by gabizou** [comment]
> My only reservation is changing the page on a hotkey. That could get annoying real fast. Using "tab" for changing tabs in a project would be cool though.

The thing is, I can imagine that as there are hotkeys to reply by selection on github, and there's hotkeys on Discourse, Ore should have hotkeys.

If anything, the hotkeys are purely suggestive and generally don't interfere with the usability of the website.

**Comment by windy1** [comment]
Yeah I think probably keys that navigate away from a page should be a combination of at least two keys to prevent accidents.

**Comment by ryantheleach** [comment]
Do not attempt to use `<tab>` to change tabs. `<tab>` has a role already to change focus from different elements and could harm accessibility.

**Comment by windy1** [comment]
Good point @ryantheleach, changed to `shift + tab`.

**Comment by gabizou** [comment]
> Good point @ryantheleach, changed to shift + tab.

Shift + Tab is to navigate to the previous element in most browsers as well ;)

How about simply `T` instead?

**Comment by windy1** [comment]
Changed again :P (to `T`)
