### ISSUE TITLE
Allow experimental build channels to be hidden on the versions tab by default 

### ISSUE THREAD

**Issue by dualspiral** [SpongePowered/Ore#656]
In the not too distant future, I would like to be able to automatically deploy Nucleus from my CI server to Ore to enable users to test my builds. However, I wouldn't want them to be immediately visible if someone browsed the versions list.

I'd like to see the ability to mark a channel as "experimental" that can only be revealed by clicking on a "show experimental builds" button somewhere.

Not a high priority, but I think it would be nice to have this if possible.

**Comment by phase** [comment]
We could have some channels be filtered off by default

**Comment by Katrix** [comment]
Can we just use the existing unstable property of versions for this? Maybe rename it if needed.

**Comment by phase** [comment]
Not showing unstable builds by default could be neat, but if a plugin had only unstable builds (Guardian for example) then we should probably show them. A check box above the channel filter would be clean.

**Comment by Katrix** [comment]
Of no one is opposed to it, we'll hide broken, unsupported and bleeding versions by default
