### ISSUE TITLE
Why Django?

### ISSUE THREAD

**Issue by 20zinnm** [SpongePowered/Ore#68]
I just want to know what Django has to offer that makes it advantageous to, say, Meteor, MEAN, Ruby on Rails, etc., before I invest my time into learning it so I can contribute.

**Comment by RobertHerhold** [comment]
Well, I'm not sure there's much of a case for switching to any of these... I'm sure any of them would be suitable, although I can't speak for Ruby on Rails (never used it before). I assumed it was a matter of preference between lukegb and gratimax.

**Comment by lukegb** [comment]
Mostly a matter of preference, to be honest. It's not particularly better than any of the other stacks you mentioned, but not particularly worse either. All of them have their own strengths - Rails has a strong ecosystem, Meteor's got Livequery, etc. going for it.

Well, except MEAN, but then I'm biased against MongoDB :o)

**Comment by 20zinnm** [comment]
If you’re bias against Mongo then how can you like Meteor?
