### ISSUE TITLE
Attempt to create a new plugin under an org results in inconsistent state

### ISSUE THREAD

**Issue by dualspiral** [SpongePowered/Ore#681]
I attempted to create a new plugin under the Nucleus namespace, Heisenberg. During the project creation, I set that the owner of the plugin should be the Nucleus org, which I own. I expected that the plugin would be created, and that I would be able to alter the documentation and upload new version as required.

However, this has not happened, instead, I've ended up with a plugin in a very weird state:

* The plugin can be seen under the org page at https://ore.spongepowered.org/Nucleus
* The plugin exists in the `dualspiral` namespace (see https://ore.spongepowered.org/dualspiral/Nucleus-Heisenberg)
* I have no editing or upload rights, as I am not listed as an owner of the plugin

I would expect that the plugin would be under the `Nucleus` namespace and that as the owner of the Nucleus org, I would inherit the permissions from the org with regards to this project unless otherwise specified.

This is using the latest version of Ore as of the time of writing, 7th Oct 2018 (which might be 1.6.14, but I'm not sure if there has been a deploy of this version)

**Comment by Hbeau** [comment]
I meet the same issue. I've uploaded a plugin with an organization as owner and I can't edit the doc.
