### ISSUE TITLE
Can't edit organisation avatar

### ISSUE THREAD

**Issue by Hbeau** [SpongePowered/Ore#685]
* Browser: `Firefox`,`Google Chrome`

* Operating System: `Windows 10`

* Error message (if applicable): ``

* Page link: `https://ore.spongepowered.org/<organisationName>`

* Steps to reproduce:

    * Log in your account
    * Create an organisation
    * Click on avatar or "Edit avatar"

When you click on edit avatar for your organisation, nothing happened.

**Comment by felixoi** [comment]
Duplicate of https://github.com/SpongePowered/Ore/issues/344
