### ISSUE TITLE
Pagination issue

### ISSUE THREAD

**Issue by XakepSDK** [SpongePowered/Ore#689]
* Browser: `Firefox 62.0.3`

* Operating System: `Arch Linux`

* Page link: `https://ore.spongepowered.org/?categories=1&page=1`

* Steps to reproduce:

    * Open page
    * Press next page button
    * Next page - empty page

**Comment by Ewoutvans** [comment]
This is strange
Left safari, right Firefox
![schermafbeelding 2018-10-15 om 12 41 06](https://user-images.githubusercontent.com/3961526/46946352-b9b2f980-d077-11e8-94cf-4a32a1e6061d.png)

Next page:
![schermafbeelding 2018-10-15 om 12 41 15](https://user-images.githubusercontent.com/3961526/46946360-be77ad80-d077-11e8-9ccc-f923e03c96eb.png)


As you can see the last one in firefox is on the wrong page

**Comment by Katrix** [comment]
Seems to be fixed in master
