### ISSUE TITLE
Get an error message when publish a plugin

### ISSUE THREAD

**Issue by Hbeau** [SpongePowered/Ore#693]
* Browser: `Firefox`

* Operating System: `Windows 10`

* Error message (if applicable): `Ore is experiencing difficulties.`

* Page link: https://ore.spongepowered.org/Onaple/Itemizer---Custom-Items/versions/1.2.0`

* Steps to reproduce:

    * publish a plugin

![image](https://user-images.githubusercontent.com/18046299/47255609-34af5200-d474-11e8-9d7e-7a28137f9aa0.png)

**Comment by mbax** [comment]
@raiponz Is your plugin's version really 1.2.0\`  with the fun character \` at the end? Check your version info in the `@Plugin` annotation and the mcmod.info inside the compiled jar.

**Comment by mbax** [comment]
Wait a minute. This is the project you authorized us to delete due to the fixed bug. Sorry, I forgot for a minute. Is this the result of trying to recreate the entire project, or was it still inexplicably visible to you and you just tried to upload a new version to it?

**Comment by Hbeau** [comment]
The ` it's a result of the copy paste , you can ignore it. And it's a try of recreation of the project.

**Comment by felixoi** [comment]
I don't know what you did but something went wrong while you uploaded the version. The version was never uploaded and because we require at least one version it errors out every time. I requested the deletion of the project again. We apologize and apologize for the inconvenience. If you run in trouble again while recreating please reopen this.

**Comment by TheBrokenDown** [comment]
I have the same problem.
 * Browser: ```Chrome```
 * Operating System: ```Win 10```
 * Error message (if applicable): ```Ore is experiencing difficulties.```
 * Page link: https://ore.spongepowered.org/TheBrokenDown/PlayTimeCounter/versions/1.1
 * Steps to reproduce: 
    * upload a new version of plugin
    * delete it
    * edit something in file (i added a dot in one class)
    * reupload it
