### ISSUE TITLE
Platform change pagination issue

### ISSUE THREAD

**Issue by XakepSDK** [SpongePowered/Ore#694]
* Browser: `Firefox 62.0.3`

* Operating System: `Arch Linux`

* Steps to reproduce:

    * Open Ore
    * Go to last page (12 atm)
    * Change platform to `Forge Mods`
    * Now you can press back button 11 times until items appear

**Comment by XakepSDK** [comment]
Also: non-forge mod appears
https://puu.sh/BOAnx/57cc4ed116.png

**Comment by Katrix** [comment]
Fixed by #773
