### ISSUE TITLE
Ore main page not refreshed

### ISSUE THREAD

**Issue by Yeregorix** [SpongePowered/Ore#699]
* Browser: `Google Chrome, Microsoft Edge`

* Operating System: `Windows 10`

* Page link: `https://ore.spongepowered.org/`, `https://ore.spongepowered.org/?sort=4`

As I speak, 7 plugins have been updating on Ore in the last 24h and the Ore main page which should list plugins ordered by last update is not refreshed. I've tried on different browsers, on pc and on mobile.

**Comment by Yeregorix** [comment]
I've updated my plugins few hours ago and it seems to still be an issue.

**Comment by felixoi** [comment]
Yes. It isn't live on production yet.
