### ISSUE TITLE
Sentry support

### ISSUE THREAD

**Issue by lukegb** [SpongePowered/Ore#7]
Please support https://getsentry.com for error reporting, we have an account. Poke me on IRC for details.

**Comment by Zidane** [comment]
@windy1 

Isn't Ore's error reporting now hitting sentry? We can close this now.

**Comment by ryantheleach** [comment]
Is this for Ore or for plugins?

**Comment by windy1** [comment]
Ore. Sorry @ryantheleach I seemed to have misread your issue.
