### ISSUE TITLE
Improve UX for CLI Download.

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/Ore#715]
Is it possible to change the name of the file downloaded using wget when hitting up reviewed and unreviewed files?

At the moment, doing `wget https://ore.spongepowered.org/api/projects/RandomCommands/versions/recommended/download`

![image](https://user-images.githubusercontent.com/141554/48965921-08f52e00-f017-11e8-8cee-7c3f88ff11b0.png)

Results in a file called `download` containing a json response message.

```
{"message":["This version has not been reviewed by our moderation staff and may not be safe for download."," Disclaimer: We disclaim all responsibility for any harm to your server or system should you choose not to heed this warning."," Please POST to the attached link to acknowledge this disclaimer and continue to the download."],"post":"https://ore.spongepowered.org/thesilentecho/RandomCommands/versions/1.0/confirm?downloadType=1&token=123456-pokemon-3434343","url":"https://ore.spongepowered.org/api/projects/randomcommands/versions/1.0/download?token=123456-pokemon-3434343","token":"123456-pokemon-3434343"}
```

Without pretty printing, formatting, or any hard instructions on what to do with this information

It's my understanding, that `wget ${url}` works, as does the `post` variable when used with the correct curl arguments.

However, being json, without formatting or wrapping, having the file name `download`, and without any instruction on what to do with this information, barring technical knowledge that requires understanding http requests, prevents many users from 1. Discovering this functionality / message. and 2. acting on it.

So, is it possible, and would anyone be opposed to,

1. Somehow changing the name of the file based on whether the plugin was reviewed or not. (It appears to be possible: https://unix.stackexchange.com/questions/394464/download-file-with-actual-name-by-wget)
2. Pretty printing the json by default, (Does line breaks, vs a message array make any problems?).
3. Having direct instructions on some common tools to download the files.

**Comment by Faithcaio** [comment]
This should work:

`wget -O dl.jar $(wget -qO- "http://localhost:9000/api/projects/<projectId>/versions/<version>/download" | sed -n "s/^.*url\":\"\s*\(\S*\)\",.*$/\1/p")`

But there is currently a race condition when confirming the unreviewed file download so it does not :(.

@Katrix 
https://github.com/SpongePowered/Ore/blob/8aec09e2e6f5e1d099a929d30601f1f3737290b3/app/controllers/project/Versions.scala#L862
worked when `*>` is `flatMap` like before
