### ISSUE TITLE
Avatars do not display properly when logged in as unverified user

### ISSUE THREAD

**Issue by HaedHutner** [SpongePowered/Ore#720]
* Browser: `Google Chrome`

* Operating System: `Manjaro Linux x86_64`

* Page link: `https://ore.spongepowered.org/AtherysHorizons`

* Steps to reproduce:

    * Register new account
    * After reaching the page which informs you that you need to check your e-mail, go to the above page
    * No avatars are displayed.

![image](https://user-images.githubusercontent.com/26813594/49804976-aa40eb80-fd5c-11e8-88e1-f12e629a0597.png)

**Comment by felixoi** [comment]
Users should not be able to login if not verified. We currently get no information from auth about verification.

Auth discussion: https://github.com/SpongePowered/SpongeAuth/pull/266

**Comment by felixoi** [comment]
Fixed with https://github.com/SpongePowered/SpongeAuth/pull/268
