### ISSUE TITLE
Sometimes, ore discuss page doesn't show replied mark

### ISSUE THREAD

**Issue by XakepSDK** [SpongePowered/Ore#721]
* Browser: `Firefox 64.0`

* Operating System: `Arch Linux`

* Page link: `https://ore.spongepowered.org/YOUR_LINK`

Sometimes, ore discuss page doesn't show replied mark.

https://puu.sh/Cjx6x/2d638731f8.png
https://puu.sh/Cjx8F/23f5ebdcfc.png

**Comment by felixoi** [comment]
We load the discussion over an iframe from discourse. Nothing to fix in Ore here, could be a discourse bug.
