### ISSUE TITLE
When uploading new version it automatically sets to "recommended", even if remove check mark.

### ISSUE THREAD

**Issue by realGWM** [SpongePowered/Ore#732]
* Browser: `Firefox`

* Operating System: `Linux`

* Steps to reproduce:

    * Upload new version to Ore, and remove check mark from "Recommended". Version still be set as recommended.

See video:
https://www.youtube.com/watch?v=VqzKeO7erAI

**Comment by Katrix** [comment]
Problematic piece of code:
https://github.com/SpongePowered/Ore/blob/master/app/controllers/project/Versions.scala#L397

**Comment by felixoi** [comment]
Fixed https://github.com/SpongePowered/Ore/commit/2c12be2495273370cc6bc13fbc03181f36b741c8#diff-4fce6d3f66cdb7e22b3999f4b09c0c8cL397 . The fix will become active with the next deploy.
