### ISSUE TITLE
DateTimes returned from the API should be in ISO 8601 timestamp format

### ISSUE THREAD

**Issue by ItsDoot** [SpongePowered/Ore#736]
As discussed with felixoi and Katrix, it seems that currently date-times are not formatted by Ore itself, but just uses the PostgreSQL format. Ore should standardize date-times on the [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format as it is the most widely used standard across the web.

**Comment by felixoi** [comment]
Since this is breaking, this needs to be done in APIv2
