### ISSUE TITLE
Server error 

### ISSUE THREAD

**Issue by NawwDidums** [SpongePowered/Ore#742]
Was told to put this here. not sure how to reproduce it or replicate it, but it's happening alot atm.

https://pastebin.com/a72B4N5L

**Comment by kashike** [comment]
~move to sf

**Comment by limbo-app** [comment]
Hey @NawwDidums! I've moved your issue to [SpongePowered/SpongeForge#2594](https://github.com/SpongePowered/SpongeForge/issues/2594).
