### ISSUE TITLE
Ore not respecting create a forum post

### ISSUE THREAD

**Issue by ImMorpheus** [SpongePowered/Ore#754]
**Describe the bug**
I was playing around on Ore.
Created a test-project, unchecked “create a forum post”, Ore decided it was a good idea to create a forum post anyway.

**To Reproduce**
1. Go to https://ore.spongepowered.org/new
2. Create a new project
3. Uncheck "create a forum post"
4. Watch the new post on the forum

**Expected behavior**
No post

**Comment by Katrix** [comment]
Ore will always create a forum post for a new project, this is needed to get much of the functionality that Ore uses. Functions as intended.

**Comment by ImMorpheus** [comment]
Actually, I misunderstood that check entirely. "Sets if events like a new release should automatically create a post on the forums"

Read this as a feature request then.

EDIT: Oh, I see
