### ISSUE TITLE
Set CSP report URL

### ISSUE THREAD

**Issue by Aaron1011** [SpongePowered/Ore#761]
Currently, we [don't set a report URI in our CSP policy](https://github.com/SpongePowered/Ore/blob/8c8aae159c3cb85c1adbcc0e3b92615984cc09ce/conf/application.conf.template#L36). If our CSP ends up breaking a particular browser, or if an XSS attack is actually occuring, we'll have no way to find out about it.

There are two possible options for setting this up:
1. Use a third-party service like https://report-uri.com/
2. Integrate this into Ore itself (e.g. insert all reports into a table, and create an admin page to list them).

**Comment by felixoi** [comment]
Sentry support this. We should configure it to use your sentry url.

**Comment by Katrix** [comment]
Added support for this now
