### ISSUE TITLE
Stars are not working

### ISSUE THREAD

**Issue by BrainStone** [SpongePowered/Ore#762]
**Describe the bug**
You can give projects a star just fine visually, but reloading the page resets the star, like it never happened.  
I knida noticed this a few weeks back, but forgot to report it. So the issue was introduced a fair bit back. Can't remember exactly when I first noticed it. Might be even more than a month ago.

The button doesn't even work on mobile at all.

**To Reproduce**
For Desktop:
1. Go to any project
2. Click on the star button
3. Notice star appears to be given
4. Reload the page
5. Notice star being gone

For Mobile:
1. Go to any project
2. Tap on the star button
3. Nothing happens

**Expected behavior**
The stars are given not only visually, but persist even after reloading.  
And the button working on mobile

**Screenshots**
Before clicking the button:
![grafik](https://user-images.githubusercontent.com/4106544/53509724-b1a2a600-3abc-11e9-80e9-5b8802d66c68.png)

After clicking the button:
![grafik](https://user-images.githubusercontent.com/4106544/53509745-bd8e6800-3abc-11e9-80ee-dbf11b8101ec.png)

After reloading the project page:
![grafik](https://user-images.githubusercontent.com/4106544/53509773-cd0db100-3abc-11e9-9bea-0187ad23a973.png)

**Environments:**
Desktop:
 - Device Type: Desktop - Windows 10
 - Browser: Firefox
 - Version: 65.0.1 (64-bit)

Mobile:
 - Device Type: Mobile - iPhone SE
 - Browser: Firefox
 - Version: 15.0 (13894)

**Comment by Katrix** [comment]
Fixed by #775
