### ISSUE TITLE
oEmbed support

### ISSUE THREAD

**Issue by phit** [SpongePowered/Ore#767]
**Is your feature request related to a problem? Please describe.**
Discord (and similar services) doesn't show nice previews for Ore links

**Describe the solution you'd like**
add support for https://oembed.com/

<https://www.reddit.com/r/discordapp/comments/4g5taw/are_link_preview_images_only_for_whitelisted_sites/d2f1jnb/>

**Additional context**
ideally Ore should support all common standards for embeds in the future, right now it only does opengraph tags

**Comment by Katrix** [comment]
Looking over the spec, it's much more complicated than opengraph. This will have to wait.

**Comment by phit** [comment]
okay so I actually realized the issue with discord, the main page view doesnt have [any opengraph tags](https://github.com/SpongePowered/Ore/blob/9e6242c0fac72d48ba0d5cce1e19c8718ecbff54/ore/app/views/bootstrap/layout.scala.html#L22) only project pages [do](https://github.com/SpongePowered/Ore/blob/9e6242c0fac72d48ba0d5cce1e19c8718ecbff54/ore/app/views/projects/view.scala.html#L30)
![image](https://user-images.githubusercontent.com/2097483/56251735-e2628d00-60b4-11e9-9028-3279a2943c6c.png)

if we could set them on the main page like we have done for the discord bot that would make me happy without the overhead of implementing oEmbed just yet
```html
    <meta property="og:title" content="Ore">
    <meta property="og:url" content="@config.app.baseUrl">
    <meta property="og:image" content="/assets/images/ore-dark.png" />
    <meta property="og:description" content="A Minecraft Package Repository" />
```

**Comment by felixoi** [comment]
So we can close this with https://github.com/SpongePowered/Ore/pull/796 you think?

**Comment by phit** [comment]
I guess, oEmbed support would still be nice at some point.

**Comment by Katrix** [comment]
Likely not going to happen. We need to dynamically resize thumbnails we don't even store, or return errors for very reasonable requests to be able to implement this. We'll stick with OpenGraph for now
