### ISSUE TITLE
Duplicate entry in search

### ISSUE THREAD

**Issue by pie-flavor** [SpongePowered/Ore#768]
**Describe the bug**
A duplicate entry is shown in the search menu.

**To Reproduce**
1. Go to ore.spongepowered.org
2. Search for 'trade'
3. Observe that CJcool06's SafeTrade appears twice

**Expected behavior**
No duplicates.

**Screenshots**
https://i.imgur.com/zJNav6u.png

**Environment:**
 - Desktop
 - Chrome
 -  72.0.3626.121

**Comment by Katrix** [comment]
Duplicate of #764
