### ISSUE TITLE
Bug: Can't create additional Release Channels

### ISSUE THREAD

**Issue by DosMike** [SpongePowered/Ore#769]
**Describe the bug**
So I'm pretty sure I've used this feature in the past, but right now I can't create additional Release Channels for any of my plugins, nor edit existing ones.

In the channel list itself, the button just doesn't seem to do anything.
When trying to create a channel while uploading a plugin the confirmation button is just a small textless box, that redirects to the main Ore listing.

**To Reproduce**
1. Channel Manager
* Go to a Plugins Version page
* Click [Edit] on the Channels box
* Click the +
* Fill the form
* Click [Create Channel]
* For disappears, nothing happens
2. Plugin Upload
* On the corresponding page click the + to create a channel
* Fill the form
* Click on the small orange box
* Get redirected to the plugin listing, no channel was created

**Expected behavior**
Clicking the Create Channel button to create the configured channel

**Screenshots**
![grafik](https://user-images.githubusercontent.com/9415671/53874833-8f041600-4003-11e9-9344-8049d5995c29.png)

**Environment (please complete the following information):**
 - Windows 7
 - Firefox 65.0.2 (64-Bit)

**Comment by Himmelt** [comment]
This problem still exists. Win10 64bit, Chrome x64.
