### ISSUE TITLE
Add proper error when trying to upload conflicting version

### ISSUE THREAD

**Issue by trentech** [SpongePowered/Ore#789]
**Describe the bug**
I uploaded the wrong jar, so I deleted it. I attempted to add the correct one, same version number and I'm presented with a Technical Difficulties page. Thought maybe it was some kind of replication issue so I've waiting 12 hours and tried again with the same results

**To Reproduce**
1. Go to 'Versions'
2. Click on 'jar version number'
3. Click 'Delete'
4. Go to 'Versions'
5. Click on 'New Version'
6. Follow usual steps for adding jar
7. Technical Difficulties page

**Expected behavior**
I expected it to add my jar file like usual

**Environment (please complete the following information):**
 - Device Type Desktop and Laptop, both Windows 10
 - Browser tried Chrome, Firefox, IE

**Comment by Katrix** [comment]
Reuploads using the same version number are disallowed currently on Ore, and it will likely stay that way. The technical error thing is a thing we should fix though.
