### ISSUE TITLE
Notifications should not show who approved a plugin

### ISSUE THREAD

**Issue by dualspiral** [SpongePowered/Ore#798]
**Describe the bug**
As part of the review process, reviewers should be anonymous. However, upon approval of a plugin, the notification shows the avatar of the person who marked it as safe - it should not.

I don't know if this is the case for plugins marked as requiring changes.

**To Reproduce**

* Upload a plugin
* Hope it gets approved
* Look at the notifications
* See that the notification says that the plugin was approved, and that the avatar is that of a reviewer's

**Expected behavior**
The notification should not have any way to identify who reviewed the plugin

**Screenshots**
I won't do this, as it reveals who has been reviewing Nucleus.

**Environment (please complete the following information):**
N/A

**Additional context**
I don't know if this happens on "requires changes", but I'd check that too.

**Comment by progwml6** [comment]
unless someone has the appropriate permissions(some staff level to be determined) the approver name should not be displayed

**Comment by felixoi** [comment]
It should just never be displayed. Staff with enough permissions can always look into the review log to find out who approved a version.
