### ISSUE TITLE
Github signin

### ISSUE THREAD

**Issue by gratimax** [SpongePowered/Ore#8]
Signing in with GitHub works well with the Ore accounts system. Github usernames seem mostly valid as Ore usernames.

This would be done with OAuth, needing the `user:email` scope from GitHub in order to fill in the email.

**Comment by lukegb** [comment]
It might be worth thinking about SSO with the forums at this point.

**Comment by pschichtel** [comment]
#35 is an issue for the forum SSO

**Comment by gratimax** [comment]
Let's migrate the issue over to there, then.
