### ISSUE TITLE
Manual (web-interface) and automatic (Gradle, API) deploy have different minimum character limit for Changelog/Release Bulletin.

### ISSUE THREAD

**Issue by VcSaJen** [SpongePowered/Ore#805]
**Describe the bug**
Manual (web-interface) and automatic (Gradle, API) deploy have different minimum character limit for Changelog/Release Bulletin. Web-interface allows to have any minimum length, but if you try to automatically deploy through gradle, it will error out with "Content too short" message.

**To Reproduce**
1. Try to manually add version to project. In "New project release" page, edit "Release Bulletin" section. Type any text with 1-14 character length (For example, "1"). Site will allow it.
2. Open or create OreTestPlugin project
3. Add or change `changelog='1'` (or any string with length of 1-14 characters) to oreDeploy section.
4. Execute `oreDeploy` task.
5. See error:
```
:oreDeploy
Publishing oretest to https://ore.spongepowered.org.
  Recommended: false
  Channel: snapshot
[failure] 400 Bad Request
* changelog
  - Content too short.
:oreDeploy FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':oreDeploy'.
> Deployment failed.
```

**Expected behavior**
A consistent minimum character limits in both web-interface and API.

**Environment**
Any

**Additional context**
n/a

**Comment by Katrix** [comment]
The automatic checks are probably the correct ones

**Comment by VcSaJen** [comment]
@Katrix Actually, when changelog is not provided in automatic one, it just results in release with 0 character length changelog.

**Comment by Katrix** [comment]
Hm, think the reason this work is that we add some more content around the version description. Probably safe to remove the limits elsewhere then because of that.
