### ISSUE TITLE
Spongie logo at the bottom is rather difficult to highlight

### ISSUE THREAD

**Issue by gabizou** [SpongePowered/Ore#82]
When trying to click on the Spongie icon (to the point where it transitions from a gray sponge to a yellow spongie), it seems like it's only able to change color only when the cursor is _exactly_ on Spongie, and not in any of the transparent areas of the logo.

**Comment by windy1** [comment]
I'm not really sure what you mean by this @gabizou. Do you want it to highlight when you aren't hovering over the logo? That seems a bit odd.

**Comment by gabizou** [comment]
@windy1 no, it's that if my cursor is between the eyes of Spongie at the bottom, the logo isn't highlighted.

**Comment by windy1** [comment]
Huh, interesting, seems to be specific to safari.
