### ISSUE TITLE
Navigation header bounds are slightly too small

### ISSUE THREAD

**Issue by MichaelFedora** [SpongePowered/Ore#83]
I.e. I can't go to the "Homepage"/"Forums"/"Code"/etc. because whenever I drag my cursor down it all disappears.

This is on Chrome v49, Windows 10 x64.

**Comment by Zidane** [comment]
@MichaelFedora 

Cannot reproduce this issue. You hover over Sponge then move your mouse down to your selection then click.

**Comment by MichaelFedora** [comment]
I do, and it disappears right as I'm moving my mouse down. I can try a different browser...

ed: it works if I do it fast enough. But only if I'm fast enough. Try going slow.

**Comment by ryantheleach** [comment]
![image](https://cloud.githubusercontent.com/assets/141554/14927074/e0387538-0e8e-11e6-9ad7-bce3f66a9894.png)

**Comment by MichaelFedora** [comment]
[Gyfcat Link](https://gfycat.com/IdealSmallCormorant)

Granted the capture kinda made it a little buggy. But that's basically what happens.

**Comment by liach** [comment]
No one really move their mouse so slowly...

**Comment by ryantheleach** [comment]
I assume it depends on PC load, performance, mouse polling rates, and zoom level, but I had to move my mouse extremely fast in order to get the menu to show @liach

**Comment by windy1** [comment]
@ryantheleach I don't understand, is it fixed now?

**Comment by MichaelFedora** [comment]
It is now, thanks @windy1!
