### ISSUE TITLE
Misc issues with Staging

### ISSUE THREAD

**Issue by phit** [SpongePowered/Ore#837]
* [x] [Upload new file, the select file box needs some padding lovin](https://cdn.discordapp.com/attachments/424686430854316042/589939519197937817/unknown.png)

* [x] [Next screen in the create channel dialog it should check the channel name and color clientside](https://cdn.discordapp.com/attachments/424686430854316042/589940813744570368/unknown.png)
  * consider closing the dialog when a channel is made, theres no indication it was successful

* [ ] [You can still make pages that are inaccessible, funny side note the prompt when making pages said it fails, but after a refresh they are in the sidebar](http://ore.stg.sponge.h.aetherpaw.com/phit/NoChat)

* [x] [missing a 0 here for watchers on the project page?](https://user-images.githubusercontent.com/2097483/59570375-59a5a480-9097-11e9-99c2-fba05cd346f8.png)

**Comment by Katrix** [comment]
Moved to minor issues list
