### ISSUE TITLE
Disallow spaces in project names (or have separate slugs)

### ISSUE THREAD

**Issue by lukegb** [SpongePowered/Ore#9]
Spaces don't translate well to URLs (%20 everywhere), so if you're going to allow them in project names we need slugs which are different (and are separately deduplicated)

Alternatively, just don't allow spaces in project names, and push people to using `-` and `_` instead (potentially automatically replacing spaces with `-` like GitHub itself does)

**Comment by windy1** [comment]
Thanks for making an issue for this. Definitely something I've thought about. I think spaces should be allowed in project names but just replacing dashes in the URL pattern. It would probably be a good idea to come up with a regex pattern for names as well as currently anything is allowed.

**Comment by lukegb** [comment]
If you do, make sure you actually make a new database column for the URL slug and mark that unique with the namespace to avoid conflicts :+1:
