### ISSUE TITLE
No "discuss" link on Plugin Page

### ISSUE THREAD

**Issue by MichaelFedora** [SpongePowered/Ore#91]
[My plugin](https://ore-staging.spongepowered.org/MichaelFedora/Fedora's-Economy) doesn't have a [discuss link](https://ore-staging.spongepowered.org/MichaelFedora/Fedora's-Economy/discuss).. probably because my ore-thread survived when you cleared the Ore-Staging data?

Dunno, but still an issue :3

**Comment by windy1** [comment]
That's probably exactly what happened actually, I've relinked your topic manually. Shouldn't happen for future projects.
