### ISSUE TITLE
Plugin/Server error log collecting?

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/Ore#93]
https://github.com/SpongePowered/SpongeAPI/pull/793

As discussed in the link above, there was talk of submitting errors from plugins to plugin developers with the server owners permission.

**Comment by windy1** [comment]
https://github.com/SpongePowered/Ore/issues/7

**Comment by phase** [comment]
This goes with #410

**Comment by ryantheleach** [comment]
I don't think so, let me reword. SpongePowered/SpongeAPI#793 Is talking about automated pretty reports and submissions. Where as this ticket would probably have some form of analysis and grouping capabilities of stack traces.

Having it just post as a forum thread would be less then awesome.

**Comment by phase** [comment]
We could prettify the error and post it on the plugin subforum for discussion. Or<sup><sub>(e)</sup></sub> we could make an issue system like GitHub or Sentry.

And what happened with that PR? It says it was closed in favor of https://github.com/SpongePowered/SpongeAPI/pull/1215 which was also closed. These features would preferably need to be written together. We can throw it in another branch.

**Comment by Katrix** [comment]
We might make something like this in the far future, but for now, just use something like Sentry.
