### ISSUE TITLE
Add (API|SForge|SVanilla) Version to plugins

### ISSUE THREAD

**Issue by FerusGrim** [SpongePowered/Ore#95]
I was thinking we could add this information to the front-page of the plugin for the most recent release, as well as show it for each release on the releases page.

For those with GitHub, perhaps we could even scrub the build information for it.

**Comment by simon816** [comment]
Plugins should really be adding the SpongeAPI to their dependencies list anyway in the same way that you should do with Forge in `requiredMods` (_[spec](https://github.com/MinecraftForge/FML/wiki/FML-mod-information-file)_).

**Comment by kashike** [comment]
:+1: for including API/SForge/SVanilla versions in dependencies/`mcmod.info`

**Comment by JBYoshi** [comment]
I'm working on adding that to the annotation processor. I should have a PR out shortly; just testing out some changes I made to the build script to make sure they don't wreck anything else.

**EDIT:** Published. The links to the PRs are below.

**Comment by kinggoesgaming** [comment]
IMO only API should be add as plugins should avoid specially making plugins made for a specific version of SpongeForge/SpongeVanilla

**Comment by kashike** [comment]
I disagree, @kinggoesgaming. Plugins should be allowed to specify a dependency on whatever they wish. Keep in mind that dependency strings have maven-style matchers, so you can specify minimum/maximum versions, etc.

**Comment by kinggoesgaming** [comment]
@kashike i said 

> plugins should _avoid_ ... making plugins made for a specific version of SpongeForge/SpongeVanilla

and not

> plugins shouldnt make plugins for a specific version of SpongeForge/SpongeVanilla

There is a difference. :stuck_out_tongue:

**Comment by FerusGrim** [comment]
@kinggoesgaming 
For users who only supply API dependency, Ore could still use that API version to determine compatible SForge/SVanilla versions.

**Comment by windy1** [comment]
API version is now displayed in the dependencies panel of individual version pages if the `spongeapi` dependency is included in the `mcmod.info` file.
