### ISSUE TITLE
Projects and their information are not centered in rows of projects

### ISSUE THREAD

**Issue by parlough** [SpongePowered/Ore#96]
![3](https://cloud.githubusercontent.com/assets/18372958/14945512/b5e66420-0fd8-11e6-839b-8a346d105810.png)
The downloads, views, project name, category icon, project description, and stars are not centered in the row. It seems only the icon is. Everything else is too far up in the row. This appears on any project list including on profiles.

**Comment by windy1** [comment]
Looks like the scss migration might have had a few unintended side-effects. Should be fixed momentarily.

**Comment by parlough** [comment]
@windy1 Looks like it either hasn't changed or it has gotten worse.

**Comment by windy1** [comment]
It's still building, give it a few minutes.
