### ISSUE TITLE
View counter on project list stops after 100 - Too small/looks weird

### ISSUE THREAD

**Issue by parlough** [SpongePowered/Ore#97]
![4](https://cloud.githubusercontent.com/assets/18372958/14945546/2f6c9e40-0fd9-11e6-9660-86a294673525.png)
100 views is such a small number, and that will be passed by most plugins pretty quickly, and possibly in downloads for more popular plugins soon as well. I am not sure of a good solution for this, but it is almost pointless to display when all projects will soon just have just multiple dots.

**Comment by simon816** [comment]
Agree. It should be able to display 3 to 4 characters e.g `800`, `1.3k`
