### ISSUE TITLE
Views can be continuously added up

### ISSUE THREAD

**Issue by 12awsomeman34** [SpongePowered/Ore#98]
Step 1: I viewed the ore homepage on chrome. I had 28 views on my plugin.
Step 2: Loaded my plugin's home page in firefox (or just close chrome and reopen, or incognito)
Step 3: Refresh initial page on chrome. 29 views.

Could probably bot the view count up if I had the time to write one. Probably not a good thing to let users do though.

**Comment by windy1** [comment]
Yeah this is something I've been meaning to get around to. Currently Ore checks for a cookie in the db for unauthed users and a cookie and/or a user id for authed users. I was planning on adding an additional check for IP addresses as well.

**Comment by windy1** [comment]
Handled in https://github.com/SpongePowered/Ore/commit/94828427190cda9b4aeb0f4e834b9110dff781bd
